### ISSUE TITLE
Router Store: VERY unexpected behavior: navigateIfNeeded

### ISSUE THREAD

**Issue by NicBright** [ngrx/platform#3641] opened 2022-11-02 15:30 UTC
### Which @ngrx/* package(s) are the source of the bug?

router-store

### Minimal reproduction of the bug/regression with instructions

It's obvious when looking at NgRx' source code.

### Minimal reproduction of the bug/regression with instructions

It's obvious when looking at NgRx' source code.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 12.5.1
Angular: 12

### Other information

Hi there

I was completely puzzled when I've learned that the reason for a very odd navigation bug in our app was due to the `StoreRouterConnectingModule` **interfering with router navigation.** It is very mysterious, that NgRx thinks it is ok to do any navigation at all on behalf of the application. In my understanding, the NgRx Router Store is only mirroring the state of the Angular router. Never would I have imagined that it tries to enforce routing based on the NgRx Store Router state slice.

**This behavior is not documented!**

Ok, putting this surprise aside, and accepting it for the moment ... then there's still a big BUT: 

Because of missing (Angular) router state checks ("are we in the middle of a route navigation?"), in our case, this happens **during a route navigation** (because we're updating the store via an action which triggers `navigateIfNeeded()`) which leads to errors because, **of course**, in the middle of a route navigation the NgRx router store state is **not up-to-date** which tricks **navigateIfNeeded()** into thinking that it should navigate .... and this effectively kills the current route navigation (which is **still in the middle of being processed**).

To properly fix this, I suggest that NgRx Router Store keeps track whether a navigation is still being in progress or not: Execution of **navigateIfNeeded()** should be queued in a way that this method is run only when all on-going navigation has finished.

This issue can also be fixed via configuration (for us):
We don't need NgRx Router Store to do any navigation on behalf of our application. Therefore a config option could be added that disables this behavior (e.g. it could make **navigateIfNeeded()** return early). This config option could be named `navigateIfNeeded`, defaulting to `true` to be non-breaking.

Best Regards
Nicolas

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by NicBright** [comment] 2023-01-24 09:44
Ping. This issue is still bugging us. @brandonroberts could you please share your thoughts on this?

**Comment by timdeschryver** [comment] 2023-01-24 17:51
Can you reproduce this behavior in a simple repo @NicBright ?
There are some checks to verify that we don't interrupt a navigation that is in progress, which should prevent this from happening.


Like you already mentioned, maybe that we can look into a config to be able to turn this behavior off, and just be able to use @ngrx/router-store to read/react to router state changes. I think most of us use router-store specifically for this feature, and not to navigate using actions (at least from what I've seen).

**Comment by timdeschryver** [comment] 2023-04-15 13:14
I'm closing this because it has no reproduction.

**Closed by timdeschryver** 2023-04-15 13:14 UTC
Labels: enhancement, Project: Router Store
