### ISSUE TITLE
[Store || Effect] Lazily loaded modules uses different store object.

### ISSUE THREAD

**Issue by ycbayrak** [ngrx/platform#1639] opened 2019-03-19 17:22 UTC
Versions

`@angular/*: 7.2.3`
`@ngrx/effects: 7.3.0`
`@ngrx/store: 7.3.0`

Hello there. Why are lazy-loaded modules using different State objects? What I'm trying to do, but I'm not successful, is that I have to dispatch actions in the newly installed module using the values in the root store object.

Suppose, we have defined a reducer in `AppModule` with `StoreModule.forRoot(reducer)` and the initial state looks like this;

```json
{
   "root": {"active": 1}
}
```
And a lazy-loaded module with, `StoreModule.forFeature("lazy", reducer)` imported.

When that lazy-loaded module initialized, it's like creating a new store object and using the initial value of root reducer. 

How to avoid that? Thank you.

**Comment by dummdidumm** [comment] 2019-03-20 15:27
What you tell ngrx by importing `StoreModule.forFeature("lazy", reducer)` is "please add a new reducer with root path 'lazy'", so your state becomes:
```
{
   "root": {"active": 1},
   "lazy": /* whatever reducer's initial state looks like */
}
```
If you just want to use the root state, then you don't have to use that import statement, just use the selectors/actions from your root.

**Comment by timdeschryver** [comment] 2019-03-20 18:19
This is by design and is explained in our [docs](https://ngrx.io/guide/store/reducers).
I'm going to close this issue, but if something is unclear feel free to respond.

**Closed by timdeschryver** 2019-03-20 18:19 UTC
