### ISSUE TITLE
[store-devtools] no store found if app already running

### ISSUE THREAD

**Issue by nasreddineskandrani** [ngrx/platform#966] opened 2018-04-11 02:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Steps: (tested on chrome browser)
1. we already have our app running in the browser (devtools closed)
2. we open the devtools of chrome for example
3. redux extension shows `No Store Found...` Message.
note: if i do anything in the app that dispatch an action or refresh the browser tab by keeping devtools open then the store shows.

## Expected behavior:
Steps: 
1. we already have our app running in the browser (devtools closed)
2. we open the devtools of chrome for example
3. redux extension should show the current state of the store without any extra developer action

## Minimal reproduction of the problem with instructions:
you can try it here:
https://github.com/nasreddineskandrani/example-angular-full

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome
Version 65.0.3325.181 (Build officiel) (64 bits)

## Other information:
print screen for message ` no store found ...`
![image](https://user-images.githubusercontent.com/1953635/38593531-c6ae928a-3d0f-11e8-8d08-bdb448979a06.png)

I can work on that or one of my friend to find a solution for this problem and do a PR. I already have something in mind.

**Comment by brandonroberts** [comment] 2018-04-11 12:53
Duplicate of #508

**Closed by brandonroberts** 2018-04-11 12:53 UTC
