### ISSUE TITLE
Unit Tests Breaking : Uncaught TypeError: Cannot read property 'entities' of undefined

### ISSUE THREAD

**Issue by cport1** [ngrx/platform#1546] opened 2019-02-08 20:34 UTC
I am getting this error randomly on different unit tests. It breaks on a different unit test each time tests are ran. However, sometimes all tests pass successfully.

Angular Version: 7.2.4
@ngrx Version: 7.0.0

**Comment by cport1** [comment] 2019-02-08 20:36
Oh, I think upgrading ngrx to 7.2.0 fixed the issue

**Comment by cport1** [comment] 2019-02-08 21:02
I think what ultimately fixes the issue is destroying the feature after create component

```
  beforeEach(() => {
    fixture = TestBed.createComponent(ComponentNameComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });
  afterEach(() => {
    fixture.destroy();
  });
```

**Comment by BBlackwo** [comment] 2019-08-16 03:05
It's quite annoying to have to add the `fixture.destroy();`. I've never had to do this for anything else as a fresh one is always created in each `beforeEach`. Why is this necessary?

**Comment by flaviuse** [comment] 2019-08-28 12:42
Really annoying it's breaking our verification system, even with fixture.destroy() it randomly fail. We have git pre hooks that run test on push ...

**Comment by cport1** [comment] 2019-08-29 15:35
> Really annoying it's breaking our verification system, even with fixture.destroy() it randomly fail. We have git pre hooks that run test on push ...

Does it fail on a different component each run?

**Comment by timdeschryver** [comment] 2019-08-30 16:23
Does anyone have a small reproduction of this behavior?

**Comment by timdeschryver** [comment] 2019-09-03 18:30
Closing this in favor of #2044, because I think it's a duplicate.
If it's not the case feel free to create a reproduction and create a new issue.

**Closed by timdeschryver** 2019-09-03 18:30 UTC
Labels: Needs Reproduction, Project: Store

**Comment by noylev** [comment] 2020-01-30 16:01
happens for me as well, I tried to add `afterEach(() => {
    fixture.destroy();
});` in one test and it helped for more tests to pass, but then another random test had failed...

**Comment by pras7430** [comment] 2020-09-09 16:38
facing the same issue, 

` An error was thrown in afterAll
  error properties: Object({ longStack: 'TypeError: Cannot convert undefined or null to object`

**Comment by aidanxyz** [comment] 2021-02-26 09:31
I had a similar error:
`An error was thrown in afterAll error properties: Object({ longStack: 'TypeError: Cannot ...`
and it turned out I just forgot to mock one selector, the value which it was supposed to emit wasn't being checked in the given component tests, therefore sometimes everything would pass, and sometimes throw an error.
