### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when dispatching the same action from multiple components

### ISSUE THREAD

**Issue by ValentinBossi** [ngrx/platform#3989] opened 2023-08-05 10:34 UTC
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

hi
i can provide a reproduction for https://github.com/ngrx/platform/issues/273: https://stackblitz.com/edit/stackblitz-starters-lowehc (its a node project. so make sure `npm install` in the "ngrx-dis-exp" directory + `ng serve`. everything is in `main.ts`)
steps for reproduction:

1. click on "Menu"
2. click on "Order 1"
3. check the console for ExpressionChangedAfterItHasBeenCheckedError

### Expected behavior

i really would not expect this error cause its the nature of an observable to change its value over time. in general i would say i see this setup/steps/process as a valid implementation which should work.
thank you for the help!

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16.1
Angular: 16.1
Node: 16.20
Browser: Chrome 115

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment] 2023-08-11 18:14
As mentioned in the referenced issue, I think this is something that we can't fix.
The problem is that the state property is changed after a change detection.
This is because both actions update the same state property, and the property is rendered in the component.

**Comment by ValentinBossi** [comment] 2023-08-11 19:49
hm thats a bit unsatisfying. i tried to have a component which has a `@Input` for the value but this also does not help. i dont want to open this change detection topic here cause there are 1000 blogs about that.

1. is there a solution to this problem? (except of `setTimeout`)
2. does a zone less app have this problem?
3. could it happen that a backend request cause such a problem? cause it also could update the same state property.

**Comment by ValentinBossi** [comment] 2024-01-15 13:23
@timdeschryver with [signalStore](https://stackblitz.com/edit/stackblitz-starters-z7qxn3?file=ngrx-dis-exp%2Fsrc%2Fmain.ts) it is working without an error.
if an short explonation is possible, why this is working with signals but not with "Observable's", then i would very appreciate it.

**Comment by rainerhahnekamp** [comment] 2024-01-31 16:36
Your stackblitz doesn't seem to work anymore and the source code shows that you are using the NgRx Global and not the SignalStore. Do you have an updated GitHub repo? Would be interested to give it a try.

**Comment by ValentinBossi** [comment] 2024-01-31 16:47
hi @rainerhahnekamp it is actually the signalStore. i just commented out the unused non-signal store code. for me the stackblitz is working, just checked it now.

**Comment by rainerhahnekamp** [comment] 2024-01-31 18:24
@ValentinBossi, that is an Angular-related problem. I removed the SignalStore and used a simple signal instead. It shows the same error: https://stackblitz.com/edit/stackblitz-starters-om9ryw?file=src%2Fmain.ts

Could you please open an issue at the Angular project directly and (if possible, include me there? I would be curious about the outcome).

I think we can close the issue here.

**Comment by ValentinBossi** [comment] 2024-02-01 09:19
@rainerhahnekamp done in https://github.com/angular/angular/issues/54197.
i also added there the note that the code is working when applied in the constructor. i do not append the comment to this constructor vs ngOnInit thing here, please read the note in https://github.com/angular/angular/issues/54197 about that.

**Comment by markostanimirovic** [comment] 2024-02-01 19:21
Closing this issue since it's not related to NgRx directly.

**Closed by markostanimirovic** 2024-02-01 19:21 UTC
