### ISSUE TITLE
Getting compiler error on 11.0.0 when installed with Angular CLI?

### ISSUE THREAD

**Issue by DrewMoody** [ngrx/platform#2924] opened 2021-02-12 23:07 UTC
## Minimal reproduction of the bug/regression with instructions:
Not sure if this is an ngrx bug, maybe Angular CLI bug, or if it's even reproducible.

I started a fresh Angular app through the CLI, then added ngrx with `ng add @ngrx/store@latest --minimal false` as stated in the docs. That gave the following compiler error (v 11.0.0): 
```
ERROR in node_modules/@ngrx/store/src/reducer_creator.d.ts:32:99 - error TS1005: ',' expected.

32 export declare function on<State, Creators extends readonly ActionCreator[]>(...args: [...creators: Creators, reducer: OnReducer<State, Creators>]): ReducerTypes<State, Creators>;
```
Downgrading to v10.2.1 resolved the issue. Then I uninstalled it completed, reinstalled latest (v11.0.0) with npm install (NOT the cli), and now it works :shrug:.

## Expected behavior:
Able to init Angular app through CLI and install ngrx with Angular CLI as mentioned in the docs

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx latest, v11.0.0. Angular v11.2.0, node v.12.1.0, any, MacOS Big Sur

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No - not sure about source of issue

**Comment by grayey** [comment] 2021-02-14 00:27
Same  issue here @DrewMoody . A compiler error. A new project I started today

ERROR in node_modules/@ngrx/store/src/reducer_creator.d.ts:32:99 - error TS1005: ',' expected.

32 export declare function on<State, Creators extends readonly ActionCreator[]>(...args: [...creators: Creators, reducer: OnReducer<State, Creators>]): ReducerTypes<State, Creators>;

**Comment by grayey** [comment] 2021-02-14 00:37
Downgrading to "@ngrx/store": "^10.1.2" solved it

**Comment by timdeschryver** [comment] 2021-02-14 12:25
I was not able to reproduce this.
Can you make sure that you're also on angular v11, and more important typescript v4.1?

**Comment by david-ae** [comment] 2021-02-15 14:49
@grayey had the same issue. Applied your fix. Worked for me.

**Comment by david-shortman** [comment] 2021-02-20 07:05
Could not reproduce either. Ran the following:
```sh
yarn global remove @angular/cli
yarn global add @angular/cli
ng new my-app  # selected defaults for all
cd my-app 
ng add @ngrx/store@latest --minimal false
```
with successful output:
```
ℹ Using package manager: npm
✔ Package information loaded.
✔ Package successfully installed.
CREATE src/app/reducers/index.ts (359 bytes)
UPDATE src/app/app.module.ts (473 bytes)
UPDATE package.json (1225 bytes)
✔ Packages installed successfully.
```

**Comment by timdeschryver** [comment] 2021-02-20 12:46
I'm closing this issue.
On stackoverflow this error also pops up in multiple questions, in all of the cases the culprit was a lower version of TypeScript.
If this issue is reproducible with the latest angular version, and the latest ngrx version, feel free to reopen (or create a new) this issue with the reproduction.

**Closed by timdeschryver** 2021-02-20 12:46 UTC

**Comment by niralishah1599** [comment] 2021-03-26 14:35
> Downgrading to "@ngrx/store": "^10.1.2" solved it

thank you @grayey

**Comment by goyalarchit101** [comment] 2021-04-14 03:24
> Downgrading to "@ngrx/store": "^10.1.2" solved it

it worked for me, thanks

**Comment by Tamal2017** [comment] 2021-04-21 21:16
Downgrading to "@ngrx/store": "^10.1.2" solved it

it also worked for me, thanks

**Comment by JeremiasAragon** [comment] 2021-09-25 15:39
Downgrading to "@ngrx/store": "^10.1.2" solved ii but i also had to Downgrade the complementary libraries to "^8.0.1".
"@ngrx/effects": "^8.0.1",
"@ngrx/router-store": "^8.0.1",
"@ngrx/store": "^10.1.2", 
"@ngrx/store-devtools": "^8.0.1",

**Comment by antonymaia** [comment] 2021-11-25 13:09
> Fazer downgrade para "@ ngrx / store": "^ 10.1.2" resolveu o problema

solved my problem, tks
BR: Essa solução resolveu o meu problema
