### ISSUE TITLE
`npx ng generate container` yields "merge conflicted" error

### ISSUE THREAD

**Issue by RobertAKARobin** [ngrx/platform#2343] opened 2020-01-30 20:37 UTC
## Minimal reproduction of the bug/regression with instructions:

- Using `@angular/cli@9.0.0-rc.11`, create an Angular app with `ng new`
- `npm i -D @ngrx/schematics`
- `npx ng config cli.defaultCollection @ngrx/schematics`
- `npx ng generate ng-add`
- Attempt to `npx ng generate container something`
- Observe the error `A merge conflicted on path "/src/app/something/something.component.spec.ts"`

https://github.com/robertAKARobin/coffeetable_200130_ng9

## Expected behavior:

No error should be thrown.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

```
    "@angular/animations": "~9.0.0-rc.11",
    "@angular/common": "~9.0.0-rc.11",
    "@angular/compiler": "~9.0.0-rc.11",
    "@angular/core": "~9.0.0-rc.11",
    "@angular/forms": "~9.0.0-rc.11",
    "@angular/platform-browser": "~9.0.0-rc.11",
    "@angular/platform-browser-dynamic": "~9.0.0-rc.11",
    "@angular/router": "~9.0.0-rc.11",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/entity": "^8.6.0",
    "@ngrx/schematics": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "@angular-devkit/build-angular": "~0.900.0-rc.11",
    "@angular/cli": "~9.0.0-rc.11",
    "@angular/compiler-cli": "~9.0.0-rc.11",
    "@angular/language-service": "~9.0.0-rc.11",
```

Mac OS 10.15.2

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment] 2020-01-30 21:03
This should be resolved when we release version 9 of NgRx.
We ran into the same problem when we upgraded to Angular 9rc. The cause is the renamed `skipTest` flag.

**Comment by brandonroberts** [comment] 2020-02-05 03:44
Just leaving a note to close this after we cut the first 9.0 beta

**Comment by RobertAKARobin** [comment] 2020-02-05 03:52
I assume that will happen after Angular 9 is released?

**Comment by brandonroberts** [comment] 2020-02-05 04:12
The plan is to cut the first beta this week

**Comment by timdeschryver** [comment] 2020-02-16 09:30
I verified this is working with the v9 beta release.
If this is not the case for you @RobertAKARobin , feel free to re-open the issue.

**Closed by timdeschryver** 2020-02-16 09:30 UTC
Labels: Project: Schematics
