### ISSUE TITLE
ROUTE_CANCEL doesn't contain router state before cancelled navigation

### ISSUE THREAD

**Issue by sommcz** [ngrx/platform#594] opened 2017-11-22 21:58 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
ROUTE_CANCEL action contains same RouterState as ROUTER_NAVIGATION (cancelled route information)

## Expected behavior:
ROUTER_CANCEL contain the store state before the navigation. So the routerReducer can restore it after cancellation with guard

## Minimal reproduction of the problem with instructions:
http://plnkr.co/edit/lNm2JAEtfxw0VRrEuS8c?p=preview

- run plunkr
- click Away link (router goes to away url and shows it form routerReducer)
- then click another link (eg. Go here...) => Guard stops navigating, but there is new URL in the routerReducer.state.url ;-(

Do i missing something?

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome 62.0.3202.94, NPM 5.5.1, Node v8.5.0, ngrx

**Comment by brandonroberts** [comment] 2017-11-30 02:36
Duplicate of #572

**Closed by brandonroberts** 2017-11-30 02:36 UTC
Labels: bug, Project: Router Store
