### ISSUE TITLE
action dispatched might fires before associated effect is fully loaded

### ISSUE THREAD

**Issue by rernens** [ngrx/platform#352] opened 2017-09-06 14:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## What is the current behavior?

After converting angular-advanced-seed to use @ngrx v4, the multilingual service which uses @ngrx to handle language state change works just fine.

When expanding the seed with additional  modules, components, reducers and effects, the multilingual module fails to handle initial translation properly because the multilingual effect associated with language change action is not initially triggered due to timing issue : the change language action is dispatched before the multilingual effect is instantiated and ready.

## Expected behavior:

Expanding an application should not affect instantiation of effects or action dispatch should wait for all effects to be ready for use.

## Version of affected browser(s),operating system(s), npm, node and ngrx:

see issue #351 

## Other information:

using setTimeout to delay the initial dispatch of the change Language action  for browser language fixes the issue but is not safe.

**Comment by brandonroberts** [comment] 2017-09-07 02:34
Duplicate of #246

**Closed by brandonroberts** 2017-09-07 02:34 UTC
