### ISSUE TITLE
Angular 6 Library with store

### ISSUE THREAD

**Issue by phsims** [ngrx/platform#1077] opened 2018-05-17 14:33 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## What is the current behavior?
Cant generate store files for Angular 6 Library, I get 
`Specified module does not exist`

**Comment by brandonroberts** [comment] 2018-05-17 15:51
Will you provide a reproduction of the issue? Are you using the latest beta or current version?

**Comment by phsims** [comment] 2018-05-18 07:12
I can generate the store fine for the root.  My package.json file is below

```
 "dependencies": {
    "@angular/common": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/animations": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@ngrx/effects": "^6.0.0-beta.3",
    "@ngrx/entity": "^6.0.0-beta.3",
    "@ngrx/store": "^6.0.0-beta.3",
    "@ngrx/store-devtools": "^6.0.0-beta.3",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.0",
    "@angular-devkit/build-ng-packagr": "~0.6.3",
    "@angular-devkit/build-angular": "~0.6.1",
    "ng-packagr": "^3.0.0-rc.2",
    "tsickle": ">=0.25.5",
    "tslib": "^1.7.1",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.1",
    "@angular/language-service": "^6.0.0",
    "@ngrx/schematics": "github:ngrx/schematics-builds",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
```

**Comment by tdeschryver** [comment] 2018-05-18 10:08
Could you show which commands you ran, so we could reproduce this?
And just to be sure, the module does exist (because the ngrx command doesn't create the module by itself)?

**Comment by sandangel** [comment] 2018-05-18 21:11
@phsims I guess you are trying to generate a store schematics for a angular library created by `ng g lib`. I think you should not use store in your library which will lead to 2 different store object (2 different source of truth) in the user application. I think ngrx should only be used in the application. To answer the question do you need to use ngrx in your application, take a look at this tweet (all the comments too):
https://twitter.com/MikeRyanDev/status/988074545834811393

 If you want to you can still do that by specifying the module you want to generate store in to. By default schematics will try to generate it to the app.module.ts in projects/<lib-name>/src/app/app.module.ts with the store for root. 

For more information take a look at docs at https://github.com/ngrx/platform/blob/master/docs/schematics/store.md

**Comment by sulco** [comment] 2018-05-23 14:29
Stumbled upon the same issue. Reproduction steps: (CLI 6.0.3)

```
ng new ngrx6demo
cd ngrx6demo
ng add @ngrx/store --module app
```

if works for effects (replace last line with `ng add @ngrx/effects --module app`) though.

**Comment by maxisam** [comment] 2018-06-19 17:18
@sandangel 
>I think you should not use store in your library which will lead to 2 different store object (2 different >?>source of truth) in the user application.

I disagreed. I think you still can use store in a library. Just make it as feature store. I don't think it will cause any issues. I have a library like that running fine.

**Comment by sandangel** [comment] 2018-06-19 20:22
@maxisam sure you can, but that will make the apps consume your library will have to use Ngrx. I think it's better to have a small store implement like this one:
https://github.com/valor-software/ngx-bootstrap/blob/development/src/mini-ngrx/store.class.ts

**Comment by maxisam** [comment] 2018-06-19 20:32
yeah, a library with dependency. I don't think it is a problem. But I think your example is pretty cool too. Just for different targets.

**Comment by brandonroberts** [comment] 2018-06-29 12:59
Closing as resolved

**Closed by brandonroberts** 2018-06-29 12:59 UTC
Labels: Needs Reproduction, Project: Schematics

**Comment by hollygood** [comment] 2019-03-14 19:49
@maxisam hey, do u have the example for using the store in library?

**Comment by maxisam** [comment] 2019-03-15 14:09
@hollygood not in public library. sorry. But it is nothing new, just treat it like a feature store.

**Comment by pedy711** [comment] 2020-03-06 09:56
@maxisam but it is not right for the libraries to have dependency on the main app. it would be great if someone shares how to use store in a library without importing store from the main app

**Comment by maxisam** [comment] 2020-03-06 15:20
> @maxisam but it is not right for the libraries to have dependency on the main app. it would be great if someone shares how to use store in a library without importing store from the main app

Well, don't you think in that case, using ngrx/store is not a good idea? Users need to download ngrx/store just because using this library?  If my library use ngrx/store, I expect users are using it in their main app, otherwise, it doesn't make sense to use my library.

**Comment by pedy711** [comment] 2020-03-08 18:10
> > @maxisam but it is not right for the libraries to have dependency on the main app. it would be great if someone shares how to use store in a library without importing store from the main app
> 
> Well, don't you think in that case, using ngrx/store is not a good idea? Users need to download ngrx/store just because using this library? If my library use ngrx/store, I expect users are using it in their main app, otherwise, it doesn't make sense to use my library.

I want to use just a single source of truth (store) in my main app and also in the library without having my library depend on my main app. The store will be used in both main app and the library, but how to use the store into the library without importing it from the main app module?
