### ISSUE TITLE
@ngrx/component-store: Warning about provideComponentStore in tests

### ISSUE THREAD

**Issue by MerrittMelker** [ngrx/platform#3937] opened 2023-06-29 13:27 UTC
### Which @ngrx/* package(s) are relevant/related to the feature request?

component-store

### Information

The tests for our classes extending ComponentStore all now log the console:

```
 console.warn
    @ngrx/component-store: MyComponentStore has the OnStoreInit lifecycle hook(s) implemented without being provided using the provideComponentStore(CashPaymentStore) function. To resolve this, provide the component store via provideComponentStore(CashPaymentStore)
```

### Describe any alternatives/workarounds you're currently using

I suggest you remove the the console.warn in the checkProviderForHooks method. 

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by MerrittMelker** [comment] 2023-06-29 15:14
we use @ngneat/spectator and the createServiceFactory method (in jest) for our tests

**Comment by markostanimirovic** [comment] 2023-07-19 23:26
Hi @MerrittMelker,

Does `CashPaymentStore` from your codebase has the `ngrxOnStoreInit` method?

- If yes, it needs to be provided by using the `provideComponentStore` function in tests too.
- If `CashPaymentStore` doesn't have the `ngrxOnStoreInit` method, but you see this warning in the console, then you need to provide a reproduction via GitHub repo/StackBlitz playground.

**Comment by schmkr** [comment] 2023-08-02 10:29
Running into this same issue, when using `@ngneat/spectator` for our tests. 

Here's a simplified 

```ts
import { createServiceFactory, SpectatorService } from '@ngneat/spectator/jest';
import { provideComponentStore } from '@ngrx/component-store';
import { SomeComponentStore as ComponentStoreUnderTest } from './some-component.store';

describe(ComponentStoreUnderTest.name, () => {
	let spectator: SpectatorService<ComponentStoreUnderTest>;

	const createService = createServiceFactory({
		service: ComponentStoreUnderTest,
		providers: [provideComponentStore(ComponentStoreUnderTest)],
	});

	beforeEach(() => {
		spectator = createService();
	});

	it('should create', () => {
		expect(spectator.service).toBeInstanceOf(ComponentStoreUnderTest);
	});
});
```

This results in the mentioned warning:

```
console.warn
    @ngrx/component-store: SomeComponentStore has the OnStateInit lifecycle hook(s) implemented without being provided using the provideComponentStore(AccountDetailsStore) function. To resolve this, provide the component store via provideComponentStore(SomeComponentStore)
```

**Comment by MerrittMelker** [comment] 2023-08-07 19:46
The simplest solution we found was to override the prototype:
`MyStore.prototype['checkProviderForHooks'] = () => {};`

**Comment by markostanimirovic** [comment] 2023-08-30 00:00
> 	const createService = createServiceFactory({
>		service: ComponentStoreUnderTest,
>		providers: [provideComponentStore(ComponentStoreUnderTest)],
>	});

I haven't used Spectator before, but providing the ComponentStore twice (`service: CS` and `providers: [provideCS(CS)]`) seems like an issue here.

Anyway, I'm going to close this issue since there is no provided reproduction via GitHub repo/StackBlitz playground. Feel free to reopen it with the provided reproduction if you think that issue exists on the NgRx side.

**Closed by markostanimirovic** 2023-08-30 00:00 UTC
Labels: Needs Reproduction, Project: Component Store
