### ISSUE TITLE
ERROR TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by CHBaker** [ngrx/platform#777] opened 2018-02-01 18:44 UTC
## I'm submitting a...

<pre><code>
[?*] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Regression of Angular 5 update?* I updated all of my npm modules including angular 4 --> 5, and this error occured.
`ERROR TypeError: Cannot read property 'state' of undefined` in all of my components
Values are not rendered in view

## Expected behavior:

No errors in console
Values from NgRx store are selected properly and rendered in view

## Minimal reproduction of the problem with instructions:

Have JSON dependencies versions as follows:
```
{
  "name": "link-warden",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.3",
    "@angular/common": "^5.2.3",
    "@angular/compiler": "^5.2.3",
    "@angular/core": "^5.2.3",
    "@angular/forms": "^5.2.3",
    "@angular/http": "^5.2.3",
    "@angular/platform-browser": "^5.2.3",
    "@angular/platform-browser-dynamic": "^5.2.3",
    "@angular/platform-server": "^5.2.3",
    "@angular/router": "^5.2.3",
    "@ngrx/effects": "^5.0.1",
    "@ngrx/store": "^5.0.0",
    "@ngrx/store-devtools": "^5.0.1",
    "angular-cesium": "0.0.48",
    "angular-font-awesome": "^3.1.2",
    "angular2-click-outside": "^0.1.0",
    "angular2-notifications": "^0.9.7",
    "bootstrap": "^4.0.0-alpha.6",
    "cesium": "^1.41.0",
    "core-js": "^2.5.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "popper.js": "^1.12.9",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.7",
    "@angular/compiler-cli": "^5.2.3",
    "@angular/language-service": "^5.2.3",
    "@types/jasmine": "2.8.6",
    "@types/jquery": "^3.3.0",
    "@types/node": "^9.4.0",
    "codelyzer": "~4.1.0",
    "jasmine-core": "~2.9.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.1",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "^2.4.2"
  }
}
```

line of code that is retrieving store values from error:
points to html form:
```
<input
      type="text"
      class="form-control"
      formControlName="start"
      [value]='(dhcpStatus$ | async)?.dhcp.poolstart'
>
```
ts
```
this.dhcpStatus$ = this.store.select(selectNetworkDhcp);

this.networkService.getDhcp()
      .subscribe(
                (dhcp: DhcpState) => {
                    this.store.dispatch(new LoadDhcpSuccessAction(dhcp));
                    this.initializeDhcpForm();
                    this.initializeHostEntryForm();
                },
                (error) => {
                    console.log(error);
                }
);
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:

node: 9.2.0
npm 5.5.1
ngrx: 5.5.0

## Other information:

My original package.json versions, that worked with no errors before the update:
```
{
  "name": "link-warden",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.4.3",
    "@angular/common": "^4.4.3",
    "@angular/compiler": "^4.4.3",
    "@angular/core": "^4.4.3",
    "@angular/forms": "^4.4.3",
    "@angular/http": "^4.4.3",
    "@angular/platform-browser": "^4.4.3",
    "@angular/platform-browser-dynamic": "^4.4.3",
    "@angular/platform-server": "^4.4.4",
    "@angular/router": "^4.4.1",
    "@ngrx/effects": "^4.1.0",
    "@ngrx/store": "^4.0.3",
    "@ngrx/store-devtools": "^4.0.0",
    "angular-cesium": "0.0.25",
    "angular-font-awesome": "^2.2.0",
    "angular2-click-outside": "^0.1.0",
    "angular2-notifications": "^0.7.8",
    "bootstrap": "^4.0.0-alpha.6",
    "bootstrap-switch": "^3.3.4",
    "cesium": "^1.37.0",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "rxjs": "^5.4.3",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.4",
    "@angular/compiler-cli": "^4.4.4",
    "@angular/language-service": "^4.4.1",
    "@types/jasmine": "2.5.45",
    "@types/jquery": "^3.2.12",
    "@types/node": "^6.0.88",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.4",
    "jasmine-spec-reporter": "~4.1.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.6",
    "tslint": "~5.3.2",
    "typescript": "^2.3.4"
  }
}
```

I am not sure If this is an Angular/typescript issue or an NgRx issue, let jme know If I should post this issue elsewhere, thanks

**Comment by brandonroberts** [comment] 2018-02-02 02:04
Duplicate of #624

**Closed by brandonroberts** 2018-02-02 02:04 UTC
