### ISSUE TITLE
feat(effects): add withLatestFromStore operator

### ISSUE THREAD

**Issue by ngfelixl** [ngrx/platform#2703] opened 2020-09-04 14:50 UTC
## Describe any alternatives/workarounds you're currently using

Hi everyone,
there is a relatively simple feature request in my mind related to effects. In order to include the store in an effect one should use a combination of `withLatestFrom` and `concatMap` as mentioned in the docs. This is such a common task, and I think many people just do `withLatestFrom` because they don't now about the performance problems. Before I knew about it, I just used `withLatestFrom`, and I see it very frequently. Therefore I think it would be nice to provide an additional operator in the effects package like `withLatestFromStore` so that one does not need to do the workaround with `concatMap`.

Before:

```typescript
createEffect(() => this.actions$.pipe(
  ofType(getSelectedBookDetails),
  concatMap(action => of(action).pipe(
    withLatestFrom(this.store.select(getSelectedBookId))
  )),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

After:

```typescript
createEffect(() => this.actions$.pipe(
  ofType(getSelectedBookDetails),
  withLatestFromStore(this.store.select(getSelectedBookId)),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

Or maybe even a direct selection could be possible without having store explicitly injected at all. Like:

```typescript 
createEffect(() => this.actions$.pipe(
  ofType(getSelectedBookDetails),
  select(getSelectedBookId),
  switchMap(([action, selectedBookId]) => this.bookService.getDetails(selectedBookId).pipe(
    map(...),
    catchError(...)
  )
);
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by alex-okrushko** [comment] 2020-09-04 18:27
Interesting.

we are having this discussion here: https://twitter.com/danm_t/status/1301910606975557639

Yeah, I think something like `withLatestFromStore` would be interesting. It should take a `selector` already though, e.g.:

```ts
 withLatestFromStore(getSelectedBookId),
```

**Comment by timdeschryver** [comment] 2020-09-04 18:27
I'm going to close this issue because I think it's a duplicate of #2222 
Can you add your notes to the RFC please, so we keep the discussion in one place?
Thanks!

**Closed by timdeschryver** 2020-09-04 18:27 UTC
