### ISSUE TITLE
Create operator that implements suggestion found in ngrx/effects docs

### ISSUE THREAD

**Issue by david-shortman** [ngrx/platform#2757] opened 2020-10-22 04:51 UTC
## Describe any alternatives/workarounds you're currently using

- N/A

## Other information:

- The [NgRx Effects docs](https://ngrx.io/guide/effects) has the following suggestion for using `withLatestFrom` in effects:

> Note: For performance reasons, use a flattening operator in combination with withLatestFrom to prevent the selector from firing until the correct action is dispatched.

Adding an operator like the following would increase adoption of this performance-enhancing suggestion:

```typescript
 this.actions$.pipe(
        ofType(CollectionApiActions.addBookSuccess),
        concatWithLatestFrom(() => [this.store.select(fromBooks.getCollectionBookIds])),
        tap(([action, bookCollection]) => ...
    );
```

## If accepted, I would be willing to submit a PR for this feature

- [x] Yes (Assistance is provided if you need help submitting a pull request)
- [ ] No

**Comment by timdeschryver** [comment] 2020-10-22 05:08
Hi, thanks for creating this issue - I do think it's a duplicate of #2222 so I'm closing this one.

**Closed by timdeschryver** 2020-10-22 05:08 UTC
Labels: Project: Effects

**Comment by david-shortman** [comment] 2020-10-22 05:47
@timdeschryver #2222 does not appear to be a duplicate.

The reason the NgRx docs suggest using a flattening operator is to delay the evaluation of `this.store.select` in the `withLatestFrom` operator. It does not have anything to do with the behavior of `ofType`.

**Comment by david-shortman** [comment] 2020-10-22 06:00
@timdeschryver After digging into #2222, I'm don't think my proposal is a duplicate.

As the NgRx effects docs' suggestion says, the problem with using `withLatestFrom` is that when the operator is evaluated, `this.store.select` is also evaluated, which means the input selector is evaluated before it is necessary.

That is not a problem with the `ofType` operator, which is what #2222 appears to be about. Rather, it's just a problem with how operators work, or rather even how function evaluation works in Typescript.

If we don't want to waste CPU cycles on evaluating the selector, the we need to delay evaluation somehow. This is applicable for usage of `withLatestFrom` with `store.select` even when it comes after other filtering operators besides `ofType`.

My suggestion is to create an operator which streamlines delaying that evaluation.

**Comment by david-shortman** [comment] 2020-10-22 06:03
Actually, it looks like #2222 is perhaps just named incorrectly. The issue several commenters are describing appears to be the behavior of the selector executing, not the operators following the `withLatestFrom`. That is definitely not an issue with `ofType`.
