### ISSUE TITLE
Home page gets bugged

### ISSUE THREAD

**Issue by mak092001** [ngrx/platform#3421] opened 2022-05-17 07:04 UTC
### Minimal reproduction of the bug/regression with instructions

![Screenshot (14)](https://user-images.githubusercontent.com/85216108/168742648-4ecdf953-606d-42f7-b7bf-d273276731a7.png)
)

### Minimal reproduction of the bug/regression with instructions

By default it came 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Browser : Microsoft edge
os : windows

### Other information

![Screenshot (15)](https://user-images.githubusercontent.com/85216108/168743070-9932c8d6-65b5-401d-8d41-638d00f28115.png)
As I debug this issue so got to know that because of "<mat-sidebar-content>" this issue came where my I am pointing at image above, so its css has margin-left of 267px but when the issue was seen its margin-left was 207px

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

**Comment by mak092001** [comment] 2022-05-20 03:12
@timdeschryver sure i'll do

**Comment by timdeschryver** [comment] 2022-07-26 17:30
Closing this for now because I can't reproduce it on various devices.
If this is still happening, feel free to open a PR with a fix.

**Closed by timdeschryver** 2022-07-26 17:30 UTC
Labels: bug, Comp: Docs, Accepting PRs, community watch
