### ISSUE TITLE
Is not assignable

### ISSUE THREAD

**Issue by juniur** [ngrx/platform#815] opened 2018-02-14 12:09 UTC
dear guys,
please, can you verify what are  these messages?

Inside ngrx/platform/example-app/app/reducers/index.ts
export const reducers: ActionReducerMap<State> = {
  layout: fromLayout.reducer,
  router: fromRouter.routerReducer,
};
error message:
Initializer type {layout: (state: State, action: LayoutActions) => State} is not assignable to variable type ActionReducerMap<State>

Initializer type {layout: (state: State, action: LayoutActions) => State, router: <T>(state: RouterReducerState<T>, action: RouterAction<any, T>) => RouterReducerState<T>} is not assignable to variable type ActionReducerMap<State>

export const metaReducers: MetaReducer<State>[] = !environment.production
  ? [logger, storeFreeze]
  : [];
error message:
Initializer type (((reducer: ActionReducer<State>) => ActionReducer<State>) | <T, V extends Action>(reducer: ActionReducer<T, V extends Action>) => ActionReducer<T, V extends Action>)[] | any[] is not assignable to variable type MetaReducer<State>[]

thank you.

**Comment by sandangel** [comment] 2018-02-15 11:40
see #709

**Comment by juniur** [comment] 2018-02-16 14:01
thanks, but it doesn't solve the issue.

**Comment by brandonroberts** [comment] 2018-02-16 19:45
Closing as duplicate of #709

**Closed by brandonroberts** 2018-02-16 19:45 UTC
