### ISSUE TITLE
Cannot start example app

### ISSUE THREAD

**Issue by harishajdarevic** [ngrx/platform#320] opened 2017-08-24 09:11 UTC
## I'm submitting a problem with starting example application

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Not able to start example app

## Expected behavior:
I run following commands:

```
# clone the repo
git clone https://github.com/ngrx/platform.git

# Use npm or yarn to install the dependencies:
npm install

# start the server
npm run build && npm run cli -- serve
```

And I'm getting error:

```
> > @ngrx/platform@4.0.0 example:start /home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer
> > npm run build && npm run cli -- serve
> 
> 
> > @ngrx/platform@4.0.0 build /home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer
> > ts-node ./build/index.ts
> 
> ✔ Removing "./dist" Folder
> ✔ Compiling packages with NGC
> ✔ Bundling FESMs
> ✔ Down-leveling FESMs to ES5
> ✔ Creating UMD Bundles
> ✔ Renaming package entry files
> ✔ Cleaning TypeScript files
> ✔ Removing remaining sourcemap files
> ✔ Copying type definition files
> ✖ Minifying UMD bundles
> { Error: Command failed: /home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer/node_modules/.bin/uglifyjs -c -m --screw-ie8 --comments -o ./dist/store-devtools/bundles/store-devtools.umd.min.js --source-map ./dist/store-devtools/bundles/store-devtools.umd.min.js.map --source-map-include-sources ./dist/store-devtools/bundles/store-devtools.umd.js --in-source-map ./dist/store-devtools/bundles/store-devtools.umd.js.map
> INFO: Using file from the input source map: store-devtools.umd.js
> (node:21385) DeprecationWarning: util.error is deprecated. Use console.error instead.
> /home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer/node_modules/directory-encoder/node_modules/uglify-js/bin/uglifyjs:226
>             sys.error("ERROR: can't read file: " + filename);
>                                                    ^
> 
> ReferenceError: filename is not defined
>     at ReadFileContext.callback (/home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer/node_modules/directory-encoder/node_modules/uglify-js/bin/uglifyjs:226:52)
>     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
> 
>     at ChildProcess.exithandler (child_process.js:206:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
>   killed: false,
>   code: 1,
>   signal: null,
>   cmd: '/home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer/node_modules/.bin/uglifyjs -c -m --screw-ie8 --comments -o ./dist/store-devtools/bundles/store-devtools.umd.min.js --source-map ./dist/store-devtools/bundles/store-devtools.umd.min.js.map --source-map-include-sources ./dist/store-devtools/bundles/store-devtools.umd.js --in-source-map ./dist/store-devtools/bundles/store-devtools.umd.js.map' }
> 
> npm ERR! Linux 4.4.0-92-generic
> npm ERR! argv "/home/haris/.nvm/versions/node/v6.9.4/bin/node" "/home/haris/.nvm/versions/node/v6.9.4/bin/npm" "run" "build"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! @ngrx/platform@4.0.0 build: `ts-node ./build/index.ts`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @ngrx/platform@4.0.0 build script 'ts-node ./build/index.ts'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the @ngrx/platform package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     ts-node ./build/index.ts
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs @ngrx/platform
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls @ngrx/platform
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer/npm-debug.log
> 
> npm ERR! Linux 4.4.0-92-generic
> npm ERR! argv "/home/haris/.nvm/versions/node/v6.9.4/bin/node" "/home/haris/.nvm/versions/node/v6.9.4/lib/node_modules/npm/bin/npm-cli.js" "run" "example:start"
> npm ERR! node v6.9.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! @ngrx/platform@4.0.0 example:start: `npm run build && npm run cli -- serve`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @ngrx/platform@4.0.0 example:start script 'npm run build && npm run cli -- serve'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the @ngrx/platform package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run build && npm run cli -- serve
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs @ngrx/platform
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls @ngrx/platform
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/haris/development/walter/bimeyenx/ngrx-4x-v-primjer/npm-debug.log
> 
> Process finished with exit code 1
```

## Version of affected browser(s),operating system(s), npm, node and ngrx:
OS: Linux Ubuntu 16.04 ( 64 bit )
npm: 3.10.10
node: 6.9.5
ngrx: 4.x.x

**Comment by dominhdung** [comment] 2017-08-24 10:44
I got the error too.

**Comment by moravcik** [comment] 2017-08-24 11:22
I had the same problem, upgrading to yarn v0.28.4 helped.

**Comment by brandonroberts** [comment] 2017-08-24 15:31
Duplicate of #123

**Closed by brandonroberts** 2017-08-24 15:31 UTC

**Comment by dominhdung** [comment] 2017-08-25 03:38
Solved this problem by installing Yarn version 0.28 and set up a fresh repository.

Find Yarn version 0.28 here  https://github.com/yarnpkg/yarn/releases
