### ISSUE TITLE
@ngrx/component: Add ability to pass "non-Observable" values 

### ISSUE THREAD

**Issue by markostanimirovic** [ngrx/platform#3345] opened 2022-03-09 17:42 UTC
It can be useful to have aliases in the template for nested properties. For example, the `LetDirective` could be used as follows:

```html
<span *ngrxLet="form.controls.name.valid as isValid">{{ isValid }}</span>
```

The input type will be `ObservableInput<T> | T` which will also solve the typing issues mentioned in #3344.

**Additional change to consider:** Treat arrays as "non-Observable" values.

Current behavior:

```ts
@Component({
  selector: 'ngrx-array',
  template: `
    <!-- the value of `a` is equal to the last element of array -->
    <p *ngrxLet="array as a">{{ a }}</p>
  `,
})
export class ArrayComponent {
  array = [1, 2, 3, 4, 5];
}
```

Behavior with proposed change:

```ts
@Component({
  selector: 'ngrx-array',
  template: `
    <!-- the value of `a` is equal to array -->
    <p *ngrxLet="array as a">{{ a }}</p>
  `,
})
export class ArrayComponent {
  array = [1, 2, 3, 4, 5];
}
```

**Comment by brandonroberts** [comment] 2022-05-29 19:09
Closed via https://github.com/ngrx/platform/pull/3440

**Closed by brandonroberts** 2022-05-29 19:09 UTC
Labels: Project: Component, 14.x

**Comment by DibyodyutiMondal** [comment] 2022-07-30 08:54
```html
 <ng-container *ngrxLet="[timeSlice.mergeCells.month(period)] as months;">
   <div *ngFor="let monthCell of months; let i = index" [class.month-end]="i !== months.length - 1">
     {{monthCell.data.dt.monthShort}}, {{monthCell.data.dt.year}}
   </div>
</ng-container>
```

The function `timeSlice.mergeCells.month(period)` returns an array of objects that I want to iterate over. 
But I also need the full array, because I need the array length to get the array's last item's index and use that to apply a certain class if it is the last item.

However, if I do not wrap the call in square braces and make an artificial array, then I cannot use `ngFor` inside the `ngrxLet` directive, because `ngrxLet` unwraps the array for me. 

I assume this is intended behaviour, and the workaround is very very simple, but it would be nice to do this via an option to the direction, so that it becomes obvious to others what I'm trying to do.
