### ISSUE TITLE
DevTools: Test-View not visible

### ISSUE THREAD

**Issue by negue** [ngrx/platform#1868] opened 2019-05-17 12:49 UTC
## Minimal reproduction of the bug/regression with instructions:
1. Add `StoreDevtoolsModule` to your Module
```ts

      StoreDevtoolsModule.instrument({
         logOnly: true,
         // also tested with features: { test: true }
      }),
```
2. Open DevTools in the Browser
3. No Test-View available

Go to: https://ngrx-seed.stackblitz.io/ and open your DevTools and see that there is no `Test`-View visible

But, if you open the edit view of stackblitz (https://stackblitz.com/edit/ngrx-seed?file=src%2Fapp%2Fapp.module.ts) you can see that Stackblitz's own redux? does add the `Test`-View 😅 

## Expected behavior:

Have a `Test`-View like its visible on other sites.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NGRX 7.4.0
Angular 7.2.13
Browsers: Chrome and Firefox 

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by adrianfaciu** [comment] 2019-05-17 16:56
Cannot reproduce this. If I go to the [StackBlitz example](https://ngrx-seed.stackblitz.io/), the instance is visible in DevTools. Both router and counter properties are present.

**Comment by negue** [comment] 2019-05-17 17:23
DevTools Views

with NgRx Seed:
![image](https://user-images.githubusercontent.com/842273/57944954-d3037900-78d8-11e9-8988-8cf8047b9efd.png)

with Stackblitz itself:
![image](https://user-images.githubusercontent.com/842273/57945042-16f67e00-78d9-11e9-9f4b-5a6a658aead2.png)


As you see `Trace` and `Test` are missing

**Comment by adrianfaciu** [comment] 2019-05-17 17:40
Yeah, there is something here. If I open dev tools and have a look they are there:

![Screenshot 2019-05-17 at 20 34 34](https://user-images.githubusercontent.com/2067101/57945751-5a55ea00-78e3-11e9-8a55-b291166a1c7c.png)

However, if I refresh the page they dissapear. Closing and opening dev tools again will make them show up.

**Comment by negue** [comment] 2019-05-17 18:47
I don't get any on the NgRx Seed, using Vivaldi / Chrome on both Mac and Windows. 🙁 

Both browser have the latest version of the dev tools installed

**Comment by timdeschryver** [comment] 2019-05-18 19:34
Weird that you see this @adrianfaciu, it shouldn't show up AFAIK.

To have these features available we must identify ourselves as a redux app, see https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/logOnly.js#L9 for ref.

For us, this would mean adding a `type` property at https://github.com/ngrx/platform/blob/55818268bac6048fbb972dacbf41c0bedd3da809/modules/store-devtools/src/extension.ts#L241. I tried it locally and the redux features become visible but sadly enough, will do nothing.

![image](https://user-images.githubusercontent.com/28659384/57974177-80978a80-79b4-11e9-8a8c-9773400553cd.png)

**Comment by adrianfaciu** [comment] 2019-05-20 12:16
Hmm, that is weird.
If no one else is working on it, I can pick it up next and try to sort it out.

**Comment by timdeschryver** [comment] 2019-05-21 18:17
Yes, that's fine by me Adrian thanks!

**Comment by dummdidumm** [comment] 2019-05-29 12:10
You will not be able to change this, I ran into this problem as well, and it's basically a bug in the redux devtools https://github.com/zalmoxisus/remotedev-app/issues/40

**Comment by timdeschryver** [comment] 2019-05-29 16:56
@dummdidumm We can make it a redux app, https://github.com/ngrx/platform/issues/1868#issuecomment-493701654 

But then you're getting some other problems 😂

**Comment by adrianfaciu** [comment] 2019-05-30 08:38
Sorry for the delay, I traveled a lot and did not have time. I'll pick this up in the weekend and see what can be done.

**Comment by alex-vg** [comment] 2020-03-19 13:41
![ngrx race](https://user-images.githubusercontent.com/22611767/77073378-7b99d200-69ef-11ea-9bfe-ef90ae20260e.png)
A little update here, I just tried setting `trace=true and type='redux'` and got some traces. Not enough to see the origin but somewhat useful.

**Comment by montogeek** [comment] 2020-07-10 09:24
@alex-vg How did you activate Trace tab?

**Comment by minijus** [comment] 2021-05-06 12:41
While there is still no support for traces in @ngrx/store-devtools, one can add a breakpoint on dispatch method to have some traceability.

![image](https://user-images.githubusercontent.com/3633549/117299718-875d8780-ae81-11eb-8f12-07a1211cafd7.png)

**Closed** 2021-05-15 19:51 UTC
Labels: Accepting PRs, Project: Router Store, community watch, enhancement

**Comment by Rybadour** [comment] 2021-09-07 18:21
@brandonroberts 

Why was this closed? I don't see any resolutions to the problem and as of the 12.4.0 I still can't access the trace tab.

**Comment by alex-vg** [comment] 2021-09-14 20:29
@brandonroberts
Is there a fix for this issue coming?
Seeing such an important feature closed without a resolution seems odd.

**Comment by thompsonap09** [comment] 2022-01-14 17:26
Has anybody figured out how to handle this? It looks like @adrianfaciu was working on it at one point and @alex-vg  seems to have figured out how to at least make it work a bit
