### ISSUE TITLE
is it possible to use @ngrx/store@6.1.2 with angular 7 ?

### ISSUE THREAD

**Issue by hocine15** [ngrx/platform#1401] opened 2018-11-04 01:50 UTC
Hi,

I've tried to upgrade my application to angular 7, and then I keep getting this message:

npm WARN @ngrx/store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.

so my question is can I use @ngrx/store@6.1.2 with an angular 7 application ?

if not is there any workarround for this ?

or have I to use lower angular version at this time ?

do we have to wait for ngrx store 7 for use with angular 7 ?

Thanks.

**Comment by brandonroberts** [comment] 2018-11-04 01:55
Duplicate of https://github.com/ngrx/platform/issues/1397

**Closed by brandonroberts** 2018-11-04 01:55 UTC
