### ISSUE TITLE
StoreDevtools: window postMessage, object Position cannot be cloned

### ISSUE THREAD

**Issue by montella1507** [ngrx/platform#825] opened 2018-02-16 08:38 UTC
## I'm submitting a...
[x ] Bug report

## What is the current behavior?
Just migrated to the newest typescript and we got new error from StoreDevTools.
"window postMessage, object Position cannot be cloned"

**Comment by montella1507** [comment] 2018-02-16 08:57
Fixed. But i would let open this issue, because it is interesting problem. Maybe it relates to some problem..

If i create an observable from window.geolocation.getPosition() and pass Position object from the callback directly to observer. it will crash in navigation in StoreDevTools.

However. if i map that position to my own new object, it works..

`
ERROR in StoreDevTools
return Observable.create(obs =>  {
   window...getPosition((pos)=> {
    obs.next(pos);
    obs.complete();
   });
});

OK
return Observable.create(obs =>  {
   window...getPosition((pos)=> {
    obs.next({
    coords: {
       ...
    }
});
    obs.complete();
   });
});
`

it looks like  StoreDevTools is trying to copy the object when it is already freed:? 

Feel free to close the issue

**Comment by warapitiya** [comment] 2018-02-16 09:25
What is the fix here? I'm getting an error like this too.

**Comment by montella1507** [comment] 2018-02-16 09:32
WELL... do not use Position object from geolocation callback directly in your code.. Just copy Longtitude, lattitude values to new object. 

`obs.next({
coords: {
   long : original.coords.long,
   lat : original.coords.lat,
}`

BTW-... this wasnt the only one problem we had.. We had to remove ALL "Position" type in our code, else we got "Position is undefined" error in runtime - lol..

I think there may be problem in Typescript lib.dom.ts where are Position 2times: as a interface and as a value.

**Comment by warapitiya** [comment] 2018-02-16 09:53
ok. looks like this is not the same issue for me! But when i disable the `Redux extension` everything works normally.

**Below is the error message I get:**
```
ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Window': function DashboardComponent(title, activatedRoute, dashboardApiService, userService, rootStore, store, route, m...<omitted>... } could not be cloned.
```

**Comment by montella1507** [comment] 2018-02-16 11:20
Well.. this looks littlebit like your own mistake, are you pushiung to observer a component?

**Comment by Overdozed** [comment] 2018-02-16 19:11
same issue if redux extension is on after updating from
"@ngrx/effects": "^5.0.1",
   "@ngrx/store": "^5.0.0",
    "@ngrx/store-devtools": "^5.0.1",

to 5.1.0

**Comment by warapitiya** [comment] 2018-02-17 05:38
@Overdozed same thing happened to me. but after execute

```sh
$ yarn info @ngrx/effects
```
It's not there at all. So I roll back to version 5.0.0. Now it works.

**Comment by warapitiya** [comment] 2018-02-18 06:24
@Overdozed any fix?

**Comment by brandonroberts** [comment] 2018-02-18 21:28
Can someone post a reproduction?

**Comment by warapitiya** [comment] 2018-02-19 08:13
@brandonroberts for now I will attach the proper error massage.

<img width="1440" alt="screen shot 2018-02-19 at 1 39 04 pm" src="https://user-images.githubusercontent.com/6380518/36367867-9e8bfc64-157a-11e8-9672-7aeedf34e0b1.png">

**Comment by albohlabs** [comment] 2018-02-20 15:14
The structured clone algorithm [1] which is used by `window.postMessage` [2] is not able to clone  function objects. 
In my case i have a proxy object in the action payload. 

The error is ease to reproduce by the following:
```javascript
const a = {
  abc () {}
};
window.postMessage(a, '*')
``` 
[1] https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm
[2] https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by albohlabs** [comment] 2018-02-20 15:32
In the redux-devtools-extension it looks like the payload is stringify before submitted. [1]

[1] https://github.com/zalmoxisus/redux-devtools-extension/blob/b6ef19bd2e722de511165e758a09c1c85e31532e/src/app/api/index.js#L230

**Comment by albohlabs** [comment] 2018-02-20 16:06
Atm i can't reproduce it with on stackblitz. 
But in my case the `devtoolsExtension.send` method is called with a function object: `this.devtoolsExtension.send(null, {abc(){}}, this.config, this.instanceId);`

**Comment by brandonroberts** [comment] 2018-02-20 18:47
There are two things contributing to this issue. Before https://github.com/ngrx/platform/pull/790 landed, the serialize option was set to false, handling circular references (such as those provided if you dispatch an action with the `ActivatedRoute`. The devtools performance is much better as a result, but now things like the `ActivatedRoute` (which is not serializable) gets mangled when trying to send it to the devtools

My recommendation is that if you're dispatching actions with the `ActivatedRoute` or some non-serializable entity, use the [`actionSanitizer` and `stateSanitizer`](http://extension.remotedev.io/docs/API/Arguments.html#actionsanitizer--statesanitizer) options introduced in 5.x to replace the `ActivatedRoute` in the payload with arbitrary placeholder text.

**Comment by warapitiya** [comment] 2018-02-20 19:38
@brandonroberts could u please share a possible usage code with `ngrx`. I'm bit confused.

**Comment by warapitiya** [comment] 2018-02-21 17:24
@brandonroberts after few hours, I think I figured it out! works like charm 👍

**Comment by brandonroberts** [comment] 2018-02-21 21:20
@warapitiya cool. Will you share what you came up with? Would be good to reference in this issue and something we could look at adding to the docs.

**Comment by warapitiya** [comment] 2018-02-22 06:01
I just add `actionSanitizer` to `instrument`

```js
StoreDevtoolsModule.instrument({
      maxAge: 25, //  Retains last 25 states
      actionSanitizer: (action: { type: string; payload?: any }, id: number): Action => action.type === '[Router] Go' && action.payload ?
        {...action, payload: '<<LONG_BLOB>>'} : action
    }),
```

**Comment by wesselvdv** [comment] 2018-02-23 16:24
I actually went with a similar, but smaller solution since it wasn't entirely clear for me which action was causing the issue:

```typescript
StoreDevtoolsModule.instrument({
  maxAge: 25,
  actionSanitizer: action => JSON.parse(JSON.stringify(action))
})
```

Performance might be less when an action contains a humongous amount of nested or recursive references, but I haven't noticed any issues yet.

**Comment by brandonroberts** [comment] 2018-02-23 18:26
@wesselvdv cool. I know the devtools extension uses https://github.com/kolodny/jsan underneath for serialization that supports circular references and such.

**Comment by warapitiya** [comment] 2018-02-26 06:00
Anyway, I noticed when serializing there is a significant performance hit.

**Comment by jmannau** [comment] 2018-03-01 03:37
I have been receiving the same error. (Error message below) and have narrowed it down to occurring when the `@ngrx/store/update-reducers` action is dispatched. The error occurs on downstream of https://github.com/ngrx/platform/blob/a7de2a694f22aac44cc22861094c421dd960d027/modules/store-devtools/src/extension.ts#L94

Interestingly if I sanitise all actions to a simple object with only the type attribute, the error doesn't occur. eg: 

```
const ActionSanitizer = (action: Action) => {
  return { type: action.type };
};
```

It is occurring when a lazily-loaded redux store is injected.

**Error Message**
```
ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Window': function () {
            if (callback) {
                callback();
            }
        } could not be cloned.
Error: Failed to execute 'postMessage' on 'Window': function () {
            if (callback) {
                callback();
            }
        } could not be cloned.
    at post (<anonymous>:1:19703)
    at toContentScript (<anonymous>:1:20486)
    at Function.sendMessage [as send] (<anonymous>:1:20741)
    at DevtoolsExtension.notify (store-devtools.es5.js:248)
    at ScanSubscriber.StoreDevtools.applyOperators.state [as accumulator] (store-devtools.es5.js:705)
    at ScanSubscriber._tryNext (scan.js:111)
    at ScanSubscriber._next (scan.js:104)
    at ScanSubscriber.Subscriber.next (Subscriber.js:89)
    at ScanSubscriber.rxjs_Subscriber.Subscriber.next (zone-patch-rxjs.js:165)
    at WithLatestFromSubscriber._next (withLatestFrom.js:115)
    at post (<anonymous>:1:19703)
    at toContentScript (<anonymous>:1:20486)
    at Function.sendMessage [as send] (<anonymous>:1:20741)
    at DevtoolsExtension.notify (store-devtools.es5.js:248)

**Comment by rhalff** [comment] 2018-03-14 21:20
Had a similar error, but after upgrading to 5.2.0 the error is gone, I think this commit fixed it: https://github.com/ngrx/platform/commit/a5dcdb143ca1e75d291bc04338fd3225d793ac7f

**Comment by tmonte** [comment] 2018-03-23 17:24
I'm still getting this error on 5.2.0, exact same problem as @jmannau. Any solutions?

**Comment by jmannau** [comment] 2018-04-10 11:33
@tmonte apologies for the late reply.

I used an ActionSantizer as per https://github.com/ngrx/platform/issues/825#issuecomment-367576543 to remove the action payload that caused the error. In my case, there were 2 actions that had payloads that error on serialisation. One had a `geoposition` object in the payload. The second had a callback function as a property. It took some time to narrow it down to those 2 actions. 

My ActionSanitizer is the following:

```
export function ActionSanitizer(action: Action) {
  const { type, payload } = <any>action;
  switch (action.type) {
    case SEARCH: {
      // This action ontains onComplete callback which cannot be cloned and causes storedectools to error
      return { type, payload };
    }
    case UPDATE_LOCATION: {
      // This action ontains geolocation position object callback which cannot be cloned and causes storedectools to error
      return { type, payload: JSON.stringify(payload) };
    }
  }
  return action;
}
```

**Comment by dotmobo** [comment] 2018-04-12 13:27
Hi guys !
I fixed a similar bug with the following solutions :
- Migration from ngrx 5.1.0 to **5.2.0**
- Use the following **StoreDevtoolsModule** in the app.module.ts : 

```javascript 
StoreDevtoolsModule.instrument({
      maxAge: 10,
      stateSanitizer: (oriState: any, id: number): any => {
        const { router, ...newState } = oriState;
        const { state, ...newRouter } = router || { state: null };
        const { _root, ...newRouterState } = state || { _root: null };
        return {
          ...newState,
          router: {
            ...newRouter,
            state: newRouterState
          }
        };
      }
    })
```
In my case, i removed **_root** from the router state object, because it contained a circular importation !

**Closed** 2018-05-26 18:52 UTC
Labels: Needs Reproduction, Project: Store Devtools
