### ISSUE TITLE
createFeatureSelector type definition is incorrect.

### ISSUE THREAD

**Issue by envil** [ngrx/platform#1201] opened 2018-07-27 04:22 UTC
## Minimal reproduction of the bug/regression with instructions:
From a fresh new Angular project, start integrating the `ngrx/platform` follow the example-app structure.
Error occurred in the `createFeatureSelector` for the layout feature in the `/src/reducer/index.ts`
```
/**
 * Layout Reducers
 */
export const getLayoutState = createFeatureSelector<State, fromLayout.State>(
  'layout'
);
```

Build erred:
> src/app/reducers/index.ts(67,31): error TS2558: Expected 1 type arguments, but got 2.

WebStorm also spotted the error even before the build:
![screen shot 2018-07-27 at 12 06 50 pm](https://user-images.githubusercontent.com/775364/43301082-834cbffa-9195-11e8-816d-8d83c8b8958f.png)

Not sure why the stackblitz example compile, even though it gives the same warning like in WebStorm:
https://stackblitz.com/edit/ngrx-seed-31duws?file=src/app/reducers/index.ts

## Expected behavior:
No errors should have occurred.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 6.1.0
NgRx: 6.0.1
Node: 8

## Other information:
I checked the definition of the `createFeatureSelector` in the `/node_modules/@ngrx/store/src/selector.d.ts`, only this line is defined:

`export declare function createFeatureSelector<T>(featureName: string): MemoizedSelector<object, T>;`

Looks like the definition is not up to date with the code:
```
export function createFeatureSelector<T>(
  featureName: string
): MemoizedSelector<object, T>;
export function createFeatureSelector<T, V>(
  featureName: keyof T
): MemoizedSelector<T, V>;
export function createFeatureSelector(
  featureName: any
): MemoizedSelector<any, any> {
  return createSelector(
    (state: any) => state[featureName],
    (featureState: any) => featureState
  );
}
```

If I change the code back to the old way, it worked:
```
export const getLayoutState = createFeatureSelector<fromLayout.State>(
  'layout'
);
```
## I would be willing to submit a PR to fix this issue

[ x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2018-07-27 05:49
Duplicate of #1180.

**Closed by timdeschryver** 2018-07-27 05:49 UTC
