### ISSUE TITLE
Effect creates as many subscriptions as there are number of EffectsModule.forFeature

### ISSUE THREAD

**Issue by sean-snapscan** [ngrx/platform#2880] opened 2021-01-14 07:31 UTC
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/ngrx-seed-xp26qu?file=src/app/app.module.ts

I've been trying to leverage effects for observables other than actions and I think I've hit an issue.

## Current behavior:

An effect as simple as below seems to be triggering 7 times - that is, console logging `test` and `complete` 7 times.
```
public readonly test$ = createEffect(() => of('test').pipe(
  tap((test) => {
    console.log(test);
  }),
  finalize(() => {
    console.log('complete');
  })
), { dispatch: false });
```

The number 7 just so happens to match the amount of modules that include the `EffectsModule.forFeature` module import. 

I've managed to reproduce the issue in the provided stackblitz.

## Expected behavior:

I'd expect the effect to trigger once and complete.

Effects created from the conventional actions observable seem to work as expected and without duplication which is strange.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
"@angular/core": "~10.0.9",
"@ngrx/effects": "~10.0.0",
"@ngrx/store": "~10.0.0",

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by sean-snapscan** [comment] 2021-01-14 11:06
After some digging around in `EffectSources.toActions` I noticed the `exhaustMap` could be part of my issue. If my effect source observable _does not_ complete, it behaves as expected. 

Is this supposed to be a limitation for effects?

Did I miss something in the doc indicating this?

**Comment by derekkite** [comment] 2021-01-15 18:02
An effect is a subscription that emits into the action stream. When you initialize an effect it subscribes to the actions observable. If you subscribe to a subject variant, that doesn't complete unless directed, the subscription is added to the subject subscriber list and receives the emissions. If it is an observable, the subscription runs the observable. Unless you're observable is set up to handle multiple observers, with share or similar, you will get the observable to run each time it is subscribed to.

So you are seeing your observable run 7 times, and complete. 

I believe this is expected behavior.

**Comment by sean-snapscan** [comment] 2021-01-18 06:13
There is one effect:
```
public readonly test$ = createEffect(() => of('test').pipe(
  tap((test) => {
    console.log(test);
  }),
  finalize(() => {
    console.log('complete');
  })
), { dispatch: false });
```
This logs 7 times.  I do not think this is intended.

**Comment by timdeschryver** [comment] 2021-01-30 14:09
Effects should be live the entire span of the application. 
The `exhaustMap` is there to only subscribe once to the source, in case when the same effect is registered multiple times.

The added example in this issue completes the stream and due to this it is invoked multiple times.
I also believe that this is the desired behavior, so I'm going to close this.

> It would be great to use effects for observables other than actions though

It can be, and it's often useful to do so. 
We've added some examples in our example app, and I've written about some cases in [Start using @ngrx/effects for this](https://timdeschryver.dev/blog/start-using-ngrx-effects-for-this).

**Closed by timdeschryver** 2021-01-30 14:09 UTC
Labels: Project: Effects

**Comment by sean-snapscan** [comment] 2021-02-01 06:56
> Or were effects simply not designed to use any source observable other than Actions that never complete?

> The added example in this issue completes the stream and due to this it is invoked multiple times.
> I also believe that this is the desired behavior, so I'm going to close this.

Thanks for the response.

So for posterity, the take away is that effects are not meant for observables that complete.
