### ISSUE TITLE
Build Succeeds, Serve fails

### ISSUE THREAD

**Issue by beauxjames** [ngrx/platform#402] opened 2017-09-18 18:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
Per basic instructions. The package is cloned, packages installed, built and served. On serve, node emits many warnings followed by a collection of errors (attached below)

## Expected behavior:
Application would be served up successfully and able to run on http://localhost:4200

## Minimal reproduction of the problem with instructions:

: git clone https://github.com/ngrx/platform.git
: cd platform
: npm install
: npm run build && npm run cli -- serve

## Version of affected browser(s),operating system(s), npm, node and ngrx:
macOS Sierra v 10.12.3
iTerm
@angular/cli v 1.4.2
node v 7.6.0
npm v 4.1.2

## Other information:
Log attached :: 
[localErrors.txt](https://github.com/ngrx/platform/files/1311769/localErrors.txt)

**Comment by brandonroberts** [comment] 2017-09-19 12:44
Seems like a duplicate of #123. Use yarn to install dependencies instead

**Closed by brandonroberts** 2017-09-19 12:44 UTC
