### ISSUE TITLE
where is go, replace, search, show, back, forward in @ngrx/router-store on v4?

### ISSUE THREAD

**Issue by junimohano** [ngrx/platform#122] opened 2017-07-19 23:03 UTC
Where is the document for @ngrx/router-store for v4?
MIGRATION.md has no manuals..

import { go, replace, search, show, back, forward } from '@ngrx/router-store';
this one was working at v1 not v4.

I can not find any documentation anywhere.

**Comment by brandonroberts** [comment] 2017-07-19 23:04
Duplicate of #107

**Closed by brandonroberts** 2017-07-19 23:04 UTC

**Comment by mikedanylov** [comment] 2017-07-20 15:23
At least go, replace, back and forward can be easily replaced by Angular Router and `Location` 
https://angular.io/api/common/Location
