### ISSUE TITLE
Tests fail when npm or latest Yarn is used to install dependencies

### ISSUE THREAD

**Issue by karptonite** [ngrx/platform#123] opened 2017-07-19 23:12 UTC
I did a clean install of ngrx/platform, and installed according to the contributing guide:
https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md
`npm install`
then ran `npm test`, and got 4 failures.

If I installed instead with yarn, the tests pass.
The tests that failed were:
1) integration spec should work
2) integration spec should support rolling back if navigation gets canceled
3) integration spec should support rolling back if navigation errors
4) integration spec should call navigateByUrl when resetting state of the routerReducer

I assume that the yarn installed correctly, but either the contributing guide should be updated to use  yarn, or the package should be fixed so that the right stuff installs with npm, or both.

**Comment by MikeRyanDev** [comment] 2017-07-19 23:32
This also happens with the latest versions of Yarn.

**Comment by linkvt** [comment] 2017-08-01 20:34
@MikeRyanDev I can't confirm that it's not working with yarn v0.28.4 - it works fine for me. I can confirm it isn't working with npm.

The reason is, that there are two lock files - `yarn.lock` and `package-lock.json` which are different from each other. `package-lock.json` is more than a week older - so it isn't up-to-date.
I think you should decide which lock file you want to use, because there will always be conflicts.

IMO you should choose yarn, because ...
- not everybody is using the latest node/npm version, so some/many will ignore the `package-lock.json`
- you use yarn already in your build and CI files
- yarn can be called through npm scripts (if it's the case, that it can't be installed globally)
- the `yarn-lock.json` works fine (at least for me)
The `package-lock.json` should be deleted and ignored until npm 5 is the default or yarn supports the `package-lock.json`

**Comment by tdeschryver** [comment] 2017-09-04 20:04
Maybe totally unrelated but I had the same problems before. 
After I've played around with it for a bit, I've removed both the `package-lock.json` and  `yarn.lock` files, deleted my `node_modules` an did a clean install but without success.
When comparing the lock files I've noticed an angular router upgrade (4.2.6 -> 4.3.6) and I think the events `GuardsCheck` and `Resolve` were added.

If you want I can open a PR for this.
The `xit` test also works without any problem.

**Comment by phillipzada** [comment] 2017-10-11 04:19
Hi @karptonite,

Is this still a relevant problem, just tried a fresh install, seemed work fine.

**Config**
**Node:** v6.9.5
**Yarn:** 1.0.2

**Commands Used**
```
git clone https://github.com/ngrx/platform.git
cd platform\
yarn
yarn test
```

**Comment by brandonroberts** [comment] 2017-10-19 14:38
Closing as resolved since the latest version of yarn is working.

**Closed by brandonroberts** 2017-10-19 14:38 UTC
Labels: help wanted
