### ISSUE TITLE
Looks like selector projector is run more number of times comparing to reselect

### ISSUE THREAD

**Issue by yzhe554** [ngrx/platform#3134] opened 2021-09-02 06:09 UTC
## Minimal reproduction of the bug/regression with instructions:
I forked a project on stackblitz and played it with ngrx/createSelector and reselect/createSelector but I am getting a different result.
https://stackblitz.com/edit/ngrx-selector-effeciency-zrxpxh?file=src%2Fapp%2Fmy-counters%2Fcounter.reducer.ts
projectors in ngrx/createSelector is executed more times comparing with reselect/createSelector.

Please comment out the codes implemented with ngrxCreateSelector and use the codes with createSelector(reselect) to see a difference.

## Expected behavior:
both createSelector should probably give the same result.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

    "@ngrx/store": "^12.4.0",
    "reselect": "^4.0.0",

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2021-09-02 09:14
Seems like a duplicate of https://github.com/ngrx/platform/issues/2862
If that's not the case, feel free to re-open.

**Closed by timdeschryver** 2021-09-02 09:14 UTC

**Comment by yzhe554** [comment] 2021-09-02 16:03
@timdeschryver the key point is reselect won’t run multiple calls. Should we consider the reason behind the implementation details? https://github.com/reduxjs/reselect/blob/master/src/index.js

**Comment by yzhe554** [comment] 2021-09-02 23:07
@timdeschryver I just updated the implementation to remove props but it still run more calls comparing with `reselect`

**Comment by timdeschryver** [comment] 2021-09-04 10:13
I'm going to keep this issue closed because it's related to #3110
