### ISSUE TITLE
StoreRouterConfig interface does not match documentation

### ISSUE THREAD

**Issue by alaboudi** [ngrx/platform#1398] opened 2018-11-02 18:54 UTC
## Description
There is a discrepancy between the type interface for the StoreRouterConfig in the ngrx/router-store code base and the router-store [documentation](https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#configuration-options).  I think this is more of a bug than a documentation error. Currently, only the stateKey field is defined in the StoreRouterConfig interface and not the remaining properties stated in the documentation.

## Minimal reproduction of the bug/regression with instructions:
```
import { StoreRouterConfig, RouterStateSerializer } from '@ngrx/router-store'
export const config: StoreRouterConfig = {
  serializer: RouterStateSerializer
}
```
This throws me an error stating that serializer does not exist in StoreRouterConfig.

## Reproduction
https://stackblitz.com/edit/ngrx-seed-ynjjr9

## Expected behavior:
Same interface as documentation

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NGRX 6, Angular 6, Node 10.9.0, Mac

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2018-11-02 21:36
Duplicate of #1390

**Closed by timdeschryver** 2018-11-02 21:36 UTC
