### ISSUE TITLE
NgrxLet: Structural directive clears view early, leading to issues with router transitions

### ISSUE THREAD

**Issue by Kamshak** [ngrx/platform#2890] opened 2021-01-20 17:05 UTC
When using the *ngrxLet structural directive in an app, the view is cleared as soon as ngOnDestroy() is called. This causes an issue with animations: the view that is animated out changes as all ngrxLet templates get cleared.

To illustrate the problem see this StackBlitz, compare the ngIf behavior with ngrxLet: https://stackblitz.com/edit/ngrx-bug-ngrxlet

I believe the problem could be fixed by removing this line: https://github.com/ngrx/platform/blob/c3ac25242717c6f4cbdb9287f9b3a83cd5dd51e1/modules/component/src/let/let.directive.ts#L178

The viewContainerRef should automatically be cleared by Angular when it is destroyed. Happy to make a PR to remove this line unless there are specific reasons why it needs to exist that I haven't considered.

CC @BioPhoton @markostanimirovic

**Comment by markostanimirovic** [comment] 2021-01-20 21:21
@Kamshak Good catch! 👍

**Comment by BioPhoton** [comment] 2021-01-20 21:55
@Kamshak I'll have a look in my notes, but it sounds pretty reasonable! Verynice catch!

**Comment by Kamshak** [comment] 2021-02-12 10:22
Friendly reminder @BioPhoton, have you had a chance to look at this yet? Happy to create a PR to take that line out if that helps 😄

**Comment by BioPhoton** [comment] 2021-02-27 17:16
Hi @Kadamas we shipped RxAngular/cdk now and updated RxAngular/template with its logic. 
We should have this now in. Can you check rx-angular/template@1.0.0-beta.24, please?

Also here some cool examples of how to use the new CDK to build your own rxFor :D
https://stackblitz.com/edit/rx-angular-cdk-demo?file=src%2Fapp%2Frx-for.directive.ts

**Comment by Kamshak** [comment] 2021-03-05 11:26
This is working great now, thanks for the fix @BioPhoton! Took a bit to try this because we had to move to rxLet/push from ngrxLet/ngrxPush. General question: does it make more sense to report issues in rx-angular?

Very interesting work on rxFor, will definitely be checking it out. We're using the cdk virtual for at the moment, but I'm thinking this could be a great way to get better perf on larger lists where the size of items is not known ahead of time.

**Comment by Kamshak** [comment] 2021-03-05 11:29
The issue is fixed for me now, going to leave this open though as it's not yet fixed in the @ngrx/component package. Maintainers: feel free to close this issue at will 😄

**Comment by 4javier** [comment] 2021-03-28 13:27
I think the issue is not limited to router transition, but with parent's component `:leave` transition too.
Any milestone for this fix in @ngrx/component?

**Comment by BioPhoton** [comment] 2021-04-20 01:24
I just double-checked with @Kamshak example because we introduced the concurrent strategies, it's definitely fixed in @rx-angular.
https://stackblitz.com/edit/ngrx-bug-ngrxlet-skref3?file=src%2Fapp%2Fcomponents%2Fhome%2Fhome.component.html

AFAICT the plan in the component package is not to introduce any scheduling or so. So it should be a simple change also valid in future.

**Comment by brandonroberts** [comment] 2021-05-15 20:14
Thanks @BioPhoton. @Kamshak @4javier if you want to submit a PR, that would be great. If not, we'll get a separate fix in soon

**Closed** 2021-06-17 21:39 UTC
Labels: Accepting PRs, Good First Issue, Project: Component, bug
