### ISSUE TITLE
@ngrx/entity with strictStateImmutability. State not spread entities in reducer

### ISSUE THREAD

**Issue by Bobrovskih** [ngrx/platform#2341] opened 2020-01-29 12:20 UTC
## Minimal reproduction of the bug/regression with instructions:
in reducer
case LOAD: { ...state, pending: true };
case LOAD_COMPLETE: adapter.addAll(action.items, { pending: false });

1) dispatch action LOAD_COMPLETE = items added in state ok
2) dispatch action LOAD = fail. Because in state entities become empty array (same ids). Expect entities remain in state.

if remove flag strictStateImmutability, it works correct.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
    "@angular/core": "~9.0.0-rc.8",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/entity": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2020-01-30 15:41
Can you elaborate more and create a reproduction?
I'm not sure what the issue is here, `LOAD` does not use an entity functionality.

**Comment by Bobrovskih** [comment] 2020-01-31 14:48
so far, cant reproduce
I will write more if I can reproduce it

**Comment by timdeschryver** [comment] 2020-02-16 09:36
@Bobrovskih I'm going to close this issue for now.
If you can reproduce it, feel free to re-open this issue with the reproduction.

**Closed by timdeschryver** 2020-02-16 09:36 UTC
Labels: Needs Reproduction, Project: Entity
