### ISSUE TITLE
ngrxLet does not seem to support dictionaries of observables as stated in the documentation

### ISSUE THREAD

**Issue by colinvella-betsson** [ngrx/platform#4166] opened 2023-12-05 13:45 UTC
### Which @ngrx/* package(s) are the source of the bug?

component

### Minimal reproduction of the bug/regression with instructions

Set up an multiple observable example as per documentation:
Documentation: https://ngrx.io/guide/component/let#combining-multiple-observables

### Expected behavior

Should work as stated in the documentstion. Instead the following error is logged as a warning:
```
Observable.js:53 TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.js:27:15)
    at subscribeToResult (subscribeToResult.js:11:23)
    at CombineLatestSubscriber._complete (combineLatest.js:52:43)
    at CombineLatestSubscriber.complete (Subscriber.js:61:18)
    at Observable._subscribe (subscribeToArray.js:5:16)
    at Observable._trySubscribe (Observable.js:42:25)
    at Observable.subscribe (Observable.js:28:22)
    at CombineLatestOperator.call (combineLatest.js:26:23)
    at Observable.subscribe (Observable.js:23:31)
    at ngrx-component.mjs:191:62
```

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx: 16.2.0
Angular: 16.2.2
Node: 18.17.0
NPM: 9.6.7
TSC: 4.9.5

### Other information

I have had a cursory look at the ngrxLet directive code and while it seems it tries to cater for dictionaries of observables, it seems to pass them to `combineLatest` without converting to an array, say, but perhaps I did not fully comprehend the implementation.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment] 2023-12-05 13:49
Hey @colinvella-betsson,

You probably use it in the wrong way. It works with a dictionary of observables: https://github.com/ngrx/platform/blob/main/modules/component/spec/let/let.directive.spec.ts#L528

Please provide a reproduction, otherwise, I'd need to close the issue.

**Closed** 2023-12-11 14:38 UTC
Labels: Needs Reproduction

**Comment by sarathdrhmcts** [comment] 2024-03-22 02:48
The issue is still there with
Ngrx: 15.4.0
Angular: 15.2.10

**Comment by eichiflSICKAG** [comment] 2024-04-04 07:12
I also see the issue here with Angular 17 & Ngrx 17

```
*ngrxLet="{ dateTime: dateTime$, deviceTime: deviceTime$ } as data
<my-text-field [value]="data.dateTime.deviceTime | timezonedate: data.deviceTime.deviceTimeZone" type="date"  />
```
