### ISSUE TITLE
ngrxLet results in possibly undefined compiler errors

### ISSUE THREAD

**Issue by Isigiel** [ngrx/platform#2872] opened 2021-01-09 19:51 UTC
## Minimal reproduction of the bug/regression with instructions:

I'm using the let pipe like `<ng-container *ngrxLet="user$; let user">` with `public user$: Observable<User>;` which works fine as it doesn't trip up webstorms type system.
But now, when trying to access the properties in a strict angular environment like `<p>{{ user.phone }}</p>` I get a compiler error `error TS2532: Object is possibly 'undefined'.   12       <p>{{ user.phone }}</p>`.
Since `<p>{{ (user$ | ngrxPush).phone}}</p>` works fine I can only assume there is some kind of logic that triggers compiler errors.
Also `<p>{{ user?.phone }}</p>` gets rid of the warning for me.

## Expected behavior:

I expect to get no error as this operation is perfectly safe.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
`"@ngrx/component": "^10.1.2"`
```
Angular CLI: 11.0.6
Node: 12.19.1
OS: win32 x64

Angular: 11.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cdk                    11.0.3
@angular/cli                    11.0.6
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.3
@nguniversal/builders           11.0.1
@nguniversal/express-engine     11.0.1
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.5
```
## Other information:

Just as a wild guess, I would assume that something with the handling of null or undefined causes these issues and it would be great if the library worked in strict mode as well.

## I would be willing to submit a PR to fix this issue

I could try for sure

**Comment by timdeschryver** [comment] 2021-01-10 08:16
Seems like a duplicate of #2755

**Closed by timdeschryver** 2021-01-10 08:16 UTC
