### ISSUE TITLE
Adding routerReduer to app reducer freezes redux devtools

### ISSUE THREAD

**Issue by ashkandaie** [ngrx/platform#209] opened 2017-07-28 18:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## What is the current behavior?
Simply adding the routerReducer to the application reducer causes Redux DevTools to freeze. The first ROUTER_NAVIGATION action is displayed and does not lock up Redux DevTools. Subsequent ROUTER_NAVIGATION actions are not displayed and the extension is frozen.

## Expected behavior:
Redux DevTools should not freeze.

## Minimal reproduction of the problem with instructions:

```javascript

import * as fromRouter from '@ngrx/router-store';

export interface State {
  router: fromRouter.RouterReducerState;
}

export const reducers: ActionReducerMap<State> = {
  router: fromRouter.routerReducer,
};

```

## Version of affected browser(s),operating system(s), npm, node and ngrx:

Chrome, MacOS Siera, Redux DevTools 2.15.1

## Other information:

:heartpulse: ngrx? Please consider supporting our collective: 👉  [donate](https://opencollective.com/ngrx/donate)

**Comment by brandonroberts** [comment] 2017-07-28 18:35
Duplicate of #104

**Closed by brandonroberts** 2017-07-28 18:35 UTC

**Comment by ashkandaie** [comment] 2017-07-28 18:40
Thanks! Searched for similar issues. Didn't see that one.
