### ISSUE TITLE
Pre-initialized class fields with a TSConfig target set to ES2022 with useDefineForClassFields set to true will cause runtime issues 

### ISSUE THREAD

**Issue by Coly010** [ngrx/platform#3654] opened 2022-11-07 13:45 UTC
## The Problem

Using TS with a TSConfig which has the `target` set to `ES2022`.

```json
{
  "compilerOptions": {
    "target": "ES2022"
  }
}
```

When TS compiles code with this target, it aims to make it TC39 Compliant.

This introduces a runtime issue on modern browsers when we try to write classes that follow this pattern:

```ts
export class Effects {
  doSomething$ = createEffect(() => this.actions$.pipe(...));
  
  constructor(private actions$: Actions) {}
}
```

```ts
class MyComponent {
  storeValue$ = this.store.select(mySelector);
  
  constructor(private store: Store) {}
}
```

Following this pattern of initializing class properties by using a class property that is added via the constructor (`this.actions$`, `this.store`) will throw runtime errors that these properties are not defined.

Expected errors (listed in Browser Console):

```
Cannot read properties of undefined (reading "pipe")

Cannot read properties of undefined (reading "get")
```

## Workarounds

There are currently two workarounds.

1. Make sure your code is TC39 Compliant

```ts
export class Effects {
  doSomething$;
  
  constructor(private actions$: Actions) {
    this.doSomething$ = createEffect(() => this.actions$.pipe(...));
  }
}
```

```ts
class MyComponent {
  storeValue$;
  
  constructor(private store: Store) {
    this.storeValue$  = this.store.select(mySelector);
  }
}
```

2. For `@Injectable` classes, use the `inject()` function

```ts
export class Effects {
  private actions$ = inject(Actions);
  doSomething$ = createEffect(() => this.actions$.pipe(...));
}
```

```ts
class MyComponent {
  private store = inject(Store);
  storeValue$ = this.store.select(mySelector);
}
```

3. Set `useDefineForClassFields` in `tsconfig.json`

In your `tsconfig.json` (or `tsconfig.app.json` in Nx Workspaces), set `"useDefineForClassFields": false` in the `compilerOptions`.

Example:

```json
{
  "compilerOptions": {
     ...,
     "useDefineForClassFields": false
  }
}
```

## Notes

Existing applications that are migrated via the Angular CLI or Nx CLI will have `"useDefineForClassFields": false` set automatically.

**Comment by nartc** [comment] 2022-11-07 14:05
I'd like to add another note on "Workaround" is that if you use `inject()`, you'll likely **not** run into this issue.

**Comment by eneajaho** [comment] 2022-11-07 14:34
Reproduction: https://stackblitz.com/edit/angular-ivy-6ayd4a?file=src%2Fapp%2Fapp.component.ts

**Comment by Coly010** [comment] 2022-11-07 15:49
>  I'd like to add another note on "Workaround" is that if you use inject(), you'll likely not run into this issue.

This is true for anything that can be _injected_.  Which is the case for NgRx. It won't erase the issue for non-injectable classes.

**Comment by JeanMeche** [comment] 2022-11-07 16:52
FYI, there is an open ticket about this on microsoft/typescript#50971. 

When targeting `ES2022 `the compiler doesn't throw an error, but does it when targeting `ESNext`

**Comment by alex-okrushko** [comment] 2022-11-07 17:53
TS team says that it works ["as expected"](https://github.com/microsoft/TypeScript/issues/50971#issuecomment-1260047959), so we'll need to add `"useDefineForClassFields": false` to compiler options.

The current issue that TS is not highlighting it as an issue without the flag, and that will be fixed.

**Comment by alan-agius4** [comment] 2022-11-07 19:09
The `useDefineForClassFields` is used as part to allow users to migrate to the upcoming standard version of class fields. 

New applications using the Angular CLI will also have `useDefineForClassFields` set to `false`. But eventually we do want to disable this and generate TC39 compliant output.

I think for starters the NGRX docs should be updated to be TC39 spec complaint so at least new users don’t write non complaint code.

**Comment by brandonroberts** [comment] 2022-11-07 19:14
@alan-agius4 that seems like a pretty big ask across the entire Angular ecosystem, not just NgRx. We've discussed moving away from class-based grouping for effects but  it wasn't prompted by this recent change. Feels like this should be handled by the compiler or somewhere else upstream and not the developer.

**Comment by alex-okrushko** [comment] 2022-11-07 20:35
@alan-agius4 

> But eventually we do want to disable this and generate TC39 compliant output.

With `useDefineForClassFields` flag set either to `true` or `false` TS generates TC39 compliant code. IHMO, TS should continue to be more than just "typing" and still support some of the language features. I **do** understand that continuing with the current behavior might mean that it would be more confusing for future JS devs adopting TS.

**Comment by Coly010** [comment] 2022-11-07 21:05
@alan-agius4 in that case. I should change this issue to state a future version, not Angular 15

**Comment by alan-agius4** [comment] 2022-11-07 21:20
> @alan-agius4
> 
> > But eventually we do want to disable this and generate TC39 compliant output.
> 
> With `useDefineForClassFields` flag set either to `true` or `false` TS generates TC39 compliant code. IHMO, TS should continue to be more than just "typing" and still support some of the language features. I **do** understand that continuing with the current behavior might mean that it would be more confusing for future JS devs adopting TS.

Right, got confused both outputs are spec compliant although now in the latest spec it has a different runtime behavior.

**Comment by JeanMeche** [comment] 2022-11-07 23:13
> TS team says that it works ["as expected"](https://github.com/microsoft/TypeScript/issues/50971#issuecomment-1260047959), so we'll need to add `"useDefineForClassFields": false` to compiler options.

It's as expected, but the compiler should error, like it does with the EsNext target.

**Comment by e-oz** [comment] 2022-11-08 06:30
Nice to finally see some discussion, because when I raised a discussion about this issue it went unnoticed: https://github.com/ngrx/platform/discussions/3405

Also I want to remind you all, that Angular 15 does not allow us to control “target” and “useDefinedForClassFields”: https://github.com/angular/angular-cli/pull/23936

**Comment by alan-agius4** [comment] 2022-11-08 07:36
You can control `useDefinedForClassFields` and `target` if you target ES2022 or later.

**Comment by e-oz** [comment] 2022-11-08 07:54
It's nice that we can control “target” if the target is exactly ES2022 (because the only option left is “esnext” and you should not use it in prod).

> A customer can have a car painted any color he wants as long as it’s black 😎

**Comment by JohannesHoppe** [comment] 2022-11-16 10:26
The simplest workaround should be the following. We perform a general search and replace for both the demo and the schematics according to the following pattern:

1. search for constructors
2. Locate all properties where declaration & initialisation is done together
    --> `this.XXX: MyInjectable` is changed to `inject(MyInjectable)`
3. Keep constructor with constructor injection if the property is also used within methods, remove constructor if not needed anymore

BEFORE:

```js
@Injectable()
export class BookEffects {

  loadBooks$ = createEffect(() => {
    return this.actions$.pipe( 

      ofType(BookActions.loadBooks),
      concatMap(() =>
        /** An EMPTY observable only emits completion. Replace with your own observable API request */
        EMPTY.pipe(
          map(data => BookActions.loadBooksSuccess({ data })),
          catchError(error => of(BookActions.loadBooksFailure({ error }))))
      )
    );
  });


  constructor(private actions$: Actions) {}
}
```

AFTER:

```js
import { inject } from '@angular/core';

@Injectable()
export class BookEffects {

  loadBooks$ = createEffect(() => {
    inject(Actions).pipe( 

      ofType(BookActions.loadBooks),
      concatMap(() =>
        /** An EMPTY observable only emits completion. Replace with your own observable API request */
        EMPTY.pipe(
          map(data => BookActions.loadBooksSuccess({ data })),
          catchError(error => of(BookActions.loadBooksFailure({ error }))))
      )
    );
  });
}
```

It has even fewer lines of code! 😎

**Comment by mariomurrent-softwaresolutions** [comment] 2022-12-13 13:54
> The simplest workaround should be the following. We perform a general search and replace for both the demo and the schematics according to the following pattern:
> 
> 1. search for constructors
> 2. Locate all properties where declaration & initialisation is done together
>    --> `this.XXX: MyInjectable` is changed to `inject(MyInjectable)`
> 3. Keep constructor with constructor injection if the property is also used within methods, remove constructor if not needed anymore
> 
> BEFORE:
> 
> ```js
> @Injectable()
> export class BookEffects {
> 
>   loadBooks$ = createEffect(() => {
>     return this.actions$.pipe( 
> 
>       ofType(BookActions.loadBooks),
>       concatMap(() =>
>         /** An EMPTY observable only emits completion. Replace with your own observable API request */
>         EMPTY.pipe(
>           map(data => BookActions.loadBooksSuccess({ data })),
>           catchError(error => of(BookActions.loadBooksFailure({ error }))))
>       )
>     );
>   });
> 
> 
>   constructor(private actions$: Actions) {}
> }
> ```
> 
> AFTER:
> 
> ```js
> import { inject } from '@angular/core';
> 
> @Injectable()
> export class BookEffects {
> 
>   loadBooks$ = createEffect(() => {
>     inject(Actions).pipe( 
> 
>       ofType(BookActions.loadBooks),
>       concatMap(() =>
>         /** An EMPTY observable only emits completion. Replace with your own observable API request */
>         EMPTY.pipe(
>           map(data => BookActions.loadBooksSuccess({ data })),
>           catchError(error => of(BookActions.loadBooksFailure({ error }))))
>       )
>     );
>   });
> }
> ```
> 
> It has even fewer lines of code! 😎

Did not work for me :(

**Comment by brandonroberts** [comment] 2023-05-04 02:37
Closing this as resolved as it's handled by the framework migrations

**Closed** 2023-05-04 02:37 UTC
Labels: Comp: Docs

**Comment by duytran31187** [comment] 2023-05-16 10:01
I still got this issue. how it resolved?

**Comment by duytran31187** [comment] 2023-05-17 04:15
solution: upgrade typescript: "typescript": "4.9.4"

**Comment by JohannesHoppe** [comment] 2023-05-17 05:37
I would refactor the code to use `inject`. Here is an article that describes the issue and explains how to rewrite your code base: https://angular.schule/blog/2022-11-use-define-for-class-fields

**Comment by mrwilbroad** [comment] 2024-09-12 14:55
> ### Information
> ## The Problem
> Using TS with a TSConfig which has the `target` set to `ES2022`.
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "ES2022"
>   }
> }
> ```
> 
> When TS compiles code with this target, it aims to make it TC39 Compliant.
> 
> This introduces a runtime issue on modern browsers when we try to write classes that follow this pattern:
> 
> ```ts
> export class Effects {
>   doSomething$ = createEffect(() => this.actions$.pipe(...));
>   
>   constructor(private actions$: Actions) {}
> }
> ```
> 
> ```ts
> class MyComponent {
>   storeValue$ = this.store.select(mySelector);
>   
>   constructor(private store: Store) {}
> }
> ```
> 
> Following this pattern of initializing class properties by using a class property that is added via the constructor (`this.actions$`, `this.store`) will throw runtime errors that these properties are not defined.
> 
> Expected errors (listed in Browser Console):
> 
> ```
> Cannot read properties of undefined (reading "pipe")
> 
> Cannot read properties of undefined (reading "get")
> ```
> 
> ## Workarounds
> There are currently two workarounds.
> 
> 1. Make sure your code is TC39 Compliant
> 
> ```ts
> export class Effects {
>   doSomething$;
>   
>   constructor(private actions$: Actions) {
>     this.doSomething$ = createEffect(() => this.actions$.pipe(...));
>   }
> }
> ```
> 
> ```ts
> class MyComponent {
>   storeValue$;
>   
>   constructor(private store: Store) {
>     this.storeValue$  = this.store.select(mySelector);
>   }
> }
> ```
> 
> 2. For `@Injectable` classes, use the `inject()` function
> 
> ```ts
> export class Effects {
>   private actions$ = inject(Actions);
>   doSomething$ = createEffect(() => this.actions$.pipe(...));
> }
> ```
> 
> ```ts
> class MyComponent {
>   private store = inject(Store);
>   storeValue$ = this.store.select(mySelector);
> }
> ```
> 
> 3. Set `useDefineForClassFields` in `tsconfig.json`
> 
> In your `tsconfig.json` (or `tsconfig.app.json` in Nx Workspaces), set `"useDefineForClassFields": false` in the `compilerOptions`.
> 
> Example:
> 
> ```json
> {
>   "compilerOptions": {
>      ...,
>      "useDefineForClassFields": false
>   }
> }
> ```
> 
> ## Notes
> Existing applications that are migrated via the Angular CLI or Nx CLI will have `"useDefineForClassFields": false` set automatically.

this **work fine for me**

**Comment by Himanshu-Tamrakar** [comment] 2024-12-01 09:41
using @inject instead of constructor worked for me.

**Comment by shanidpk** [comment] 2025-02-23 06:51
using @Inject instead of constructor worked for me also
