### ISSUE TITLE
createReducer/on is not typesafe, since adding support for generic reducers

### ISSUE THREAD

**Issue by amakhrov** [ngrx/platform#3044] opened 2021-06-15 00:40 UTC
Looks like this PR (https://github.com/ngrx/platform/pull/2996), while solving some particular issues, also degraded dev experience. Mistyped state properties inside `on` callback are no longer caught at compile time

## Minimal reproduction of the bug/regression with instructions:
The code below compiles nicely, despite mistyping the property name of the state (`fakeProp` instead of `realProp`)

```
interface MyState {
  realProp: number
}

const initialState: MyState = {realProp: 1}

createReducer(
  initialState,
  on(myAction, (state) => ({
    ...state,
    fakeProp: 2
  })
)
```

## Expected behavior:

The code above should have thrown a compile time error about about incompatible types.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular: 11.2.12
NgRx: 11.1.1

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2021-06-15 05:49
Duplicate of https://github.com/ngrx/platform/issues/2851

**Closed by timdeschryver** 2021-06-15 05:49 UTC

**Comment by amakhrov** [comment] 2021-06-15 08:24
@timdeschryver 

The issue you linked is closed with the resolution saying "out of our control".
However, it used to work just fine. It's a regression introduced in a recent ngrx version. It used to catch the issue at compile time until the update related to generic reducer.

**Comment by timdeschryver** [comment] 2021-06-15 10:32
@amakhrov thanks for the update because I was also unable to reproduce it.
We do have the [on-function-explicit-return-type](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/on-function-explicit-return-type.md) in the NgRx ESLint plugin for these cases.

**Comment by amakhrov** [comment] 2021-06-15 16:50
Oh, thank you thank you thank you! That's exactly what I was looking for and couldn't find for some reason :)
