### ISSUE TITLE
NGRX Signals Needs support for Angular 18

### ISSUE THREAD

**Issue by pmathulan** [ngrx/platform#4353] opened 2024-05-24 06:26 UTC
### Which @ngrx/* package(s) are relevant/related to the feature request?

signals

### Information

Please make support for angular 18. 

![Screenshot 2024-05-24 at 11 55 51](https://github.com/ngrx/platform/assets/29794156/8787288c-c176-47b6-98b2-94f58778910b)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment] 2024-05-24 12:52
Closing as a duplicate of https://github.com/ngrx/platform/issues/4352

**Closed by brandonroberts** 2024-05-24 12:52 UTC
