### ISSUE TITLE
ngrx/component typing is lost

### ISSUE THREAD

**Issue by pegaltier** [ngrx/platform#2691] opened 2020-08-28 16:10 UTC
Currently the typing is lost using ngrxLet or ngrxPush
*ngrxLet="state$ as vm"
*ngIf="state$ | ngrxPush  as vm"
**> vm type is unknow**

On the contary if I use the old async directive I still have the typing
*ngIf="state$ | async  as vm"
**> vm type is know**

**Comment by va-stefanek** [comment] 2020-09-13 13:01
Are there some steps to reproduce your issue? In my case I have other problem in the same situation. Variable assigned by as in *ngrxLet `*ngrxLet="book$ as book"` is evaluated as Observable<T>, although in real that is T. Thus I can not access T properties in the template. When I use $implicity value eg. `*ngrxLet="book$; let book"` type is fine.

**Comment by BioPhoton** [comment] 2020-09-17 23:40
The as Syntax is not really working here atm. Also there is an open issue in Angular related to custom type guards.

The let syntax (ngrxLet="o$; let o") should work. 

I only face issues in vscode atm. 
Here the same problem https://github.com/rx-angular/rx-angular/issues/201
If we are sure we fixed it I most probably pr here too.

**Comment by vladimirdrayling** [comment] 2020-11-23 21:37
WebStorm doesn't understand the `as` syntax, too:

![image](https://user-images.githubusercontent.com/16114644/100017965-f9627880-2ddb-11eb-96d3-b40782cc9c62.png)

The `o$; let ...` syntax is fine.

Honestly the `as` syntax is much cooler :D

**Comment by pstarostka** [comment] 2020-11-30 13:02
I have same problem in VS Code

![Screenshot 2020-11-30 at 14 00 29](https://user-images.githubusercontent.com/24566569/100613187-68782980-3314-11eb-9d4e-a8655eeb232b.png)

But actually, the return type is "U | undefined":
![Screenshot 2020-11-30 at 14 01 15](https://user-images.githubusercontent.com/24566569/100613246-847bcb00-3314-11eb-9f6a-cbfcd6589bda.png)

Same with the `as` syntax

**Comment by seanwu1105** [comment] 2021-01-06 06:14
Facing the same problem with either `ngrxLet let`, `ngrxLet as` and `ngrxPush` in Visual Studio Code. The version of `@ngrx/component` is `11.0.0-beta.0` with Angular 11.

**Comment by juane1000** [comment] 2021-05-05 20:33
Also facing the issue since the early beta versions. Currently on @ngrx/component 11.1.1 with Angular 11.2.12. Functionally it still works but the template typing loss is sort of a show stopper for the dev experience. Hope this gets resolved.

**Comment by brandonroberts** [comment] 2021-05-15 20:18
If someone wants to submit a PR, that would be great.

**Comment by samuelfernandez** [comment] 2021-06-17 06:56
@brandonroberts I started to investigate this one, and it is not a problem with the library. `ngrxLet` directive already implements everything needed for template checking, namely, `ngTemplateContextGuard`. To have this working in a project it is required to:

* Use Ivy in the app
* Have latest version of the Angular Language Service extension
* Make sure it doesn't use the View Engine
* As the extension suggests, add this configuration at `tsconfig.json`:

```json
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  }
```

I've tested that internally in the example app and template checking works correctly.

![image](https://user-images.githubusercontent.com/19343955/122346905-c2a3a980-cf49-11eb-8396-470d7d33fe3d.png)

I'd suggest to close this issue, since it is related to an uncomplete app configuration.

**Comment by timdeschryver** [comment] 2021-06-18 13:33
Thanks for the info @samuelfernandez

**Closed by timdeschryver** 2021-06-18 13:33 UTC
Labels: Accepting PRs, Project: Component, bug

**Comment by vladimirdrayling** [comment] 2021-06-18 22:02
![image](https://user-images.githubusercontent.com/16114644/122619102-ee30ac00-d08f-11eb-9e91-a9897bf824c9.png)

For some reason it still doesn't show the unpacked data. WebStorm 2021.1.2. The variable `state` does have correct typings but if I try to access them it's not working.

Continue using alternative `*ngrxLet="o$; let state"`. And that's the result.

![image](https://user-images.githubusercontent.com/16114644/122619336-83cc3b80-d090-11eb-9fd1-f8144b5b1f31.png)

**Comment by david-shortman** [comment] 2021-06-18 22:05
> For some reason it still doesn't show the unpacked data. WebStorm 2021.1.2. The variable `state` does have correct typings but if I try to access them it's not working.
> 
> Continue using alternative `*ngrxLet="o$; let state"`. And that's the result.
> 
> ![image](https://user-images.githubusercontent.com/16114644/122619336-83cc3b80-d090-11eb-9fd1-f8144b5b1f31.png)

Does the Angular plugin for Webstorm use the Angular Language Service or the Ivy Language Service?

**Comment by vladimirdrayling** [comment] 2021-06-18 22:49
I didn't install any angular plugins. Using webstorm as is

**Comment by david-shortman** [comment] 2021-06-18 23:05
> I didn't install any angular plugins. Using webstorm as is

Then a probable cause is that whatever is the built-in Angular plug-in for Webstorm doesn't use the Ivy Language Service.

**Comment by vladimirdrayling** [comment] 2021-06-19 00:17
@david-shortman thank you for the help. Working in VSCode as expected.

![image](https://user-images.githubusercontent.com/16114644/122624709-cc402500-d0a1-11eb-8196-f84d16eef3cc.png)

**Comment by dc-p8** [comment] 2021-08-05 13:18
same for me. In VScode the typing is good but webstorm fail with the "as" syntax (but the "let" syntax has the good typing in webstorm).
