### ISSUE TITLE
@ngrx/data doesn't seem to tolerate parameters

### ISSUE THREAD

**Issue by wbhob** [ngrx/platform#1934] opened 2019-06-08 23:02 UTC
## Other information:
_Many_ apps have relational data, as well as child structures, and I'm surprised an issue hasn't been opened about this before. Essentially, our use case is as follows.

We have a base object, say "vendors", which have products and events. Managing the vendors with @ngrx/data is relatively simple, but as soon as I try to write a data wrapper for events or products, type-checking prevents me from doing so.

In other words, vendors can be fetched from `/api/vendors`, but getting vendor products requires passing a vendor id, i.e. `/api/vendors/:vendor_id/products`. There aren't any docs on this whatsoever, and, like I said, the built in types don't like this fairly common data structure _at all_.

Similarly, there is no documentation on how to add peripheral data, like pagination. Other issues about this have said that ngrx/data doesn't care about your pagination, and that you can implement it yourself, which would be fine if there were some sort of sample app or demo or docs to base it on. But after hunting the internet, there don't seem to be any docs or demos on a *sample* implementation that we can base it on, just people saying "ngrx data lets you do it yourself!".

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by wbhob** [comment] 2019-06-09 02:45
For clarity:

All we need is to pass a parameter in to, say, `getAll`. In my container code, I am already aware of the `vendor_id`, and the only thing stopping me is that I can't pass a parameter to `getAll()` or any other method. It would be life saving to allow for parameterized methods in the Collection and Data service models, and to pass them accordingly under the hood.

**Comment by JiaLiPassion** [comment] 2019-06-11 19:41
@wbhob, I have the same use cases with you, and I am working on the documentation and PR of those issues, for the `pagination`, you can reference to my updated doc here https://github.com/ngrx/platform/blob/master/projects/ngrx.io/content/guide/data/entity-metadata.md

**Comment by timdeschryver** [comment] 2019-06-13 07:19
@JiaLiPassion, this is #1944 right?

**Comment by JiaLiPassion** [comment] 2019-06-13 08:15
@timdeschryver. #1944 is another use case. @wbhob 's use cases are.
1. pagination, this can be resolved by my earlier PR, #1921.
2. nested data, such as products belongs to vendor, so get products need to pass vendor id, this one is not supported by `@ngrx/data` now.

#1944 resolved another use case, which is we may have multiple backend endpoints return the similar data, such as `getMostPopularProducts` and `getLatestProducts`, if we want to reuse the `getWithQuery action`, we need to use `tag`. (the `tag` by design is to resolve the use cases like this).

**Comment by timdeschryver** [comment] 2019-06-13 08:25
Ok, thanks for clarifying this.

**Comment by wbhob** [comment] 2019-06-13 12:34
Thanks for the help guys! I'll keep an eye out for this issue, as this would help a lot with our development.

**Comment by GreedyA1** [comment] 2019-11-12 06:50
@JiaLiPassion Is there any workaround or updates on nested data?

Could you recommend how to deal with sitaution, where we have nested data from server?

**Comment by AdditionAddict** [comment] 2020-02-28 11:36
There's a hacky way using `EntityCacheDispatcher`

- Create your custom action e.g. type "[OrderProductsPage ONINIT] ONINIT"
- Create effect that calls saveEntities
```
// include in custom action payload and get this id here
const id;

// fake changes to get past guards in EntityCacheEffects
const changeSet = {
    changes: [
        cif.add("Product", {}) // required to get past guard
    ],
    // hook for defining custom behaviour
    tag: "CUSTOM_GET_PRODUCTS" 
};
this.entityCacheDispatcher.saveEntities(changeSet, `orders/${id}/products`)
```
-  a. Extend `EntityCacheDataService` and override the `saveEntities` method to first check if tag is CUSTOM_GET_PRODUCTS otherwise call `super.saveEntities(changeSet, url)` 
- b. If tag is CUSTOM_GET_PRODUCTS than call get http and pipe map to changeSet with ChangeSetOperation.Add
- pipe map to `ChangeSet` so that SAVE_ENTITIES_SUCCESS reducer kicks in

### [Stackblitz](https://stackblitz.com/edit/angular-rkok45-custom-url-ngrx-data)
---

This begs the natural question...

@wardbell should `EntityCacheDispatcher` be extended to include method with following API?

`getEntities(url: string, params?: QueryParams, mergeStrategy?: MergeStrategy): Observable<ChangeSet>`

This way someone can call a get request with whatever url they like and change state in a manner of their choosing by mapping to an `Observable<ChangeSet>` response and specifying `mergeStrategy`

Would require following changes:

_New Entity Cache Actions_
GET_ENTITIES
GET_ENTITIES_SUCCESS
GET_ENTITIES_FAIL

Implementations in _EntityCacheEffects_ _EntityCacheDataService_. Can't find anything else...

Happy to do a PR

As an aside, do you have a UML diagram / fuller architecture diagram for ngrx/data?

**Comment by AdditionAddict** [comment] 2020-02-28 11:44
> 
> 
> @JiaLiPassion Is there any workaround or updates on nested data?
> 
> Could you recommend how to deal with sitaution, where we have nested data from server?

@GreedyA1

Yes.
Extend `DefaultDataService`
Within a pipe map nested data to entities (I use normalizr)
```
  getById(key: string | number): Observable<ConcreteRecordHeader> {
    return super.getById(key).pipe(
      map((denorm: any) =>
        this.categoryCacheService.normalizeCategory([denorm])
      ),
      tap((norm: NormalizedCategories) => this.mergeQuerySet(norm)),
      map((norm: NormalizedCategories) => this.pickEntities(norm)[0])
    ) as Observable<ConcreteRecordHeader>;
  }

  protected mergeQuerySet(norm: NormalizedCategories) {
    console.log("⚠️ Merging server data ⚠️");
    const options: EntityActionOptions = {
      mergeStrategy: MergeStrategy.PreserveChanges
    };
    const data = norm.entities.concreteRecordLoads
      ? Object.values(norm.entities.concreteRecordLoads)
      : [];
    const action = this.eaFactory.create(
      "ConcreteRecordLoad",
      EntityOp.SAVE_UPSERT_MANY_SUCCESS,
      data,
      options
    );
    this.entityCacheDispatcher.dispatch(action);
  }

  protected pickEntities(norm: NormalizedCategories) {
    return (norm.entities.concreteRecordHeaders
      ? Object.values(norm.entities.concreteRecordHeaders)
      : []) as ConcreteRecordHeader[];
  }
```
Sadly `this.entityCacheDispatcher.mergeQuerySet()` isn't working with mergeStrategy

**Comment by brandonroberts** [comment] 2021-05-15 20:04
If someone still wants to open a PR for this, feel free

**Comment by kichnan** [comment] 2021-06-08 19:31
@brandonroberts Would love to contribute. How can I get started? Does the following make sense?

My initial thought is to simply support Angular HTTP Client's new ["context" token for HTTP interceptor](https://netbasal.com/308a1ca2f3dd) feature when calling ANY of the side-effect actions in EntityCollectionService, i.e. getAll, getWithQuery, getByKey, add, update, delete, upsert.
That way, the core ngrx data need not be changed at all. People who want different behaviours for their http calls can introduce the "context" and pass it as an EntityActionOptions param. AND use HttpInterceptor to modify the final HTTP API call signature/behaviour.

I feel that this would be highly scalable because the responsibility of constructing such a URL is delegated to the user (developer) himself.

Shall I get started on this approach?

**Closed** 2021-07-21 02:31 UTC
Labels: Accepting PRs, Project: Data
