### ISSUE TITLE
Cannot import saved store state using devtools package

### ISSUE THREAD

**Issue by MikeDabrowski** [ngrx/platform#3636] opened 2022-10-28 09:45 UTC
### Which @ngrx/* package(s) are the source of the bug?

store-devtools

### Minimal reproduction of the bug/regression with instructions

Using chrome redux dev tools, export the state to .json and import it again.

![image](https://user-images.githubusercontent.com/17836911/198557654-693a680a-d7ce-4e39-9376-0d0278b02b65.png)

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

+-- @ngrx/effects@14.3.2
+-- @ngrx/entity@14.3.2
+-- @ngrx/router-store@14.3.2
+-- @ngrx/schematics@14.3.2
+-- @ngrx/store-devtools@14.3.2
+-- @ngrx/store@14.3.2

### Other information

I think the problem is in the following line: https://github.com/ngrx/platform/blob/24c086f94e0a16b0733a144f0cbe42557107503f/modules/store-devtools/src/reducer.ts#L408-L420

The `nextLiftedState` has the store structure and therefore does not contain all those 'meta' properties. This results in the error `Cannot read properties of undefined (reading 'length')`

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment] 2023-04-15 13:13
I'm closing this because it has no reproduction.
Feel free to reopen/create a new issue with a reproduction.

**Comment by MikeDabrowski** [comment] 2023-04-18 20:39
this is false
>it has no reproduction


So here you go: https://stackblitz.com/edit/angular-urqqk2?file=src/main.ts

Latest angular and ngrx. You will need to:

1. have chrome redux dev tools installed
2. go to the page above
3. open dev tools and select proper store instance
4. save the state to file
5. load saved state from file
6. see console with the same error

![image](https://user-images.githubusercontent.com/17836911/232899580-3d900e85-3ebd-45c7-af7c-351e7f632cca.png)  
![image](https://user-images.githubusercontent.com/17836911/232898503-44181378-37db-4c68-b793-42ea1145291a.png)  
![image](https://user-images.githubusercontent.com/17836911/232898981-6c0ec3cd-9239-46b4-8d9d-0fa3b37e3d44.png)

**Comment by timdeschryver** [comment] 2023-04-19 17:18
Thanks @MikeDabrowski

**Comment by timdeschryver** [comment] 2023-04-22 11:48
This should work if you set the value of the `import` feature to `'import'`.

**Comment by MikeDabrowski** [comment] 2023-04-22 11:56
![image](https://user-images.githubusercontent.com/17836911/233783288-0a3b7c07-3eb6-4fa6-9e43-b9521b659b9a.png)

**Comment by timdeschryver** [comment] 2023-04-22 12:10
My bad, I meant `'custom'` @MikeDabrowski

**Closed** 2023-04-24 18:12 UTC
Labels: Project: Store Devtools
