### ISSUE TITLE
ngrxOnRunEffects behaves differently when the effect is loaded via `forRoot` vs `forFeature`

### ISSUE THREAD

**Issue by jeetparikh** [ngrx/platform#1130] opened 2018-06-14 01:29 UTC
## Minimal reproduction of the bug/regression with instructions:

I am trying to use the `ngrxOnRunEffects` to control when the effects in my class should start listening. I have added `ngrxOnRunEffects` in my effect class as follows:
This is a very simple version of it which basically does nothing but returns the `resolvedEffects`

```
ngrxOnRunEffects(resolvedEffects$: Observable<EffectNotification>) {
        return this.actions$
          .pipe(
            exhaustMap((res) => {

                return resolvedEffects$;
            })
          );
    }
```

This is a part of a lazy loaded module.  When this effect is specified in the module import as `forFeature(featureClass)`,  NONE of the effects in this class execute when I visit the page for the first time. But when I navigate away and come back to the page then all the `effects` in THIS class start working. However, if use `forRoot(featureClass)` then all the `effects` in THIS `class` work as expected for the first time as well.

**What I was actually trying to achieve with `ngrxOnRunEffects`**

In our application, we dispatch a `ROUTER_NAVIGATION` action for each router state change. The router state name is maintained in such a way that each page would have a parent state and then child router states. For example, the root for a particular page is `pageA` then the children would be `pageA.child1`, `pageA.child2` and so on... Corresponding to each page, we have an `Effects class`. So the idea was the `ngrxOnRunEffects` would switch all the effects in the class ON/OFF based on the current route. Basically, the effects would only be listening when you are in THAT particular view.
Below is the sample of what I was trying to achieve

```
return this.actions$.pipe(
          ofType(ROUTER_NAVIGATION),
          filter((action: RouterNavigationAction) => {
              const routerState: any = action.payload.routerState;
             // start listening when the user navigates to the current page
              return routerState.name.indexOf('pageA') > -1;
          }),
          exhaustMap(() => {
                return resolvedEffects$.pipe(
                  takeUntil(
                    this.actions$
                      .pipe(
                        ofType(ROUTER_NAVIGATION),
                        filter((action: RouterNavigationAction) => {
                            const routerState: any = action.payload.routerState;
                           // stop listening when the user navigates away from this page
                            return routerState.fromState.name === '' || routerState.fromState.name.indexOf('pageA') > -1;
                        })
                      )
                  )
                )
            }
          )
        );
```

This is basically a step towards optimisation so that all effects are not listening for `each` dispatched action.
Is the above achievable? Also, would the `effects` start listening when the user `navigates` back for the next time?

## Expected behavior:

The `ngrxOnRunEffects` shuould behave the same whether it is used with `forRoot` vs `forFeature`

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
NgRx: 6.0.0-beta.3
Angular: 6.2.0
Node: 8.11.1
Affected Browsers: Chrome and possibly others
Operating System: MacOS 10.13.5

## Other information:
I am unable to produce this on `stackblitz` since I would actually require an entire application to be provided as whole. But I have tried to provide as much code as possible. Thanks

**Comment by tdeschryver** [comment] 2018-06-18 18:09
Hi, I tried to reproduce your first example but it works fine for me?
In the todo folder you can find the feature module, when the todo component is loaded I fire the Load action. In the effects I log something whenever the Load action is dispatched.

[StackBlitz link](https://stackblitz.com/edit/ngrx-seed-banszs)

**Comment by jeetparikh** [comment] 2018-06-18 23:30
hi @tdeschryver thank you for the response. Not sure what is going on in my configuration. Could you please have a look and see if anything is incorrect.

This is my feature module config

```
@NgModule({
  imports: [
    CommonModule,
    CoreModule.forChild(),
    ReactiveFormsModule,
    UIRouterModule,
    FeatureRoutes,
    EffectsModule.forFeature([
      FeatureEffects
    ]),
    ForDirectiveModule
  ],
  declarations: [
    AComponent,
  ],
  entryComponents: [
  ],
  exports: []
})

export class FeatureModule {}```


And this is my `app module` config

```
@NgModule({
    bootstrap: [
        AppComponent
    ],
    declarations: [
        AppComponent
    ],
    imports: [
        CurrencyModule.forRoot(),
        CoreModule.forRoot(),
        FormsModule,
        HttpClientModule,
        StoreModule.forRoot({
            reducerA,
           reducerB
        }, {
            initialState,
            metaReducers
        }),
        EffectsModule.forRoot([
            CoreEffectA,
            CoreEffectB
        ]),
        AppRouterStoreModule,
        !environment.production ? StoreDevtoolsModule.instrument({ maxAge: 50, name: 'Bla bla' }) : [],
    ],
    providers: [
        APP_PROVIDERS,
    ]
})```

Is there anything wrong with the `config`? cos in my case none of `effects` fire up if I use `forFeature`

**Comment by tdeschryver** [comment] 2018-06-19 08:37
I'm not 100% about it, have you tried it?
Is it OK if we're going to close this issue, since I don't think it is an issue.

We can discuss it further over at our [gitter channel](https://gitter.im/ngrx/platform) if you need some help - if it appears that it is an issue, we can re-open it.

Also, a reproduction would really help, at least for me 😅

**Comment by maxisam** [comment] 2018-06-19 15:09
I think the question is should we even need to worry about this? If so, it seems to me, this should be taken care by ngrx instead of in every application.

**Comment by tdeschryver** [comment] 2018-06-19 16:04
@maxisam If it's indeed a bug, we have to take care of it.
But I'm guessing this isn't a bug, but either something wrong in the setup (I could be wrong tho).
This isn't the right channel for "guidance" imho, that's why I asked to join the gitter channel.

**Comment by maxisam** [comment] 2018-06-19 16:55
@tdeschryver You misunderstood. I was trying to say should we need to worry about performance issue when there are too many effects. If so should we handle this in ngrx instead of every application?

I don't think it is a performance issue but it might be a memory issue. I think there should be a way to unload a feature store. 

I feel the original question is a pretty interesting pattern. Turn on and off for an Effect base on the active route. I feel like if this pattern is necessary or provide a lot of benefits, should we think about how to make it easier from ngrx side?

**Comment by tdeschryver** [comment] 2018-06-19 17:10
Oooh sorry :sweat_smile:, I thought you were referring to my question about closing the issue.
But yea, it's indeed an interesting pattern.

**Comment by jeetparikh** [comment] 2018-06-19 22:47
thanks @tdeschryver @maxisam .  Well, I think I am happy to close. Maybe something going on in my config that is interfering which I need to investigate. Thank you for the help. And how about the thoughts on the pattern? How do we want to take it forward from here? Should I close this one and make a feature request?

**Comment by tdeschryver** [comment] 2018-06-20 05:37
I'm not sure if this is something we would want (to maintain) in NgRx. 
Let's not close this issue and see what @brandonroberts or @MikeRyanDev has to say.

**Comment by jeetparikh** [comment] 2018-06-20 05:38
sure.. thanks @tdeschryver

**Comment by jeetparikh** [comment] 2018-06-26 23:43
@tdeschryver on that note.. is this something possible to achieve like the way m doing right now
```
return this.actions$.pipe(
          ofType(ROUTER_NAVIGATION),
          filter((action: RouterNavigationAction) => {
              const routerState: any = action.payload.routerState;
             // start listening when the user navigates to the current page
              return routerState.name.indexOf('pageA') > -1;
          }),
          exhaustMap(() => {
                return resolvedEffects$.pipe(
                  takeUntil(
                    this.actions$
                      .pipe(
                        ofType(ROUTER_NAVIGATION),
                        filter((action: RouterNavigationAction) => {
                            const routerState: any = action.payload.routerState;
                           // stop listening when the user navigates away from this page
                            return routerState.fromState.name === '' || routerState.fromState.name.indexOf('pageA') > -1;
                        })
                      )
                  )
                )
            }
          )
        );
```

**Comment by tdeschryver** [comment] 2018-06-27 06:15
@jeetparikh I would expect that the feature you want should work. 
But I can't say for sure that there is something wrong with "your" implementation without having a reproduction.

**Comment by timdeschryver** [comment] 2018-10-29 08:05
Hi, I'm going to close this issue as we didn't get a response for a while.

**Closed by timdeschryver** 2018-10-29 08:05 UTC
Labels: Project: Effects
