### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by rafal-rapcewicz** [ngrx/platform#3896] opened 2023-05-16 17:53 UTC
### Which @ngrx/* package(s) are relevant/related to the feature request?

component-store, component, data, effects, entity, eslint-plugin, router-store, schematics, store-devtools, store

### Information

Could you introduce dark mode please ... ?

### Describe any alternatives/workarounds you're currently using

none

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by markostanimirovic** [comment] 2023-05-16 22:22
duplicate of https://github.com/ngrx/platform/issues/3805

**Closed by markostanimirovic** 2023-05-16 22:22 UTC
