### ISSUE TITLE
Strange behaviour with entity and selectAll (maybe a bug)

### ISSUE THREAD

**Issue by cesco69** [ngrx/platform#2707] opened 2020-09-08 10:04 UTC
## Minimal reproduction of the bug/regression with instructions:

`seletAll` from `getSelectors()` fire event without change into own feature store, but when the root store changes, see demo:

https://stackblitz.com/edit/angular-ngrx-test-123654789?file=src%2Fapp%2Ffeatures%2Fbar.component.ts

this behaviour happens only if `seletAll` is used into other selector.

Open the the demo and click on the button. The button dispatch a change into the root store, but `selectAll` from the feature store also fire the event.

## Expected behavior:

seletAll fire event only when the changes comes into the feature store.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx 10
Angular 10

**Comment by timdeschryver** [comment] 2020-09-08 20:42
I'm not sure if this is a bug, and if we can do something about it.
The root cause is the props selector, which shares the same `selectAll` instance.

A fix is to wrap `selectAll` into another selector:

```
export const selectBar = createSelector(selectAll, (items) => items);
```

**Comment by cesco69** [comment] 2020-09-09 06:49
@timdeschryver wrap selectAll don't solve the problem if the wrapper is used in other selectors. The only workaround is create one wrapper of selectAll for each selectors use then. But, this is just a workarond... 

By design, what is the correct usage of selectAll into other selectors?

**Comment by timdeschryver** [comment] 2020-09-09 11:44
That's just how prop selectors behave (they pass down props to all "child" selectors).

Perhaps a better work around is to use a factory selector:

```
export const selectBarById = (id: number) =>
  createSelector(selectAll, (itemEntities: Bar[]) =>
    itemEntities ? itemEntities.filter((element) => element.id === id) : []
  );
```

**Comment by cesco69** [comment] 2020-09-09 14:22
But from the https://ngrx.io/guide/entity/adapter the example suggest that is safe to use selectAll inside other selector... maybe we can report into the docs this behaviour.

**Comment by timdeschryver** [comment] 2020-09-09 16:59
To be clear, it's safe to use.

The selector "just" emits a second time in combination with props selectors (and in the specific order, first `selectAll` and then the selector based on the props).
From what I can see, the selectors aren't even invoked because of the memoization.

**Comment by nigrosimone** [comment] 2020-09-09 18:58
By design a selector fire when the selected state changes. This can be a bug because break the expected behavior.

**Comment by cesco69** [comment] 2020-09-10 07:00
@timdeschryver i have made another test with a fork of the first example https://stackblitz.com/edit/angular-ngrx-test-123654789-a7js8p?file=src%2Fapp%2Ffeatures%2Fbar.component.ts

If selectAll is used in more selectors, all selectors that use selectAll and selectAll itself fire changes everytime a change is made elsewhere, everytime a change is made and not just on the first change like the first example.

**Comment by timdeschryver** [comment] 2020-09-10 16:40
@cesco69 thanks for the example but can I please ask you to read my comments.

The following works:

```
// If this line is commented out, the behaviour is the expected one
this.store.select(BarSelectors.selectBarById({id: 1})).subscribe(result => this.selectors.push('BarSelectors.selectBarById')); 
// And with this other the problem become big...
this.store.select(BarSelectors.selectBarByBar({bar: true})).subscribe(result => this.selectors.push('BarSelectors.selectBarByBar')); 
```

**Comment by cesco69** [comment] 2020-09-11 06:53
@timdeschryver yes, I have implemented the fix on my _env_, but the point is: is a workaround or the standard, expected, implementation?

**Comment by timdeschryver** [comment] 2020-09-14 18:11
@cesco69 it's expected, see https://ngrx.io/guide/store/selectors#using-selectors-with-props for more info.
A fix on the NgRx side would be to expose factory selectors for the entity selectors, e.g.

```
return {
  selectIds: createSelector(selectState, selectIds),
  selectEntities: createSelector(selectState, selectEntities),
  selectAll: createSelector(selectState, selectAll),
  selectTotal: createSelector(selectState, selectTotal),
  // 👇 this one here
  createSelectAll: () => createSelector(selectState, selectAll),
};
```

**Comment by cesco69** [comment] 2020-09-16 09:40
Hi @timdeschryver i have founded another problem. 
the following example https://stackblitz.com/edit/angular-ngrx-test-123654789-a7js8p?file=src%2Fapp%2Ffeatures%2Fbar.component.ts don't use selectAll into the selectBarById and selectBarByBar selectors.

When click on the button, a new entity is added with addOne, selectBarByBar fire change without change into his selection...

```ts
// the selector
export const selectBarByBar = (bar: boolean) => createSelector(
  selectBarState,
  (state: BarState) => { 
    if(state.entities) {
      const entities = [];
      Object.keys(state.entities).forEach(id => {
        if( state.entities[id].bar === bar ){
          entities.push(state.entities[id]);
        }
      });
      return entities;
    } 
    return null;
  }
);

// add new item with "bar: false" casue fire of selectBarByBar(true)
this.store.dispatch(BarActions.addOne({bar:{ id: Date.now(), bar: false}}));

// this fire
this.store.select(BarSelectors.selectBarByBar(true)).subscribe(result => this.selectors.push('BarSelectors.selectBarByBar')); 
```

**Comment by timdeschryver** [comment] 2020-09-21 16:35
@cesco69 this is behaving as intended. 
Selectors are using a reference check (===). 
What you're doing in the selector is creating a new reference to the entities array, thus this check will fail.

I'm going to close this issue (for the entities selectors) but I think this is a niche problem.
We can reevaluate later if this pops up again.

**Closed by timdeschryver** 2020-09-21 16:35 UTC
Labels: Project: Entity, Project: Store
