### ISSUE TITLE
Effects are still subscribed to when changing feature module in NgRx

### ISSUE THREAD

**Issue by PooSham** [ngrx/platform#2581] opened 2020-06-15 16:09 UTC
I'm not sure you'll consider this a bug, but I wonder if this is the intended behaviour. 

I have a project with multiple lazy-loaded features. In one of them, I have an effect that listens to actions of type `routerNavigatedAction` from `@ngrx/router-store`, like this:

```
changeRoute$ = createEffect(() =>
    this.actions$.pipe(
        ofType(routerNavigatedAction),
        mergeMap(action => 
            this.http.get("/some/url").pipe(map(x => myFeatureActions.loadSuccess(x)))
        )));
```

But when I go to another part of the website, loading another feature (ie a module loaded under another route), I can still see these calls being made. So the subscription made by the EffectsModule doesn't unsubscribe from the effects it has subscribed to. 

If I'm using angular or ngrx in the wrong/unintended way, please tell me. However, I feel like this could be a memory leak, because all the effects inside inactive modules are still subscribed to. I understand this might be the desired behaviour sometimes, but I would at least like some documentation on how to unsubscribe from these effects when visiting another feature module. 

I will upload a stackblitz along with minimal reproduction instructions ASAP.

## Expected behavior:

Either:
1. EffectsModule inside a feature automatically unsubscribes from the subscibed effects when routing to another feature module (ie when a feature module is unused)
2. There is an API with documentation about how to unsubscribe from selected or all subscribed effects. For example, this could be used in `ngOnDestroy` inside the feature module's Effect service

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular: 9.0.0
Angular CLI: 9.0.1
ngrx-store: 9.1.0
ngrx-effects: 9.1.0
ngrx-router-store: 9.1.0
Node: 10.16.2
OS/Browser: win32 x64 / Firefox Dev Edition 78.0b6 64bit (assumed to not matter, but included for completeness)

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ X ] No

Well, I haven't really looked into the NgRx code, so I'm not sure I could right now. But maybe later I could.

**Comment by timdeschryver** [comment] 2020-06-15 16:50
This is the desired result, with the [OnRunEffects lifecycle](https://ngrx.io/guide/effects/lifecycle#onruneffects) you can "unsubscribe" an Effect.

Perhaps adding an example on how to do this for feature modules can be helpful.

**Comment by alex-okrushko** [comment] 2020-06-15 17:23
FYI, effects start running whenever the app bootstraps, unless they are part of the lazy-loaded module(s). "Features" aren't really tied to any tree of components.

Upcoming `@ngrx/component-store` handles this well when it's tied to a particular Component's lifecycle - but it's designed to be that local/component/module part of the state, unlike `@ngrx/store` or `@ngrx/effects`, which are meant for the global app state.

**Comment by timdeschryver** [comment] 2020-06-16 10:55
As this is the intended behavior, I'm going to close this issue.
Feel free to add an example to the docs if you want.

**Closed by timdeschryver** 2020-06-16 10:55 UTC
Labels: Project: Effects
