### ISSUE TITLE
@ngrx/store-dev-tools: nightly - TypeError asObservable of

### ISSUE THREAD

**Issue by Kaffiend** [ngrx/platform#58] opened 2017-07-03 20:27 UTC
Was just migrating to the nightly build and ran across this updating to the latest dev-tools

tsc -v 2.3.4

```
main.browser.ts:26 TypeError: Cannot read property 'asObservable' of undefined
    at new StoreDevtools (store-devtools.es5.js:544)
```

**Comment by brandonroberts** [comment] 2017-07-03 20:29
Duplicate of #30

**Closed by brandonroberts** 2017-07-03 20:29 UTC
