### ISSUE TITLE
RouterState is undefined when creating selectors using it

### ISSUE THREAD

**Issue by blackholegalaxy** [ngrx/platform#835] opened 2018-02-17 16:59 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The routerState cannot be retrieved from selectors. Creating a selector for routerState leads to get an `undefined` value.

Here is the redux tools state init sequence, in case it's useful:

![redux_tools](https://user-images.githubusercontent.com/11064123/36343377-9bd0d96a-13d9-11e8-905d-77e552a72b05.png)

## Expected behavior:
Being able to access routerState from anywhere in the store without being undefined.

## Minimal reproduction of the problem with instructions:
We use NGRX to manage our state. We use several feature states.

Our store structure is created at different levels of our lazy loaded modules:

```
Core: router + auth
   |___ OurApp Module (lazy loaded): layoutState
        | ___   Admin Module (lazy loaded): adminState (containing the institutionState as described below)
```

Our app.module.ts:

```
imports: [
    ...
    StoreModule.forRoot(reducers, { metaReducers }),
    EffectsModule.forRoot(effects),
    StoreRouterConnectingModule,
],
providers: [
   ...
   {
      provide: RouterStateSerializer,
      useClass: fromStoreUtils.CustomRouterStateSerializer,
    },
]
```

CustomSerializer:

```
export class CustomRouterStateSerializer
  implements fromRouter.RouterStateSerializer<RouterStateUrl> {
  serialize(routerState: RouterStateSnapshot): RouterStateUrl {
    let route = routerState.root;

    while (route.firstChild) {
      route = route.firstChild;
    }

    const { url, root: { queryParams } } = routerState;
    const { params } = route;

    return { url, params, queryParams };
  }
}
```

Our root/core reducer:

```
import * as fromNgrxRouter from '@ngrx/router-store';
import * as fromAuth from './auth.reducer';

export interface RouterStateUrl {
  url: string;
  queryParams: Params;
  params: Params;
}

export interface State {
  router: fromNgrxRouter.RouterReducerState<RouterStateUrl>;
  auth: fromAuth.AuthState;
}

export const reducers: ActionReducerMap<State> = {
  router: fromNgrxRouter.routerReducer,
  auth: fromAuth.reducer,
};

export const getRouterState = createFeatureSelector<fromNgrxRouter.RouterReducerState<RouterStateUrl>>('router');
```

Creating any selector with routerState gets us an undefined routerState.

Exemple of a selector as we intend to use it:
```
export const getSelectedInstitution = createSelector(
  getInstitutionsEntities,
  getRouterState,
  (entities, router): Institution => {
    console.log(router);
    return router.state && entities[router.state.params.institutionId];
  }
);
```

We also tried to put a simple subscribe to select the router State in app.component.ts: 

```
this.store.select(getRouterState).subscribe((router) => console.log(router));
```

These two selectors returns us an `undefined` value.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
```
"@ngrx/effects": "5.1.0",
    "@ngrx/entity": "5.1.0",
    "@ngrx/router-store": "5.0.1",
    "@ngrx/store": "5.1.0",
    "@ngrx/store-devtools": "5.1.0",
```

**Comment by BrianCerasuolo** [comment] 2018-02-18 16:05
getting the same issue in our app. it's easily fixed by null checking in every selector that touches the router store state, but would be nice to have this check built in.

**Comment by bossqone** [comment] 2018-02-18 17:57
Hello,
there's probably an issue with registration of router state. You need to use:
```ts
StoreRouterConnectingModule.forRoot({
    stateKey: 'router' // name of reducer key
})
```
otherwise it will use `routerReducer` as default router state key.

**Comment by blackholegalaxy** [comment] 2018-02-18 19:51
Just tried to change the registration as stated in @bossqone comment. But it doesn't change anything and still returns undefined.

**Comment by bossqone** [comment] 2018-02-18 21:10
Can you reproduce same behaviour on stackblitz? I've tried basic app (without lazy modules) and it works - https://stackblitz.com/edit/angular-1gfui7, please feel free to modify my example to match your project/structure.

**Comment by BrianCerasuolo** [comment] 2018-02-20 19:55
I think the issue is only when using the createFeatureSelector inside of a createSelector.

Here is a stack blitz with the error shown: https://stackblitz.com/edit/angular-kinkha 
If you create a selector off of the feature selector it has state being returned as undefined.

**Comment by brandonroberts** [comment] 2018-02-20 20:32
The router key will be undefined initially because navigation hasn't happened yet. See https://stackblitz.com/edit/angular-v2aiih?file=app/app.module.ts for a working example.

**Comment by blackholegalaxy** [comment] 2018-02-20 21:11
Why is this closed? 

Of course the router key is undefined initially. That's not the problem. In my case the call to the selector using the routerState selector happens way after nav init. At the moment of the call, the state shows router state correctly. But the selector returns undefined.

I tried to reinstall node_modules without more success.

**Comment by brandonroberts** [comment] 2018-02-20 21:40
@blackholegalaxy I thought the reproduction provided was the issue. Provide a repro through stackblitz

**Comment by miniplus** [comment] 2018-02-22 14:42
@brandonroberts as stated by @BrianCerasuolo in https://github.com/ngrx/platform/issues/835#issuecomment-367099578

> I think the issue is only when using the createFeatureSelector inside of a createSelector.
>
>Here is a stack blitz with the error shown: https://stackblitz.com/edit/angular-kinkha
>If you create a selector off of the feature selector it has state being returned as undefined.

Reproduction is also provided there, but I'll link again for ease of use. https://stackblitz.com/edit/angular-kinkha

Asking for: `routerstate.state.url`
Evaluates to: `undefined.state.url`

Hence the error: `Cannot read property 'state' of undefined`

**Comment by blackholegalaxy** [comment] 2018-02-22 15:17
After review the reproduction is indeed the encountered problem.

**Comment by brandonroberts** [comment] 2018-02-23 04:19
@miniplus @blackholegalaxy my response is still the same. The `router` state will be undefined until an initial navigation happens. If you want to guard against this, you can provide an `initialState` for the `router` state.

**Comment by MattiJarvinen-BA** [comment] 2018-02-23 09:29
@brandonroberts hm... but if the initial state is anything other than what you added there everything breaks.

https://stackblitz.com/edit/ngrx-router-reducer-initial-state

Initial state set to SSR style to match url below everything breaks.
```json
{
  "state": {
    "url": "/users/1",
    "params": { "id": "1" },
    "queryParams": {}
  },
  "navigationId": 0
}
```
https://ngrx-router-reducer-initial-state.stackblitz.io/users/1

With initial state below everything works as expected.
```json 
{
  "state": {
    "url": "/",
    "params": {},
    "queryParams": {}
  },
  "navigationId": 0
}
```

Is there a bug in my code or is the router-store giving back references to the same object in some cases and by doing so breaking memoized selectors?

**Comment by blackholegalaxy** [comment] 2018-02-23 13:28
How to give this initialState for routerStore? Since everything seems handled through the lib. What is the proper way to override this. For example, a good thing could be to register the current activated route as initial state. The initial route should not be the first route you navigate to. But the actual first loaded route.

I think ngrx router-store should init at load and detect the current route from Angular router. Because for example the initial state can vary. If you load the app from "root" or if you deeplink in a sub route...

**Comment by brandonroberts** [comment] 2018-03-01 13:34
@blackholegalaxy You provide initial state for router-store using the `window.location.pathname` to give you the current URL.

```ts
    StoreModule.forRoot(reducers, {
      metaReducers: [],
      initialState: {
        router: {
          "state": {
            "url": "/",
            "params": {},
            "queryParams": {}
          },
          "navigationId": 0
        }
      }
    }),
```

@MattiJarvinen-BA The issue you are having when using SSR is a bug that you've already filed. I will look into it soon.

**Comment by blackholegalaxy** [comment] 2018-03-01 21:30
Hi @brandonroberts thanks about that. So there is now way for routerStore to initialize in sync with Angular router state?

**Comment by brandonroberts** [comment] 2018-03-09 02:25
@blackholegalaxy no, because the `RouterState` hasn't been compiled at application bootstrap. The `ROUTER_NAVIGATION` dispatches the routerState to the store at the earliest possible point already.

**Closed by brandonroberts** 2018-03-09 02:25 UTC
Labels: Needs Reproduction

**Comment by jwa107** [comment] 2018-04-11 16:55
I think it's weird that the CustomSerializer runs (and contains all the proper information) before the selector gets called but the state is still null. Where does this information end up then, if not in the router store?

Initial state is nice and all, but I'm populating a header on my page based on the URL, which I'm trying to extract with the router state. Something I couldn't handle through the initial state.

**Comment by JeffryGonzalez** [comment] 2019-12-17 22:38
Leaving a comment in case someone ends up here - had a similar problem. The custom serializer in the original issue:

```
export class CustomRouterStateSerializer
  implements fromRouter.RouterStateSerializer<RouterStateUrl> {
  serialize(routerState: RouterStateSnapshot): RouterStateUrl {
    let route = routerState.root;

    while (route.firstChild) {
      route = route.firstChild;
    }

    const { url, root: { queryParams } } = routerState;
    const { params } = route;

    return { url, params, queryParams };
  }
}
```
doesn't expose a `root` property on the result, and the selectors need that/assume that. Just replacing the custom serializer with the minimal made it go away for me.

**Comment by PuffPastry** [comment] 2020-07-09 12:58
I fixed the issue giving by passing the router options with `{initialNavigation: 'enabled'}`

**Comment by prewk** [comment] 2021-12-09 12:37
Perhaps related?

When we lazy-load routes - and store features - we end up with a situation where the router-store state  is undefined long enough for our selectors to crash. Yet `getSelectors().selectUrl()` is typed with `string`? It seems that type cannot be trusted. It evidently is `undefined` sometimes. Should it be changed?

**Comment by light9** [comment] 2021-12-11 22:02
Эх авч Бирме жюри  иыя г  и где ссмь

**Comment by adlion** [comment] 2022-07-31 08:26
In my case  I will get state undefined when calling the selector or AppComponent.
If I ask for it inside one of route components there is no error.
Also the solution @PuffPastry  mentioned works for AppComponent but it will cause some issues with guards and resolvers.
