### ISSUE TITLE
Documentation/Examples Request

### ISSUE THREAD

**Issue by Max-Lev** [ngrx/platform#715] opened 2018-01-13 15:38 UTC
Hi All,

first of all i wanted to say that you are doing a great job that helps develop a better apps and us to be a better developers.

Is it possible to add some **documentations and code examples** that will be attached with installed packages?

I think it will be much more clear and easier to learn new Issues and follow with a concepts, if it documented also as part of installed packages instead of trying to understand what is the context from separated topics/issues and they appear today. 
There is a lot of moving parts that represent different levels of experience that hard to grasp, and might be more clear if will be represented width a wider context.

Tnx.

**Comment by peterbsmith2** [comment] 2018-01-13 19:38
Does #692 speak to what you're looking for?

**Comment by brandonroberts** [comment] 2018-01-16 02:54
Closing as a duplicate of #692

**Closed by brandonroberts** 2018-01-16 02:54 UTC
