### ISSUE TITLE
Generate NGRX Store from Angular CLI 6.x

### ISSUE THREAD

**Issue by Max-Lev** [ngrx/platform#1108] opened 2018-06-02 19:40 UTC
Expected behavior:
Generate NGRX Store: cannot generate ngrx store width reducers and actions by runing following command:
ng generate store State --root --module app.module.ts --collection @ngrx/schematics

Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular CLI: 6.0.5
Node: 8.9.4
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cli                      6.0.5
@ngtools/webpack                  6.0.5
@schematics/angular               0.7.0-beta.1
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

Result:
Schematic "store" not found in collection "@schematics/angular".
Error: Schematic "store" not found in collection "@schematics/angular".

**Comment by brandonroberts** [comment] 2018-06-02 19:44
Duplicate of #1091. See here https://github.com/ngrx/platform/issues/1091#issuecomment-392026213

**Closed by brandonroberts** 2018-06-02 19:44 UTC
