### ISSUE TITLE
EntityAdapter upsertMany inserts `id` property into entity object that wasn't there before

### ISSUE THREAD

**Issue by ychaikin** [ngrx/platform#993] opened 2018-04-25 00:01 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
When using upsertMany, each `entity` object in the `entities` gets an `id` property.

## Expected behavior:
Leave the original (model) object as is.

## Minimal reproduction of the problem with instructions:
```
const tasks = action.tasks;
const updateTasks = tasks.reduce<Update<Task>[]>((updateAccum, task) => {
  updateAccum.push({id: task.taskId, changes: task });
  return updateAccum;
}, []);
return {
  ...taskEntityAdapter.upsertMany(updateTasks, state)

);
```
As you can see, the `id` of the `Task` object is `taskId`, not `id`. However, after the `upsertMany` call, the `entities` object has `Task`s where each one has an `id` property.

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome, MacOS, node v6.9.4, ngrx 5.2.0

**Comment by tdeschryver** [comment] 2018-04-25 05:59
duplicate of #817 ?

**Comment by ychaikin** [comment] 2018-04-25 06:55
@tdeschryver I saw #817 and I am not sure. The cause might be the same, but the behavior described there is different. There, it overrides the value in `id` (as far as I understand). In this one, it seems to be inserting it.

Again, that may be caused by the same thing though.

**Comment by tdeschryver** [comment] 2018-04-26 19:51
@ychaikin to be 100% sure, I've re-created your case and I believe the fix for #817 should also fix your case.

```
interface Person {
  name: string;
  ssn: string;
}

it('should do not create an id property', () => {
  const adapter = createEntityAdapter({
    selectId: (person: Person) => person.ssn,
  });

  const s1 = adapter.upsertOne(
    { name: 'Tim', ssn: '001' },
    { ids: [], entities: {} }
  );
  const s2 = adapter.upsertMany(
    [{ name: 'Bob', ssn: '001' }, { name: 'Joey', ssn: '002' }],
    s1
  );

  expect(s2).toEqual({
    ids: ['001', '002'],
    entities: {
      '001': { name: 'Bob', ssn: '001' },
      '002': { name: 'Joey', ssn: '002' },
    },
  });
});
```

**Comment by ychaikin** [comment] 2018-04-26 20:30
@tdeschryver Thank you very much!

Do I understand correctly that this fix is planned to appear in v7 of NGRX? Version 5.x+ and 6.0 won't get it yet?

**Comment by tdeschryver** [comment] 2018-04-26 20:32
@ychaikin It's shipped with v6-beta.0 - [Changelog](https://github.com/ngrx/platform/blob/master/CHANGELOG.md#600-beta0-2018-03-31)

**Comment by ychaikin** [comment] 2018-04-26 20:35
@tdeschryver Thank you! I'll let you close this issue whenever you see fit.

Thanks again!!!

**Closed** 2018-04-27 12:31 UTC
