### ISSUE TITLE
States that are instances of native Map are not presented correctly

### ISSUE THREAD

**Issue by david2tm** [ngrx/platform#2810] opened 2020-12-08 10:33 UTC
I have a state which is native Map (eg `new Map()`)
In Redux dev tool tab, it is shown as empty object, although works perfectly and logged fine in console.

## Minimal reproduction of the bug/regression with instructions:
```

export const initialState: Map<string, any> = new Map();

const _theReducer = createReducer(
  initialState,
  on(
    myAction,
    (state, { key, value }) => new Map(state.set(key, value))
  )
)
```

## Expected behavior:

Dev Tools should be able to show Map

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Latest

## Other information:

Looks relevant: https://github.com/zalmoxisus/redux-devtools-extension/issues/461

**Comment by david-shortman** [comment] 2020-12-12 01:03
This appears to be an issue in the redux devtools extension, not in the NgRx's `store-devtools` lib. Looking through the latter lib's spec, it look like nothing special is done to communicate a value's type to the devtools. The store value is merely passed to it, so however it displays is the devtools responsibility.

**Comment by brandonroberts** [comment] 2020-12-12 01:37
Duplicate of https://github.com/ngrx/platform/issues/632

**Closed by brandonroberts** 2020-12-12 01:37 UTC

**Comment by jdavault** [comment] 2023-11-01 22:27
import { legacy_createStore as createStore, applyMiddleware } from "redux";
import reducers, { initialState } from "./reducers";
import thunkMiddleware from "redux-thunk";
import { composeWithDevTools } from "@redux-devtools/extension";

const composeEnhancers = composeWithDevTools({ serialize: true });

export const store = createStore(
  reducers,
  initialState,
  composeEnhancers(applyMiddleware(thunkMiddleware))
);

//WORKED FOR ME ....
