### ISSUE TITLE
ComponentStore effect: type of emitted value is unknown

### ISSUE THREAD

**Issue by spierala** [ngrx/platform#3458] opened 2022-06-15 20:29 UTC
### Minimal reproduction of the bug/regression with instructions

Creating an effect like this: 

```
test = this.effect<string>((trigger$: Observable<string>) =>
    trigger$.pipe(
      tap((v) => {
        const stringValue: string = v; // TS error: Type 'unknown' is not assignable to type 'string'.(2322)
        console.log(stringValue);
      })
    )
  );
```
TS does not know that `v` is of type `string`. 

https://stackblitz.com/edit/angular-ivy-vcygbf?file=src/app/a-store.service.ts

It happens when **not** using tsconfig compilerOptions `"strict": true`.

At least `"strictFunctionTypes": true` is required in the compilerOptions to let the typing work correctly.  

### Expected behaviour

TS should know the type of the emitted value also when not using `"strict": true` or `"strictFunctionTypes": true` in the tsconfig compilerOptions.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Comp Store: 13.2
Angular: 14.0.2

### Other information

StackBlitz does not use `"strict": true` or `"strictFunctionTypes": true`.

Projects which started with an older Angular version might still not use `"strict": true`.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment] 2022-06-16 15:34
Duplicate of #3217

**Closed by timdeschryver** 2022-06-16 15:34 UTC
Labels: bug
