### ISSUE TITLE
ngrx feature state in an Angular library results in: Function calls are not supported in decorators but 'StoreModule' was called.

### ISSUE THREAD

**Issue by fransdeboer** [ngrx/platform#2768] opened 2020-11-01 16:12 UTC
## Minimal reproduction of the bug/regression with instructions:

1. clone the project from https://github.com/fransdeboer/swapi-demo.git
2. npm install
3. ng build swapi-lib --prod

Building the library with the View Engine compiler doesn't succeed.
```
ERROR: Error during template compile of 'SwapiLibModule'
  Function calls are not supported in decorators but 'StoreModule' was called.

An unhandled exception occurred: Error during template compile of 'SwapiLibModule'
  Function calls are not supported in decorators but 'StoreModule' was called.
```

## Expected behavior:
Expected that is possible to build the Angular library with the View Engine compiler without errors.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
Angular 10.2.0
ngrx 10.0.1
node 12.16.2

## Other information:
Building this library with the Ivy compiler (`ng build swapi-lib`), works without any problems. However at this time it is not allowed to push packages compiled by Ivy to NPM, also see the Angular site at https://angular.io/guide/creating-libraries#publishing-your-library.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by brandonroberts** [comment] 2020-11-01 20:22
This seems like an upstream issue, as we haven't changed anything about how compilation happens with ViewEngine. If you change `skipTemplateCodegen` to `false` in the `projects/swapi-lib/tsconfig.lib.json` it builds successfully with `ng build swapi-lib --prod`.

**Comment by brandonroberts** [comment] 2020-11-01 20:30
Closing as a duplicate of https://github.com/ngrx/platform/issues/2655

**Closed by brandonroberts** 2020-11-01 20:30 UTC

**Comment by MichaliEverson** [comment] 2020-11-02 20:02
Why have a swap done to begin with unless u are using for security reasons
such as a VNC render to display other then what the hacker searched for

(KiwiBox)

**Comment by pandaiiz** [comment] 2020-11-07 06:10
I have the same problem when i run `ng add @ngrx/store`, and i try to restart the Angular project then these mistakes disappear
