### ISSUE TITLE
@ngrx/entity add setOne (replaceOne?) method

### ISSUE THREAD

**Issue by dmytro-gokun** [ngrx/platform#2369] opened 2020-02-11 17:07 UTC
Currently, the only way to replace an item is by using upsertOne. That does not work well with 'undefined' though (which is the case when the backend omits nulls when serializing to JSON). For example, i have an entity in the collection: {id: 1, name: 'foo', note: 'lorem ipsum'}. I want to replace it with {id: 1, name: 'foo'}. Obviously, upsertOne does not do the job well. Since the object  is already there, it attempts to perform an update, thus treating the new object as a patch and leaving 'note' value unchanged. So, a new method 'setOne' is needed here.

## Describe any alternatives/workarounds you're currently using

removeOne/addOne does the trick, but is not very efficient.

## If accepted, I would be willing to submit a PR for this feature

[X ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by AdditionAddict** [comment] 2020-02-11 22:56
Note `upsertOne` treats the passed entity as an update as does `@ngrx/entity`. In fact, previous interface was that the payload was an `Update<T>`. I'd say this is intended behaviour which has been addressed in previous issues - https://github.com/ngrx/platform/issues/1604 (closed) https://github.com/ngrx/platform/issues/2061 (open)

I think upsertOne should have `Partial <T>` though.

Also every dictionary definition I've found has upsert means insert or update.
I think replaceOne is closer to the equivalent database term though I'd still vote for setOne if approved

**Comment by dmytro-gokun** [comment] 2020-02-12 06:44
@AdditionAddict I do not think there is any issue with `upsertOne`. It behaves in accordance with `ngrx`'s update semantic. All is well here. It's just that it does not cover all possible scenarios. That's why i think `setOne` is needed.

As to name, i chose `setOne` to follow the pattern which is already here after a recent rename of `addAll` to `setAll`: https://github.com/ngrx/platform/pull/2347

**Comment by AdditionAddict** [comment] 2020-02-12 07:22
@dmytro-gokun I agree

**Comment by timdeschryver** [comment] 2020-02-16 10:14
I think adding a `setOne` makes sense, now that we have `setAll`.
Also, this is an issue that comes up regurarly (as pointed out)

**Comment by dmytro-gokun** [comment] 2020-02-16 15:41
@timdeschryver Great, i'll work on a PR

**Comment by timdeschryver** [comment] 2020-02-16 16:07
@dmytro-gokun can you hold it off for a bit?
I want to hear @brandonroberts 's thought about this first.

**Comment by dmytro-gokun** [comment] 2020-02-16 16:32
@timdeschryver sure

**Comment by brandonroberts** [comment] 2020-02-16 17:11
Sounds good to me

**Comment by dalu** [comment] 2020-02-21 12:29
will the cache updating method names be changed as well then or will they remain the same?
addOneToCache
updateOneInCache
removeOneFromCache
and others

**Closed** 2020-02-27 14:13 UTC
Labels: Project: Entity, enhancement
