### ISSUE TITLE
State is not initialized when using spread operator in AOT

### ISSUE THREAD

**Issue by Kimserey** [ngrx/platform#2047] opened 2019-08-07 09:03 UTC
## Minimal reproduction of the bug/regression with instructions:

When reducers are provided to `StoreModule.forRoot` via spread operator, the state is not initialized in AOT.

```
StoreModule.forRoot(fromRoot.reducers), <- OK
StoreModule.forRoot({ ...fromRoot.reducers }), <- Not OK :(
```

https://github.com/Kimserey/ngrx-reducer-test/blob/8371798a5038d880fe4adb5c8cfd1efb76ffe908/src/app/app.module.ts#L21

Serve with AOT `ng serve --aot` and observe the browser error:

```
core.js:7187 ERROR TypeError: Cannot read property 'message' of undefined
    at getMessage (hello.reducer.ts:32)
    at store.js:944
    at memoized (store.js:859)
    at defaultStateFn (store.js:899)
    at store.js:953
    at memoized (store.js:859)
    at MapSubscriber.project (store.js:778)
    at MapSubscriber._next (map.js:29)
    at MapSubscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
```

Without spread operator, the state is initialized properly.

## Expected behavior:

I expect `StoreModule.forRoot(fromRoot.reducers)` and `StoreModule.forRoot({ ...fromRoot.reducers })` to behave the same way and have the state initialized.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

- NgRx: 8.2.0
- Angular: 8.0.1
- Browser: Chrome Version 75.0.3770.80

**Comment by timdeschryver** [comment] 2019-08-07 14:00
What's the reason you want to use the spread operator here?
I think this is out of our (NgRx's) hands.

**Comment by Kimserey** [comment] 2019-08-07 17:36
> What's the reason you want to use the spread operator here?
I was using the spread operator to combine the router reducer with my current reducers without really thinking whether that was a good idea or not.

```
export const reducers: ActionReducerMap<State> = {
  ...myReducers,
  routerReducer: fromRouter.reducer,
};
```

I didn't expect the spread operator to yield this behaviour when building with AOT and couldn't find any explanation.

> I think this is out of our (NgRx's) hands.
Would you know the reason, and/or the correlation, with the state not being initialised?

Within an injection token factory method, the spread operator can be used and states get initialised properly.

**Comment by SerkanSipahi** [comment] 2019-08-12 13:28
@Kimserey i think your issue is related to Angular Ivy, see: https://github.com/angular/angular/issues/29835#issuecomment-488641027

**Comment by brandonroberts** [comment] 2019-10-01 23:40
Closing as not a bug with NgRx

**Closed by brandonroberts** 2019-10-01 23:40 UTC
Labels: Project: Store
