### ISSUE TITLE
[Feature Request] Decorators for components

### ISSUE THREAD

**Issue by spock123** [ngrx/platform#984] opened 2018-04-23 10:58 UTC
Would it be an idea to add some decorators which make it possible to avoid boilerplate stuff?

Specifically I'm thinking of a @Select() decorator which connects to the store and creates a component property observable with the part of the store requested in the arguments (or returned by a selector).

Angular-Redux uses such a decorator and it's great.
There are also 3rd party ngrx packages that provide the same (ngrx-utils), but I think it would be a great idea to have these as part of the ngrx/store platform.

Cheers

**Comment by brandonroberts** [comment] 2018-04-23 12:52
Duplicate of https://github.com/ngrx/platform/issues/416

**Closed by brandonroberts** 2018-04-23 12:52 UTC
