### ISSUE TITLE
ngrxLet type in template is wrong when using the as syntax

### ISSUE THREAD

**Issue by ArielGueta** [ngrx/platform#2779] opened 2020-11-10 05:17 UTC
## Minimal reproduction of the bug/regression with instructions:

Use the following code in Webstorm:

```ts
observableNumber$ = interval(1000);
```

```html
<ng-container *ngrxLet="observableNumber$ as n">
  {{ n }}
</ng-container>
```

The inferred type of `n` is `Observable<number>`:
![image](https://user-images.githubusercontent.com/20522870/98630837-ad67fc00-2324-11eb-94ea-3f60c00453cc.png)

When using the `let` syntax it works well:
![image](https://user-images.githubusercontent.com/20522870/98630847-b658cd80-2324-11eb-805f-58ea5fcf2716.png)

## Expected behavior:
The type should be `number` and not `Observable<number>` when using the `as` syntax.

**Comment by timdeschryver** [comment] 2020-11-10 09:25
Closing this, duplicate of #2691

**Closed by timdeschryver** 2020-11-10 09:25 UTC
