### ISSUE TITLE
Add example of unit testing selector which uses props

### ISSUE THREAD

**Issue by hegedis-andor** [ngrx/platform#2476] opened 2020-04-06 07:07 UTC
## Other information:
https://ngrx.io/guide/store/testing#testing-selectors
It is not clear how to test ngrx selector which uses props

## I would be willing to submit a PR for the docs :heart:

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

**Comment by timdeschryver** [comment] 2020-04-06 07:23
I think this is a duplicate of #2176
If this is not the case, feel free to re-open the issue

**Closed by timdeschryver** 2020-04-06 07:23 UTC
