### ISSUE TITLE
@ngrx/store, @ngrx/data Detected unserializable action at "payload.data.error" (DataServiceError)

### ISSUE THREAD

**Issue by KrzysztofKarol** [ngrx/platform#1993] opened 2019-07-03 15:02 UTC
## Minimal reproduction of the bug/regression with instructions:

https://stackblitz.com/edit/data-service-error?file=src%2Fapp%2Fpost-data.service.ts

## Expected behavior:

DataServiceError is somehow serializable or I can catch it and serialize on my own

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

@angular/common: 8.1.0
@angular/compiler: 8.1.0
@angular/core: 8.1.0
@angular/forms: 8.1.0
@angular/platform-browser: 8.1.0
@angular/platform-browser-dynamic: 8.1.0
@angular/router: 8.1.0
@ngrx/data: 8.0.1
@ngrx/effects: 8.0.1
@ngrx/entity: 8.0.1
@ngrx/store: 8.0.1
@ngrx/store-devtools: 8.0.1

## Other information:
It's thrown here:
https://github.com/ngrx/platform/blob/c59c21150293ad2c9ee5b03782b4fda7ce9f15c7/modules/store/src/meta-reducers/serialization_reducer.ts#L84

Should it be catched in custom data service?
https://stackblitz.com/edit/data-service-error-workaround?file=src/app/post-data.service.ts

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

Understanding the flow is not ease but I'm beginning to see the light.

**Comment by peimelo** [comment] 2019-07-23 22:42
Hi, I haven't used `@ngrx/data` yet, but when I used `@ngrx/effects` I had the same problem:

````
loadWeights$ = createEffect(() =>
  this.actions$.pipe(
    ofType(WeightsActions.loadWeights),
    mergeMap(({ pageIndex }) =>
      this.weightsService.getAll(pageIndex).pipe(
        map(weightResponse =>
          WeightsActions.loadWeightsSuccess({ weightResponse })
        ),
        catchError(error => {
          return of(WeightsActions.loadWeightsFailure({ error })); <= ERROR
        })
      )
    )
  )
);
````
`ERROR Error: Detected unserializable action at "error"`

I resolved by returning the `error.message` instead of `error`:

````
loadWeights$ = createEffect(() =>
  this.actions$.pipe(
    ofType(WeightsActions.loadWeights),
    mergeMap(({ pageIndex }) =>
      this.weightsService.getAll(pageIndex).pipe(
        map(weightResponse =>
          WeightsActions.loadWeightsSuccess({ weightResponse })
        ),
        catchError(error => {
          return of(WeightsActions.loadWeightsFailure({ error: error.message })); <= SOLVED
        })
      )
    )
  )
);
````

**Comment by KrzysztofKarol** [comment] 2019-07-23 23:14
Thank you, @peimelo!
I'll try it today.

**Comment by KrzysztofKarol** [comment] 2019-07-24 16:28
Yes, somethink like this (https://stackblitz.com/edit/data-service-error-workaround?file=src%2Fapp%2Fpost-data.service.ts) can work but it's better to handle it in @ngrx

**Comment by vicki2576** [comment] 2019-07-25 23:59
Thank you

A-"74=HiwB8-^=d

**Comment by vicki2576** [comment] 2019-07-25 23:59
Thank you

A-"74=HiwB8-^=d

**Comment by KrzysztofKarol** [comment] 2019-08-14 17:09
Setting `runtimeChecks` to
```
strictStateSerializability: false,
strictActionSerializability: false,
```
"solves" the problem.

**Comment by andrsbrbs** [comment] 2019-11-14 14:45
> Yes, somethink like this (https://stackblitz.com/edit/data-service-error-workaround?file=src%2Fapp%2Fpost-data.service.ts) can work but it's better to handle it in @ngrx

How do I handle it via NgRx? I'm using @ngrx/data with a custom API url, and got the same error until I added the catchError operator to the service's request.

**Comment by jemerald** [comment] 2019-11-24 23:53
> Setting `runtimeChecks` to
> 
> ```
> strictActionSerializability: false,
> ```
> 
> "solves" the problem.

This only hides the problem, which is to do with `@ngrx/data` trying to pass the `HttpErrorResponse` object in the action payload. The `HttpErrorResponse` object contains function definitions that cannot be serialized.

`@ngrx/data` should either map the `HttpErrorResponse` to simple object, or provide an override for HTTP error response mapping, or both.

**Comment by luchillo17** [comment] 2020-02-13 04:36
@peimelo I'm using `@ngrx/data` and getting control of the error is harder here, though I do understand the issue is with the error itself not being serializable at some point.

I was going to override the DefaultPersistenceResultHandler to cast the error into a serializable object to work around this issue, however, it seems like it's part of the architecture to transform the error (which I'm throwing in an interceptor as a string) to 
a non-serializable `DataServiceError`.

https://github.com/ngrx/platform/blob/master/modules/data/src/dataservices/persistence-result-handler.service.ts#L51-L71

If that's the case, can't find where am I supposed to override, looks to me that transforming into `DataServiceError` was intentional and it's a bug where it wasn't transformed back into serializable error somewhere else.

**Comment by brandonroberts** [comment] 2020-02-13 13:00
We've added a feature to ignore runtime checks for actions that originate from NgRx libraries that should help with this. See the PR here https://github.com/ngrx/platform/pull/2351

**Comment by luchillo17** [comment] 2020-02-13 13:16
I see, so it will be fixed in next release, any ETA on it? will it be for angular 9 up?

**Comment by brandonroberts** [comment] 2020-02-13 13:19
Soon-ish 😉. It will be for Angular 9 up, as that's our official support policy on major releases.

**Comment by brandonroberts** [comment] 2020-02-26 02:32
Closing as resolved

**Closed by brandonroberts** 2020-02-26 02:32 UTC
Labels: Project: Data

**Comment by luchillo17** [comment] 2020-03-12 01:55
@brandonroberts I've just updated to NG9 and the error keeps happening, wasn't the fix deployed with version 9.0.0?

**Comment by AdditionAddict** [comment] 2020-03-13 15:50
@luchillo17 please can you produce a reproduction in stackblitz or a github link

**Comment by luchillo17** [comment] 2020-03-14 19:02
Is there a base StackBlitz link from where to start?

**Comment by zendu** [comment] 2020-06-12 07:17
I am using ngrx 9.1.0 and I see this error.

**Comment by ivdim1992** [comment] 2020-07-12 13:52
same here.. let explain what happened
1. export const signInUserFailure = createAction(
  '[Authentication Module] Sign In User Failure',
  props<{ error: HttpErrorResponse }>()
); -> that is my error handler action

2.  public readonly signInUser$ = createEffect(() =>
    this.actions$.pipe(
      ofType(AuthActions.signInUser),
      exhaustMap(({ data }) =>
        this.authService.signIn(data).pipe(
          map((user) => AuthActions.signInUserSuccess({ user })),
          catchError((error) => of(AuthActions.signInUserFailure({ error })))
        )
      )
    )
  ); --> that's my effect 
-- here on the sign in I was receiving this specific error, when I changed the action to receive props<{error:{message: string}}>() --> the error disappeared...
3. When I signed in and after that log out and return to the previous code with the previous action the error did not show again.. which is sooo strange can not understand what actually caused it

**Comment by SanteriMagister** [comment] 2021-03-09 13:08
This still happens for me in the current version on NgRx Data. Has anyone found a workaround?

**Comment by cbejensen** [comment] 2021-05-28 19:06
This error is still happening to me as well.

Here's a bare-bones reproduction: https://stackblitz.com/edit/angular-ivy-sxycrg?file=src/app/app.module.ts

**Comment by krema** [comment] 2022-12-18 21:52
> This still happens to me in the current version on NgRx Data. Has anyone found a workaround?

{ error: JSON.parse(JSON.stringify(error)) })
