### ISSUE TITLE
ngrx.io server is down

### ISSUE THREAD

**Issue by imukeshsoni** [ngrx/platform#4363] opened 2024-05-28 09:24 UTC
### Information

I was trying to read the documentation but the page is not available and I'm seeing 'REQUEST FOR DOCUMENT FAILED.' with this screen

<img width="1509" alt="Screenshot 2024-05-28 at 2 53 11 PM" src="https://github.com/ngrx/platform/assets/28658405/528c0760-e163-4a20-b6f9-4af034404048">

this is how network tab looks like:
<img width="1322" alt="Screenshot 2024-05-28 at 2 54 03 PM" src="https://github.com/ngrx/platform/assets/28658405/27464e7a-d3a9-480f-b1fe-cf31282dc0cf">

### Documentation page

https://ngrx.io/guide/store/why

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by timdeschryver** [comment] 2024-05-28 11:07
Thanks for letting us know, this is a duplicate of #4362

**Closed by timdeschryver** 2024-05-28 11:07 UTC
Labels: Comp: Docs
