### ISSUE TITLE
Automatic type checking for the state that is returned by the on function in createReducer 

### ISSUE THREAD

**Issue by StretchTitan** [ngrx/platform#2412] opened 2020-02-25 14:51 UTC
It would be great to have the state type that is supplied to createReducer function enhanced to guard against additional properties being added. Here is an example where the state becomes different than the AccountState model but it is not caught and builds/runs fine.

```
import { Action, createReducer, on } from '@ngrx/store';
import { updateAccountBalance } from './account.actions';

export interface AccountState {
  accountBalance: number;
  name: string,
}

export const accountInitialState: AccountState = {
  accountBalance: 2000,
  name: 'StretchTitan',
};

const reducer = createReducer(
  accountInitialState,
  on(updateAccountBalance, (state, { amountChange }) => ({
    ...state,
    accountBalance: state.accountBalance + amountChange,
    newParam: 'test',
  })),
);

export function accountReducer(state: AccountState | undefined, action: Action) {
  return reducer(state, action);
}
```

## Describe any alternatives/workarounds you're currently using
The only way to get the strong typing guard against property addition is to add the return state to the function in the 2nd param of the on function.
```
import { Action, createReducer, on } from '@ngrx/store';
import { updateAccountBalance } from './account.actions';

export interface AccountState {
  accountBalance: number;
  name: string,
}

export const accountInitialState: AccountState = {
  accountBalance: 2000,
  name: 'StretchTitan',
};

const reducer = createReducer(
  accountInitialState,
  // Example of how to get strong typing applied to the state object that is returned
  on(updateAccountBalance, (state, { amountChange }): AccountState => ({
    ...state,
    accountBalance: state.accountBalance + amountChange,
    newParam: 'test',
  })),
);

export function accountReducer(state: AccountState | undefined, action: Action) {
  return reducer(state, action);
}
```
## Other information:
This isn't a critical enhancement but the old switch case statement code handled this scenario and it would be great to bring this back in NgRx v8.

## If accepted, I would be willing to submit a PR for this feature
I will not be able to submit this anytime soon but I am willing to help tackle this enhancement.

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2020-02-25 17:25
This should work if you explicitly provide a generic for the reducer:

```ts
const reducer = createReducer<AccountState>(
  accountInitialState,
  on(updateAccountBalance, (state, { amountChange }) => ({
    ...state,
    accountBalance: state.accountBalance + amountChange,
    newParam: 'test',
  })),
);
```

**Comment by timdeschryver** [comment] 2020-02-25 18:16
Oh, you're right. I always thought that would catch these.
But now I think of it, I remember Alex mentioning you have to do it like the second example you provided.

**Comment by Andrei0872** [comment] 2020-03-02 21:36
Hello @StretchTitan, it seems to be working fine [here](https://stackblitz.com/edit/ngrx-8-playground-msd8bk?file=src%2Fapp%2Fstore%2Fcounter%2Fcounter.reducer.ts). The extra prop is caught. 

Did I miss something?

**Comment by StretchTitan** [comment] 2020-03-02 21:41
Your example does work and it is applying the AccountState within the on function like I have it in my workaround example. I brought this issue up because I think it would be a nice enhancement to have the State type automatically applied to the on functions since we are supplying the state to the createReducer function.

**Comment by Andrei0872** [comment] 2020-03-03 09:00
I see. I think I found a way to solve this without explicitly typing the **on-reducer**.

I modified the `on`'s signature like this:

```ts
export function on<
  C1 extends ActionCreator,
  S,
  R extends S,
  F extends (s: S, a: C1) => R, // Infer the function's types
  T = keyof ReturnType<F> extends keyof S ? true : false // Make sure it complies with the inferred state 'S'
  >(
  creator1: C1,
  reducer: F & (T extends true ? {} : 'Does not comply with S'),
): On<S>
```

A working example:

```ts
interface State {
  a: string;
  b: number;
}

const initState: State = {
  a: 'A',
  b: 1,
};

const add = createAction('add');

const fooReducer = createReducer(
  initState,
  on(add, (s, a) => ({
    ...s,
    a: '123',
    b: s.b + 123,
    c: true, // Error
  })),
);
```

**Comment by StretchTitan** [comment] 2020-03-05 14:36
Thanks for working on this enhancement @Andrei0872!

**Comment by timdeschryver** [comment] 2020-04-14 13:33
@Andrei0872 That seems to be what we're looking for.
@alex-okrushko, thoughts?

**Comment by alex-okrushko** [comment] 2020-04-19 18:49
Thanks @timdeschryver  and @Andrei0872 
I've been following this issue opened for Typescript for a while now: https://github.com/microsoft/TypeScript/issues/12936

The initial solution from TS team was to use the following:
```ts
type Exact<T> = {|
    [P in keyof T]: P[T]
|}
```

Another solution further down in the comments is:
```ts
type Exact<T, R> = T extends R
  ? R extends T
    ? T
    : never
  : never
```

We could experiment with those.

Some problems appear when `State` is a union or intersection of types. We should keep that in mind.

**Comment by Andrei0872** [comment] 2020-04-20 14:43
After spending some time on it, I realized that the problem is not the object's comparison, but inferring the return type of the reducer.

For example:
```typescript
function on<
  A extends Action,
  S,
  R extends S,
  F extends (s: S, a: A) => R,
>(a: A, r: F, foo: ReturnType<F>): On<S> {
  return undefined!;
}

function inferStateType<S> (state: S, ...reducers: On<S>[]) { }
```

Now I'm not sure why `foo`'s type is not properly determined(or am I missing something?):

```typescript
interface AppState {
  user: {
    name: string;
    age: number;
  },
  booleanOption: boolean;
}

const s: AppState = {
  user: {
    name: 'john',
    age: 123,
  },
  booleanOption: true,
};

inferStateType(
  s,
  on(testAction, (s, a) => ({ ...s, test: 123 }),  { /* only `booleanOption` and `user` are required, `test` is not  */ }),
)
```

However, if you hover over the arrow from `(s, a) => ...`, it can be seen that the return type is properly inferred, which confuses me. I haven't able to find a solution for this.

Another issue might be that my current solution and the one which uses `Exact` don't work for nested properties.

[_TypeScript Playground_](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQEEkRAezAHgBVUoAPaMAEwGdVqIZwBzVAXjoeYD5UBvVGFASU8AGwCeqCOIAOUAFypiAXwDcwUJFiIUqAEpRKAVxQx8AZQA0GEuShVavZWz7KevYKlQAKaoquoCIroAJT+6soa4NDwyGgA8gTm7p6BWLhgfhyMYEwA2gC66l4wigbGphZcwJHAAPR1bKzNLa1t7R3N9Y3m8QAyAKqEAJLxAHKoAIyoALSoYDgQqADuODAA1swrIBAAFvNQ9IaoOABGAFZQWNTdqHBGYOl4JwS3Xui2FDQYT2CWb6grAC9J97N8gQ0vKgAGKghw+LIBIIYEJsHh6f6QrjeZHoaylGGoABkPnWUHEODg+igECMMDAhFkUHw0J4ZC+tDJFKp5lQAH5XKhFGAoAA3WAhMKoRJVPgAwS0+moB6UKBwcCGACE6khtUhvUGI3GqAATLN5osBEJKJJxDTgNI5KgAKKkZAQIjWPQ8djEdlg2h6VICkH++GEVJeAURqFCg7imCpYVi2Aae6PbDPPD4VIfMPfTCZv6pIFeUN2eGlwn52i+fzWXGo1jo-7Y3H4xTQ6xwHA4Mo0ukMpksrhSmXJOUlAdKlVqjWUbU1W6dFer1pph6-VDgOCwcwQBDQRlyWW+A-QeuoAB0N8EFVgWXHXEKqP4tWi2jiGBkMn3h7QHheEY1CwIogFQmACAALYKNkzDFFCCBMLBYBGFBpywAhyj-F4py9qIQhgPEMhFooeE4ARCBgBEGhIHg9B0MEP5-tALjgcBoGThB0GwQA5OcOC7GAvE4YhyGKJMJoAMyidhqTkZRREkRkigMEYUD-GotH0Us0D0IWGRsVITKKLxPY4LxqBaZou4wCxUDHlA3ipNQol4N4ekQAZeDWL4DZNjw3j8DeV6uVIhwQBJ0lWSE1j8DF1iQp5WwAAbmSlGipJC+qTFljTuZ53l-Ai-loj4wU3mFHEEvwSGwZJUlWTFsWoJC8QANKKIgICiLQIBUgsSwIKIoioDIMA4HIMDYIcgSCNujyiEYqqUHlLweRFRW+WFCABeV16VdY1VgQdoVXtVDbiVM0XOMokqJY0HVrQVm2-NtpXNvtIVhYN6AjTgyyGAAErAsFqWgd0tW1nV3AgPU3F4kIvfpb0lYEe1BadYUKYRxGkVIMDqUdIE1Vj50k9Yv3-YDlAg4IXXDSBTWQw9MJw71dxrAcRyUGNE1TTNCOtflYAbSjRbvejZWY991g41ReMqQTRMWl51PA6DqmExpyokyd33k7AlOLH9ogAxr9Ow71EPNcLqAAOprOstCAyNnMwKrMwijzfOTTcIRAA).

**Comment by liesahead** [comment] 2020-06-26 10:06
Is this planned to be fixed? Also, my suggestion would be to slightly reimplement the `createAction` function. Instead of

```ts
export const MyAction = createAction('My Action', props<{ model: MyModel }>());
```

let's say it could be something like that

```ts
export const MyAction = createAction<{ model: MyModel }>('My Action');
```

**Comment by liesahead** [comment] 2020-06-26 10:08
Sorry, if it's not the right place to mention this, I'm just not sure it's worth creating a new issue. My suggestion would be to slightly reimplement the `createAction` function. Instead of

```ts
export const MyAction = createAction('My Action', props<{ model: MyModel }>());
```

let's say it could be something like that

```ts
export const MyAction = createAction<{ model: MyModel }>('My Action');
```

**Comment by brandonroberts** [comment] 2021-05-15 20:10
I believe this is resolved in the latest version. Closing this for now

**Closed by brandonroberts** 2021-05-15 20:10 UTC
Labels: Project: Store

**Comment by cpyle0819** [comment] 2021-07-02 12:45
@brandonroberts I'm still seeing this in 12.1

**Comment by pablomaurer** [comment] 2022-03-29 20:45
@brandonroberts still seeing this in 13.0.2

**Comment by sunio00000** [comment] 2023-12-13 09:18
i resolved this issue using generic type. 
```typescript
type Exact<T> = T extends object ? { [key in keyof T]?: T[key] } | { [key: string]: never } : never;

const reducer = createReducer<Exact<TState>>
```

Make reducer with `Exact<T>` above to find improper properties (but not 2-depth object properties not applied.)
