### ISSUE TITLE
Feature Selector

### ISSUE THREAD

**Issue by tamasfoldi** [ngrx/platform#41] opened 2017-06-16 16:17 UTC
Hi!

I'm trying to create a selector for my feature and I'm wondering what should be the most proper way to do it. Now I have a simple selector like this
`const getValues = (state: State) => state.values &&
  state.values;`

A wrapper feature selector like this:
`export const getValuesForFeatrue = (featureName: string) => createSelector(createFeatureSelector(name), getValues);`

And I can call this from my component:
`this.store.select(fromReducer.getValuesForFeatrue(this.config.featureName))`

It is working but dont think this is the best way to implement a feature selector. Any suggestions?

**Comment by robwormald** [comment] 2017-06-16 21:42
This is a really, really subjective question - There's no "right" or "best" answer, generally. :)

Personally, I don't see a lot of value in creating these kinds of selectors. It's what RxJS was designed to do. Ymmv.

I'm going to close this because it's not really an actionable issue. Try https://gitter.im/ngrx for discussion/help requests.

**Closed by robwormald** 2017-06-16 21:42 UTC
