### ISSUE TITLE
Time travel in Redux Dev Tools causes router-store to stop emitting ROUTER_NAVIGATION

### ISSUE THREAD

**Issue by mruf** [ngrx/platform#773] opened 2018-01-31 16:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The router-store stops emitting ROUTER_NAVIGATION actions after time traveling to an app state using the "Jump" button in the Redux Dev Tools.
The same behavior can be observed in my own app and the example app.

## Expected behavior:
1. Jump to a state in the Redux Dev Tools 
2. Jump back to the latest state
3. Navigation in the app should cause ROUTER_NAVIGATION actions to be emitted

## Minimal reproduction of the problem with instructions:
1. Install and run the [example app](git clone https://github.com/ngrx/platform.git) locally
2. Browse to http://localhost:4200 and open the Redux Dev Tools
3. Login with test/test
4. Open side bar and select 'Browse Books'
5. Verify in the Redux Dev Tools that several ROUTER_NAVIGATION actions have been emitted
6. Select the second to last ROUTER_NAVIGATION action in the Dev Tools and click "Jump"
7. Select the latest action in the Dev Tools and click "Jump"
8. Open the side bar and select 'My Collection'
9. No ROUTER_NAVIGATION actions are emitted anymore from now on when navigating in the app

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Chrome 63, Redux Dev Tools 2.15.1, Windows 10 64bit, Node 8.9.4
ngrx platform commit: a140fa90452c352443b79311eff12722267f8c00

**Comment by brandonroberts** [comment] 2018-02-13 03:23
Duplicate of #662

**Closed by brandonroberts** 2018-02-13 03:23 UTC
Labels: Project: Router Store, bug
