### ISSUE TITLE
Effects: extended/subclassed effects class not run

### ISSUE THREAD

**Issue by dummdidumm** [ngrx/platform#1234] opened 2018-08-06 22:20 UTC
## Minimal reproduction of the bug/regression with instructions:

When creating a subclass of an effect and adding it to the list of effects, it will not be run.

```
// Adding this base class to effects will run bla$
@Injectable()
export class ConfigurableBaseEffect {
  @Effect({ dispatch: false })
  bla$ = this.actions$.pipe(tap(() => console.log("responding to effect action")))

  constructor(protected actions$: Actions) {}
}

// Adding this extended class to effects will NOT run bla$
@Injectable()
export class EffectA extends ConfigurableBaseEffect {
  constructor(actions$: Actions) {
    console.log("inside constructor of EffectA");
    super(actions$);
  }
}
```

Reproduction: https://stackblitz.com/edit/angular-xxrdqg?file=src%2Fapp%2Fapp.module.ts

My guess is that it's because the effects metadata is added to prototype.constructor and the constructor is overwritten when the class is extended (https://github.com/ngrx/platform/blob/master/modules/effects/src/effects_metadata.ts).

This is a subtle yet critical bug in my opinion as this makes creating generic effects which are extended to have a specific behavior impossible.

## Expected behavior:

Subclassed effects work just fine.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular/Ngrx 6.x

## Other information:

Adding the metadata property to prototype instead of prototype.constructor could solve the issue.

## I would be willing to submit a PR to fix this issue

[x] Yes
[ ] No

**Comment by brandonroberts** [comment] 2018-08-06 22:43
Duplicate of https://github.com/ngrx/platform/issues/586. See https://github.com/ngrx/platform/pull/890 for reference

**Closed by brandonroberts** 2018-08-06 22:43 UTC

**Comment by dummdidumm** [comment] 2018-08-13 10:59
Just for information: Before [this commit](https://github.com/ngrx/platform/commit/e7ae8a228ee4338b6beac4baf0bba745fa32c917#diff-708a6e5fc1424e81075508aee61cb59f) subclassing effects without adding extra effects worked, now even that does no longer work. Reason "hasOwnProperty"-usage instead of direct access of the property.
