### ISSUE TITLE
Can't import lazy-loaded module's state from json using Redux DevTools

### ISSUE THREAD

**Issue by MasDevProject** [ngrx/platform#1326] opened 2018-09-09 15:35 UTC
I'm developing an application using Angular and ngrx with redux DevTools for Chrome. My application has also a lazy-loaded module and I configured it like this:

```
@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        RouterModule.forChild([
            { path: '', component: UserLazyHistoryComponent }
        ]),
        StoreModule.forFeature(moduleFeatureName, reducers),
        EffectsModule.forFeature([
            HistoryEffects
        ])
    ],
    declarations: [UserLazyHistoryComponent]
})
export class UserLazyHistoryModule { }
```

and this is my reducer index file:

```
export const moduleFeatureName = 'user-lazy-module';

export interface UserLazySate {
    history: fromHistory.HistoryState;
}

export const reducers = {
    history: fromHistory.reducer
};

export const selectHistoryModuleState = createFeatureSelector<UserLazySate>(moduleFeatureName);

export const selectHistory = createSelector(selectHistoryModuleState, s => s.history);
```

With this configuration everything works well but I noticed that when I export the state of the application (as a json) using the ReduxDevTools and than I upload it, the state of the lazy module is not loaded. It remains null.

If I start the application right in the state of the lazy-laoded module and then I import the json, it works, but if I start from the beginning of the app, then I import the json, using the time-slider, when I reach the lazy module the state is null (default).

## Expected behavior:

The state of lazy-loaded modules should be imported correctly from json.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
- "@angular/cli":"6.0.8"
- "@angular/common":"6.1.6"
- "@ngrx/router-store":"6.1.0"
- "@ngrx/store":"6.1.0"
- "@ngrx/store-devtools":"6.1.0"
- MacOs 10.13.6
- Chrome 69

**Comment by dummdidumm** [comment] 2018-09-10 07:27
Duplicate of #919 (which was closed, but is not really solved yet, @brandonroberts maybe you should reopen it).

**Comment by dummdidumm** [comment] 2018-09-10 12:49
#919 contains one specific use case which is not resolved yet, which explains the same problem of the issue which is reported here I think:
1. Be on a page where a lazy loaded module of some other page is not loaded yet
2. Import a JSON which, in the course of reapplying the actions, changes to the page of that lazy loaded module
3. -> Bug: Actions are reapplied to "old" reducers. There is no logic "oh, there is a page change which has a lazy loaded reducer, let's wait for it and then continue reapplying the actions".

Part of #919 was fixed through the "wait for update reducers initially", but this specific use case was not.

**Comment by SenthilKumaranC** [comment] 2019-11-13 07:17
I am introducing add state management layer in my official angular project  , I want to show a demo to team how we can replay actions by importing jsons , but facing the same issue.

I am planning to add deffered actions queue in root metareducer and execute those actions on lazy module load. But is there anyway to check those actions are already added to store or not. Do we have any  action collection to check incoming action present or not?

**Comment by dummdidumm** [comment] 2019-11-13 12:37
There is a "update reducers" action I think, which is called everytime a new reducer is added. If you load the app with devtools open you should see these actions. But this would be only a workaround on your side. To really fix this, we need to finish what was started in #955 .

**Comment by SenthilKumaranC** [comment] 2019-11-15 12:29
I can able to retain state now with lazy loading reducers but not using update reducers. I have maintained a deferred action collection , on module load ngOnit executing the action collection. For time being , this is ok for me.

One drawback is for each action call ,  there will be two failed action call and success action call while replaying.

**Closed** 2020-07-10 02:53 UTC
Labels: Project: Store Devtools
