### ISSUE TITLE
Broken typing for 'on' in reducer

### ISSUE THREAD

**Issue by bpanteleev** [ngrx/platform#3141] opened 2021-09-06 11:59 UTC
## Minimal reproduction of the bug/regression with instructions:

I have a reducer in my project:
const globalStateReducer = createReducer<IAppGlobalState>(...

And 'on's:

on(setTenor, (state, action) => ({
    ...state,
    notExistingProperty: 23,
  })),

And there is no typescript error for this 'notExistingProperty'.

See details by in StackBlitz https://stackblitz.com/edit/ngrx-seed-yli3pt?file=src%2Fapp%2Freducers%2Fcounter.reducer.ts

## Expected behavior:

There should be a typescript error

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx 12.4.0

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2021-09-06 16:24
Duplicate of #2412.
See [On Function Explicit Return Type (from the NgRx Linter)](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/main/docs/rules/on-function-explicit-return-type.md) for more info.

**Closed by timdeschryver** 2021-09-06 16:24 UTC
