### ISSUE TITLE
File structure suggestion

### ISSUE THREAD

**Issue by moniuch** [ngrx/platform#1986] opened 2019-07-02 08:43 UTC
FEATURE REQUEST

Could we (what I'd call:) improve the folder structure that is being created by the ng add schematics?

IMO, this sort of organization:

```
src
  app
    store
      reducers
        index.ts
      effects
        app.effects.spec.ts
        app.effects.ts
      actions
        app.actions.ts
```

would be much clearer than what we actually get:

```
src
  app
    reducers
      index.ts
    app.effects.spec.ts
    app.effects.ts
```

By _clearer_ I mean two things:
- for a dev jumping on a project: it would be one glimpse to notice: oh, ok, they use **store**, so this is where I should expect to find all the relevant stuff
- for an ngrx beginner: it would help identify all three essential store components: actions + reducers + effects

I think lack of actions in the output is a bad thing, there could at least be an empty folder generated with a `.gitkeep` file. A schematics fo `ng add @ngrx/action` could generate a placeholder file, with perhaps a commented example of the [User Login action](https://ngrx.io/guide/store/actions) code. The schematics do a very useful job preparing a home for reducers and I think actions deserve the same. Having a commented example would make the action creation easier without having to reach out to the examples.

This way, the output would be complete in terms of ngrx store flow and the generated files would not pollute module folders.

**Comment by brandonroberts** [comment] 2019-07-03 13:28
Duplicate of https://github.com/ngrx/platform/issues/1741

**Closed by brandonroberts** 2019-07-03 13:28 UTC
