### ISSUE TITLE
Component store select operator when chained in an http interceptor causes missed requests

### ISSUE THREAD

**Issue by lydemann** [ngrx/platform#3793] opened 2023-03-01 11:00 UTC
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

The simplest way to reproduce this is to create a new Angular apps that loads custom svg icons from Angular material registry while having an HTTP interceptor that is chaining on a ngrx component store select value eg.

`  intercept(
    req: HttpRequest<unknown>,
    next: HttpHandler
  ): Observable<HttpEvent<unknown>> {
    return this.someService.selectValue$.pipe(
      switchMap((studyId) => {
        return next.handle(req);
      })
    );
  }
}
`

I believe this is because component store internally uses a ReplaySubject and requests like Angular Material icon registry load requests are called before the ReplaySubject in NgRx component store is initialized.

### Minimal reproduction of the bug/regression with instructions

The simplest way to reproduce this is to create a new Angular apps that loads custom svg icons from Angular material registry while having an HTTP interceptor that is chaining on a ngrx component store select value eg.

`  intercept(
    req: HttpRequest<unknown>,
    next: HttpHandler
  ): Observable<HttpEvent<unknown>> {
    return this.someService.selectValue$.pipe(
      switchMap((studyId) => {
        return next.handle(req);
      })
    );
  }
}
`

I believe this is because component store internally uses a ReplaySubject and requests like Angular Material icon registry load requests are called before the ReplaySubject in NgRx component store is initialized.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

"@ngrx/component-store": "^14.3.2",
"@angular/core": "^14.2.5"

### Other information

Other similar component store implementation like rx-angular/state uses the scan operator to hold state which might fix this issue.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by timdeschryver** [comment] 2023-03-14 19:04
@lydemann could you please provide a full reproduction?

**Comment by timdeschryver** [comment] 2023-04-15 14:56
I'm closing this one because it doesn't contain a reproduction.
Feel free to reopen/recreate with a reproduction.

**Closed by timdeschryver** 2023-04-15 14:56 UTC
Labels: Needs Reproduction, Project: Component Store
