### ISSUE TITLE
ng serve  failed \platform\example-app\@ngrx\store.ts doesn't exist

### ISSUE THREAD

**Issue by musman92** [ngrx/platform#392] opened 2017-09-14 20:12 UTC
i follow the same instruction listed but it did not work for me

**Comment by brandonroberts** [comment] 2017-09-15 04:04
Can you provide some more details about your environment?

**Comment by shcizo** [comment] 2017-09-15 06:17
I have the same problem. Cloned the repo on a Win10 system, Node 8.5, angular 4.0. I run npm install and the packages seem to be downloaded and installed but when I try to run with either ng server or npm run it fails. 

Error messages start with tons of warnings about "Emitted value instead of an instance of Error" from all kinds of modules (effects, store and so on) and then just as many errors starting with:

"ERROR in ../dist/effects/src/effects_root_module.js
Module not found: Error: Can't resolve '@ngrx/store' in 'c:\Dev\ngrx\dist\effects\src'
resolve '@ngrx/store' in 'c:\Dev\ngrx\dist\effects\src"

**Comment by 6congyao** [comment] 2017-09-15 07:07
Yes, I also have the same problem when following the instruction.

**Comment by Janzelf** [comment] 2017-09-15 09:03
Most of these error messages go away if you do
npm install @ngrx/store
npm install @ngrx/effects
npm install @ngrx/store-devtools
npm install @ngrx/router-storage
... etc.
However since about a week 
ng serve 
results in 
webpack fails to compile.
ERROR in C:/ngprojects/platform/example-app/app/books/reducers/books.ts (2,65): Cannot find module '@ngrx/entity'.
npm install @ngrx/entity   fails.

**Comment by 6congyao** [comment] 2017-09-15 16:53
Well, I updated my NPM version from 3.x to 5.4.x and this issue has gone.

**Comment by brandonroberts** [comment] 2017-09-19 12:43
Seems like a duplicate of #123. Use yarn to install dependencies instead

**Closed by brandonroberts** 2017-09-19 12:43 UTC

**Comment by marcusbelcher** [comment] 2017-12-11 20:25
I encountered the same issue. 

- macOS 10.13.1
- VSCode 1.18.1
- yarn 1.3.2
- npm 5.5.2
- node 9.2.1

The process is as follows:
- git clone https://github.com/ngrx/platform.git
- cd platform
- yarn
- yarn run build && yarn run cli serve

Gave the 'ng serve failed \platform\example-app\@ngrx\store.ts doesn't exist' error

However doing:
- yarn run example:start

Worked perfectly fine, and after doing 'yarn run example:start' twice and then 'yarn run build && yarn run cli serve', the latter started working...

So if anyone comes across the same error try doing the above...

**Comment by rmrfhome** [comment] 2017-12-15 13:42
I've the same problem as @marcusbelcher 
`npm install <missing package>` fixes this issue
