### ISSUE TITLE
StoreDevtools error

### ISSUE THREAD

**Issue by axtho** [ngrx/platform#30] opened 2017-05-26 12:33 UTC
Setup same as #29 ... I followed the docs more closely now. I get:

```
unhandled Promise rejection: Cannot read property 'asObservable' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'asObservable' of undefined
    at new StoreDevtools (store-devtools.es5.js:544)
```

The import section from the app.module.ts looks like this:

```
imports: [
        BrowserModule,
        BrowserAnimationsModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        FlexLayoutModule,

        AppMaterialModule,
        AppRoutingModule,
        MHCoreModule,

        StoreModule.forRoot(reducers),
        StoreRouterConnectingModule,
        !environment.prod ? StoreDevtoolsModule.instrument() : [],

        EffectsModule.forRoot(),
        EffectsModule.run(PersonEffects),
        EffectsModule.run(AuthEffects),

        CommonModule,
        SearchModule,
        InteractionModule
    ],
```

The reducer import like so (partial):
```
import {
    ActionReducerMap,
    createSelector } from '@ngrx/store';
import { routerReducer, RouterReducerState } from '@ngrx/router-store';

import * as interaction from 'mh-core';
import * as person from 'mh-core';
import * as settings from 'mh-core';
import * as auth from 'mh-core';

export interface AppState {
    interaction: interaction.InteractionState;
    person: person.PersonState;
    settings: settings.SettingsState;
    auth: auth.AuthState;
    router: RouterReducerState;
}

export const reducers: ActionReducerMap<AppState> = {
    interaction: interaction.interactionReducer,
    person: person.personReducer,
    settings: settings.settingsReducer,
    auth: auth.authReducer,
    router: routerReducer
};
```

**Comment by llwt** [comment] 2017-05-29 03:46
Running into the same issue, you ever find a solution?

**Comment by axtho** [comment] 2017-05-29 08:04
@llwt unfortunately not yet. I have reverted back to the 2.x branch because I don't have the time to debug alpha versions.

**Comment by llwt** [comment] 2017-05-30 04:39
Hmm, so I think I tracked it down to the `injector.get(StoreDevTools)` call in `createStateObservable` of [instrument.ts](https://github.com/ngrx/platform/blob/master/modules/store-devtools/src/instrument.ts#L44).

It looks the eager provider calling `injector.get()` winds up with the `ActionSubject` from `@ngrx/store` not being present in the DI container at the time of instantiation and injecting undefined into the `StoreDevTools`. Playing around with it, if I provide `StoreDevTools` and `State` to the `createStateObservable` factory deps everything works:
```typescript
// ...
export function createStateObservable(shouldInstrument: boolean, devTools: StoreDevtools, state: State<any>) {
  return shouldInstrument ? devTools.state : state;
}
// ...
export class StoreDevtoolsModule {
  static instrument(options: StoreDevtoolsOptions = {}): ModuleWithProviders {
    return {
      ngModule: StoreDevtoolsModule,
      providers: [    
        // ...
        {
          provide: StateObservable,
          deps: [ SHOULD_INSTRUMENT, StoreDevtools, State, ],
          useFactory: createStateObservable
        },
        // ...
```
Although, If I'm understanding everything correctly though that leads to the `StoreDevTools` being bootstrapped regardless of whether `SHOULD_INSTRUMENT` is true.

I'm not sure what the _correct_ solution to get this working would be. I have a feeling this issue is already understood by the project maintainers.

Probably related to: [Angular #15501](https://github.com/angular/angular/issues/15501)

**Comment by llwt** [comment] 2017-05-30 04:47
So that actually doesn't work as expected. The dev tools work but all actions end up being fired twice...

**Comment by boneskull** [comment] 2017-06-01 08:16
My WAG is that `StoreModule` [isn't actually providing anything](https://github.com/ngrx/platform/blob/master/modules/store/src/store_module.ts#L35), because it's been split into `StoreFeatureModule` and `StoreRootModule`.

I'll try to test this hypothesis, but I'm new to the toolchain..

**Comment by boneskull** [comment] 2017-06-01 08:50
n/m; there are a bunch of unused imports in the devtools code, so it's tough to determine intent or if things are half-implemented.  I'm also an Angular 2+ noob, so can't be of much help here

**Comment by msandeeprao38** [comment] 2017-06-07 19:10
@axtho @llwt Running into the same issue. Any solution for this as of now or is it better to revert back to 2.x versions

**Comment by axtho** [comment] 2017-06-07 19:12
@msandeeprao38 I back on 2.x for now. It doesn't seem a hight priority to get 4.x on the road soon :) Maybe @MikeRyanDev or @brandonroberts could guestimate on this?

**Comment by boneskull** [comment] 2017-06-08 05:56
I also went back to 2.x; works well enough

**Comment by llwt** [comment] 2017-06-08 14:56
Rolled back to 2.x here as well. An update on the status of this from @MikeRyanDev or @brandonroberts would be really helpful, the original ETA was "sometime in May"?

**Comment by boneskull** [comment] 2017-06-08 17:55
You can always move that ETA up by contributing back to the project yourself.

**Comment by llwt** [comment] 2017-06-08 18:24
@boneskull I'm trying :P see my earlier comments.

**Comment by drew-moore** [comment] 2017-06-12 05:14
:-) This seems to be fixed as of today's "nightly" build (store-devtools-builds#c242ff2). 

Thanks team!

**Comment by axtho** [comment] 2017-06-12 08:06
@drew-moore yes? I just pulled the latest via `"@ngrx/store-devtools": "github:ngrx/store-devtools-builds",` and I still get the same error:

```
Unhandled Promise rejection: Cannot read property 'asObservable' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'asObservable' of undefined
    at new StoreDevtools (store-devtools.es5.js:544)
    at _createClass (core.es5.js:9615)
    at _createProviderInstance$1 (core.es5.js:9573)
    at resolveNgModuleDep (core.es5.js:9558)
    at NgModuleRef_.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.NgModuleRef_.get (core.es5.js:10644)
    at createStateObservable (store-devtools.es5.js:696)
    at _callFactory (core.es5.js:9637)
    at _createProviderInstance$1 (core.es5.js:9576)
    at initNgModule (core.es5.js:9527)
    at new NgModuleRef_ (core.es5.js:10635) TypeError: Cannot read property 'asObservable' of undefined
    at new StoreDevtools (http://localhost:4200/vendor.bundle.js:101813:52)
    at _createClass (http://localhost:4200/vendor.bundle.js:47765:26)
    at _createProviderInstance$1 (http://localhost:4200/vendor.bundle.js:47723:26)
    at resolveNgModuleDep (http://localhost:4200/vendor.bundle.js:47708:17)
    at NgModuleRef_.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.NgModuleRef_.get (http://localhost:4200/vendor.bundle.js:48794:16)
    at createStateObservable (http://localhost:4200/vendor.bundle.js:101965:40)
    at _callFactory (http://localhost:4200/vendor.bundle.js:47787:17)
    at _createProviderInstance$1 (http://localhost:4200/vendor.bundle.js:47726:26)
    at initNgModule (http://localhost:4200/vendor.bundle.js:47677:13)
    at new NgModuleRef_ (http://localhost:4200/vendor.bundle.js:48785:9)
```

**Comment by drew-moore** [comment] 2017-06-12 20:51
@axtho try pulling the latest store build too

**Comment by axtho** [comment] 2017-06-13 06:03
@drew-moore I am upgrading all my deps each day :) So that's not it ... what is your setup (npm, angular, TS, etc)?

I think it is what @MikeRyanDev has already mentioned in the new example app:

> Both @ngrx/store and @ngrx/store-devtools now have mixed eager providers making it hard to debug undefined injector errors, see angular/angular#15501

But I am still curious why it seems to work for some and for others not. Does it have to do with how many eager providers are already setup before dev tools kick in?

**Comment by bbaia** [comment] 2017-06-19 22:37
I also have an error with latest nightly builds:
```
zone.js:569 Unhandled Promise rejection: Cannot read property 'lift' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'lift' of undefined
    at observeOn (observeOn.js:57)
    at new State (store.es5.js:273)
```

**Comment by axtho** [comment] 2017-06-20 06:46
@bbaia I am certain that has to do with the above mentioned open ticket on angular (angular/angular#15501). We seem to get errors on different points, which makes sense when you think about eager loading to be the issue: it depends on your specific setup, how many modules are being loaded by the time the devtools kick in.

**Comment by bbaia** [comment] 2017-06-20 08:52
I'm using lazy features modules

**Comment by wpcfan** [comment] 2017-06-23 01:11
any update? I ran into this issue too, it is painful without dev tools around

**Comment by axtho** [comment] 2017-07-02 20:23
@robwormald @MikeRyanDev is there another solution to this beside waiting for the issue at angular to be resolved? It is quite painful without the dev tools.

**Comment by diicar** [comment] 2017-07-02 21:06
@axtho meanwhile u can log the actions:  **action$.subscribe(a => console.log(a))**

**Comment by brandonroberts** [comment] 2017-07-03 00:06
@axtho have you tried the method above of putting the devtools and store in the AppModule

**Comment by axtho** [comment] 2017-07-03 04:35
@brandonroberts if you look at the appModule snippet at the start of the issue you see that it is what I am doing. Currently I am not lazy loading any store stuff or putting it into a common module.

Looking at the error it says that actions are undefined. Is that because the actions have not loaded by the time the devtools connect?

**Comment by jinder** [comment] 2017-07-03 09:09
@brandonroberts @axtho Also seeing this error when importing StoreDevtoolsModule only in the App module.

**Closed** 2017-07-03 20:36 UTC

**Comment by bbaia** [comment] 2017-07-03 21:55
Latest build works like a charm!

Thanks!

**Comment by axtho** [comment] 2017-07-04 05:20
@brandonroberts thanks for doing this despite the holiday ;) it works now.

**Comment by bbaia** [comment] 2017-07-04 08:17
But it really slow down the app, normal ?

**Comment by axtho** [comment] 2017-07-04 08:38
yes, i also noticed that ... maybe that has to do with the subscription not being closed properly?

**Comment by brandonroberts** [comment] 2017-07-04 15:44
Leaving the devtools will slow down you app as it's retaining all the actions and states by default. You can use the `maxAge` option to limit the number of states retained.

```ts
StoreDevtoolsModule.instrument({
  maxAge: 25
})
```

**Comment by dragGH102** [comment] 2018-01-17 14:26
I'm actually getting this error even with the latest build. Same structure: DevTools imported in app.module.

Note: the store is a separate module imported in `AppModule` (I use `https://github.com/kmathy/ngx-reduxor`)

**Comment by siordache94** [comment] 2018-07-15 11:33
Error still present, what's the main workaround ? Should I go down to some version?

**Comment by mayurgaud** [comment] 2018-07-18 13:30
I'm also facing the similar issue

`zone.js:680 Unhandled Promise rejection: Cannot read property 'schedule' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'schedule' of undefined
    at ObserveOnSubscriber.scheduleMessage (observeOn.js:99)
    at ObserveOnSubscriber._error (observeOn.js:105)
    at ObserveOnSubscriber.Subscriber.error (Subscriber.js:105)
    at ActionsSubject.Observable._trySubscribe (Observable.js:177)
    at ActionsSubject.Subject._trySubscribe (Subject.js:97)
    at ActionsSubject.Observable.subscribe (Observable.js:160)
    at ObserveOnOperator.call (observeOn.js:74)
    at AnonymousSubject.Observable.subscribe (Observable.js:157)
    at WithLatestFromOperator.call (withLatestFrom.js:70)
    at AnonymousSubject.Observable.subscribe (Observable.js:157) TypeError: Cannot read property 'schedule' of undefined
    at ObserveOnSubscriber.scheduleMessage (webpack-internal:///./node_modules/rxjs/_esm5/operators/observeOn.js:105:33)
    at ObserveOnSubscriber._error (webpack-internal:///./node_modules/rxjs/_esm5/operators/observeOn.js:111:14)
    at ObserveOnSubscriber.Subscriber.error (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:110:18)
    at ActionsSubject.Observable._trySubscribe (webpack-internal:///./node_modules/rxjs/Observable.js:177:18)
    at ActionsSubject.Subject._trySubscribe (webpack-internal:///./node_modules/rxjs/Subject.js:97:51)
    at ActionsSubject.Observable.subscribe (webpack-internal:///./node_modules/rxjs/Observable.js:160:93)
    at ObserveOnOperator.call (webpack-internal:///./node_modules/rxjs/_esm5/operators/observeOn.js:80:23)
    at AnonymousSubject.Observable.subscribe (webpack-internal:///./node_modules/rxjs/Observable.js:157:22)
    at WithLatestFromOperator.call (webpack-internal:///./node_modules/rxjs/_esm5/operators/withLatestFrom.js:73:23)
    at AnonymousSubject.Observable.subscribe (webpack-internal:///./node_modules/rxjs/Observable.js:157:22)`

Followed the steps present here https://github.com/ngrx/platform/blob/master/docs/store/README.md

**Comment by brandonroberts** [comment] 2018-07-18 14:59
@mayurgaud open a issue with a reproduction of the error.
