### ISSUE TITLE
Initial state still empty in AOT as of v4.1.0

### ISSUE THREAD

**Issue by GiuseppePiscopo** [ngrx/platform#515] opened 2017-10-21 10:34 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

I've read through related issues, #116 , #189 , #247 and especially, #258 . I've **successfully** applied the `InjectionToken`/`getReducers` workaround as suggested in [latest comment](https://github.com/ngrx/platform/issues/258#issuecomment-323345740) by @brandonroberts . 

It is not clear to me whether injecting reducers map by token is *the* way to go forward or what. If that's the case, would you consider a PR making this explicit in docs? Otherwise, this issue is to notify that AOT problem still persists as of 4.1.0.

## What is the current behavior?
When a ng-cli based project is built for production with AOT enabled, at runtime the application state seems to be stuck as an empty object `{}`. Initial state passed in single reducers seems to be ignored. Also trying to pass initial state when calling `StoreModule.forRoot(...)` seems to be ignored. The only change I could experience in application state has been when some router action was fired: then just the router slice of app state was created.  
When project is built for development, app state is correctly populated. I've not tried building for production but with AOT *disabled*.

## Expected behavior:
Even when compiling project for production, with AOT enabled, application state should be correctly populated as in development build.

## Minimal reproduction of the problem with instructions:

Sorry for not providing a demo. Is there a seed project available in stackblitz? I took it you can try AOT builds there, as opposed to Plunker.  
Steps:
* Create a project with ng-cli
* Add ngrx store + effects + router-store 4.1.0. Also useful is store-devtools. Set those up with a minimal application state
* Build project for development and serve that: observe no runtime errors and, from Redux devtools, state is filled
* Build project for production and serve that: see runtime errors and state is empty

## Version of affected browser(s),operating system(s), npm, node and ngrx:
Tried with Google Chrome 61.0.3163.100 64 bits  
Windows 10 64 bits  
node v6.9.5  
npm 3.10.10
ngrx 4.1.0
angular 4.3.4

**Comment by brandonroberts** [comment] 2017-10-25 01:33
@GiuseppePiscopo I haven't been able to reproduce this in the example app using the `-prod` flag. Can you provide a reproduction?

**Comment by GiuseppePiscopo** [comment] 2017-10-25 08:34
Ok, I'll try. BTW, where's the example app? And, is there a plunker or stackblitz seed, ngrx-included, to start with? Thanks

**Comment by ebduhon** [comment] 2017-10-26 15:30
Can you update the example-app to reflect the documentation as it relates to using InjectionTokens, I found this to be a source of inconsistent behavior between root, eagerly loaded features, and lazily loaded features; as lazily loaded features initial state is empty. As well dispatching actions to modify state of lazily loaded features will reflect in store-devtools as expected; however, subsequently dispatching actions to modify state of root causes lazily loaded state to be lost.

**Comment by brandonroberts** [comment] 2017-11-03 01:02
The example app is in this repo https://github.com/ngrx/platform/tree/master/example-app

**Comment by GiuseppePiscopo** [comment] 2017-11-04 00:36
Thanks, currently working at it. Actually I first "moved" example app into a new empty ng-cli project. At the moment I'm not able to reproduce the issue there.

If it might help: initially I met some funny errors related to angular material and MaterialModule not being defined. Apparently there have been some breaking changes across beta versions and one way to fix them is by pinning them to some specific versions:

```js
"@angular/material": "2.0.0-beta.7",
"@angular/cdk": "2.0.0-beta.8",
```

**Comment by GiuseppePiscopo** [comment] 2017-11-15 11:20
As said, I was not able to reproduce the issue then, and I'm not having time to try again, so I'd say we can close this.

OT you might want to give a shot at that dependency issue mentioned in comment above. HTH

Regards

**Comment by brandonroberts** [comment] 2017-11-18 18:38
We landed a PR to lock the material versions. Thanks

**Closed by brandonroberts** 2017-11-18 18:38 UTC
Labels: bug, Project: Store
