### ISSUE TITLE
Inconsistent providing of services leads to problems with module federation

### ISSUE THREAD

**Issue by KimFFVII** [ngrx/platform#4248] opened 2024-02-15 10:12 UTC
### Which @ngrx/* package(s) are the source of the bug?

effects

### Minimal reproduction of the bug/regression with instructions

We are currently working on microfrontend applications using module federation and encountered a problem like in this issue #3700. 
After reading through the issue, we found out that our situation is the same as mentioned in this [comment ](https://github.com/ngrx/platform/issues/3700#issuecomment-1728712071) by @Achilles1515, where we only use NgRx in the microfrontend app and do not use NgRx in the shell. There is also a solution provided by @Achilles1515 here in this [comment ](https://github.com/ngrx/platform/issues/3700#issuecomment-1761742224) with [this Stackblitz](https://stackblitz.com/edit/angular-ivy-ojly3v?file=src%2Fmodules%2Feffects%2Fsrc%2Feffects_module.ts,src%2Fmodules%2Feffects%2Fsrc%2Feffects_runner.ts,src%2Fmodules%2Feffects%2Fsrc%2Factions.ts,src%2Fmodules%2Feffects%2Fsrc%2Feffect_sources.ts).

Just do the following steps in that Stackblitz to make it work like he described in the comment by removing the `{ providedIn: 'root' }` and adding the affected classes to the providers in the `EffectsModule.forRoot` :
1.	In effects_runner.ts comment line 7 and uncomment line 8
2.	In actions.ts comment line 11 and uncomment line 12
3.	In effects_module.ts uncomment lines 59 and 61

This works in that Stackblitz even without doing the changes for effect_sources and we also tried it in our project with NgRx version 15 which is working.

[This PR](https://github.com/ngrx/platform/pull/4119) was created by @brandonroberts to solve the issue, but the fix was done differently and not like @Achilles1515 suggested. That PR was closed because it was not a viable solution and we don't really understand why.

So, the question is, why the PR fix was not using the suggested solution of @Achilles1515? What is the problem with that? In our case it works. There might be some other cases that could lead to problems which we don’t know of, so it would be nice if someone could provide us with more information on that or explain it to us so we can support finding a solution that is working for everyone.

This [hack/workaround](https://github.com/ngrx/platform/issues/3700#issuecomment-1762632766) that is also provided by @Achilles1515 is working for us, but it is not ideal to have that in every of our microfrontend apps.

We would really appreciate it if someone could support us in finding a solution for this issue because other people also have the same problem as we can see in this issue #3700
We can also provide a PR for the NgRx versions 15, 16 and 17 with the exact same changes which were done in the [Stackblitz solution ](https://stackblitz.com/edit/angular-ivy-ojly3v?file=src%2Fmodules%2Feffects%2Fsrc%2Feffects_module.ts,src%2Fmodules%2Feffects%2Fsrc%2Feffects_runner.ts,src%2Fmodules%2Feffects%2Fsrc%2Factions.ts,src%2Fmodules%2Feffects%2Fsrc%2Feffect_sources.ts) of @Achilles1515 already mentioned at the beginning.

Thank you in advance!

### Expected behavior

Correctly providing the services.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 15.4.0
Angular: 15.2.7
Node: 20.11.0

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by markostanimirovic** [comment] 2024-02-18 22:01
Closing this issue as a duplicate of #3700. Feel free to share your thoughts there.

**Closed by markostanimirovic** 2024-02-18 22:01 UTC
