### ISSUE TITLE
App not getting started

### ISSUE THREAD

**Issue by nagarjunveni** [ngrx/platform#555] opened 2017-11-09 13:57 UTC
√ Removing "./dist" Folder
√ Compiling packages with NGC
√ Bundling FESMs
√ Down-leveling FESMs to ES5
√ Creating UMD Bundles
√ Renaming package entry files
√ Cleaning TypeScript files
√ Removing remaining sourcemap files
√ Copying type definition files
× Minifying UMD bundles
{ Error: Command failed: "D:\varun_work\ngrx\platform\node_modules\.bin\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map
INFO: Using file from the input source map: store.umd.js
(node:98108) DeprecationWarning: util.error is deprecated. Use console.error instead.
D:\varun_work\ngrx\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226
            sys.error("ERROR: can't read file: " + filename);
                                                   ^

ReferenceError: filename is not defined
    at ReadFileContext.callback (D:\varun_work\ngrx\platform\node_modules\directory-encoder\node_modules\uglify-js\bin\uglifyjs:226:52)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '"D:\\varun_work\\ngrx\\platform\\node_modules\\.bin\\uglifyjs" -c -m --screw-ie8 --comments -o ./dist/store/bundles/store.umd.min.js --source-map ./dist/store/bundles/store.umd.min.js.map --source-map-include-sources ./dist/store/bundles/store.umd.js --in-source-map ./dist/store/bundles/store.umd.js.map' }
error Command failed with exit code 1.

Any help is highly appreciated.

**Comment by brandonroberts** [comment] 2017-11-14 03:39
Duplicate of https://github.com/ngrx/platform/issues/519

**Closed by brandonroberts** 2017-11-14 03:39 UTC
