### ISSUE TITLE
createDenormalizedSelector

### ISSUE THREAD

**Issue by Odonno** [ngrx/platform#2342] opened 2020-01-29 21:46 UTC
## Describe any alternatives/workarounds you're currently using

Create selectors and making the denormalization by hand (selecting different parts of the state and 'merging' them).

However, it can simplified by using the source selector and a function with denormalizations to apply. I would like to see something like that:

```ts
export const selectCities = createDenormalizedSelector(
    selectNormalizedCities,
    city => ({
        country: findOneBy(selectCountries, country => country.name === city.countryName),
        people: findBy(selectPeople, people => people.cityId === city.id)
    })
); 
```

## If accepted, I would be willing to submit a PR for this feature

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment] 2020-01-30 15:24
How would the behavior be if `selectCountries` or `selectPeople` would emit a new output?

**Comment by Odonno** [comment] 2020-01-30 20:04
Like a regular selector. I imagine it is some kind of `combineLatest`.

**Comment by brandonroberts** [comment] 2020-02-05 03:27
This seems like a duplicate of https://github.com/ngrx/platform/issues/859

**Closed** 2020-04-26 18:37 UTC
Labels: Project: Store, enhancement
