### ISSUE TITLE
initial state is not working with AOT

### ISSUE THREAD

**Issue by PedroEsperanca** [ngrx/platform#484] opened 2017-10-15 22:46 UTC
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?
The setup described in [the docs](https://github.com/ngrx/platform/blob/master/docs/store/README.md#setup) seems to not work with AOT. As the initial state is not set.

I also tried setting it as a function as mentioned [here](https://github.com/ngrx/platform/blob/master/docs/store/api.md#initial-state-and-ahead-of-time-aot-compilation), but in the reducer itself, not in `App.module.ts` as that doesn't seem to scale well. Also got an empty state.

**Comment by queueseven** [comment] 2017-10-16 07:07
I have the same problem. I basically just gave up trying to upgrade to ngrx 4.

**Comment by brandonroberts** [comment] 2017-10-16 12:01
Please provide a reproduction. We just recently fixed a bug with initialState when used along with metareducers which may be the cause of your issue.

**Comment by brandonroberts** [comment] 2017-10-19 14:36
The latest version of Store has been released as `4.1.0` which includes the fixes for this issue.

**Closed by brandonroberts** 2017-10-19 14:36 UTC

**Comment by meenie** [comment] 2017-11-27 05:36
@brandonroberts I believe I've stumbled across this issue or something close to it.  When setting the `initialState` in `StoreModule.forRoot()` for states that are loaded in via the router's `loadChildren` where you are also loading states in that `StoreModule.forRoot()`, the `initialState` gets overwritten.  This doesn't happen when running `ng serve`.  I've found a fix, but it kinda sucks.  Here's the [release](https://github.com/meenie/bang-for-reddit/releases/tag/v0.3.0) before the fix so you can run it yourself to see.  And here's the [release](https://github.com/meenie/bang-for-reddit/releases/tag/v0.4.0) that fixes it.  Basically, the `initialState` needs to include the `initialState` of all reducers that have initial state.

**Comment by meenie** [comment] 2017-11-27 06:12
I've [released](https://github.com/meenie/bang-for-reddit/releases/tag/v0.5.0) a followup fix which clears up a race-case issue where the state was being manipulated before the lazy loaded state gets loaded.
